async function createGBCModule(moduleArg={}){var moduleRtn;var h=moduleArg,aa=[],ca="./this.program",da=import.meta.url,ea="",fa;try{ea=(new URL(".",da)).href}catch{}fa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ha=console.log.bind(console),k=console.error.bind(console),ka,la=!1,ma,na,oa,pa=!1,qa=!1;
function ra(){var a=sa.buffer;h.HEAP8=m=new Int8Array(a);ta=new Int16Array(a);h.HEAPU8=q=new Uint8Array(a);ua=new Uint16Array(a);r=new Int32Array(a);t=new Uint32Array(a);u=new Float32Array(a);v=new Float64Array(a);w=new BigInt64Array(a);new BigUint64Array(a)}function va(){wa();xa(ya);za=!1;Aa(0);for(var a of Ba)a&&Ca(a);qa=!0}function Da(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);la=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");oa?.(a);throw a;}var Ga;
async function Ha(a){if(!ka)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==Ga&&ka)a=new Uint8Array(ka);else throw"both async and sync fetching of the wasm failed";return a}async function Ia(a,b){try{var c=await Ha(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),Da(d)}}
async function Ja(a){var b=Ga;if(!ka)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return Ia(b,a)}class Ka{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var ta,r,w,m,u,v,ua,t,q,xa=a=>{for(;0<a.length;)a.shift()(h)},La=[],Ma=[],Na=()=>{var a=h.preRun.shift();Ma.push(a)},y=!1;
function Oa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":m[a]=b;break;case "i8":m[a]=b;break;case "i16":ta[a>>1]=b;break;case "i32":r[a>>2]=b;break;case "i64":w[a>>3]=BigInt(b);break;case "float":u[a>>2]=b;break;case "double":v[a>>3]=b;break;case "*":t[a>>2]=b;break;default:Da(`invalid type for setValue: ${c}`)}}
var Pa=[],z=a=>{var b=Pa[a];b||(Pa[a]=b=Qa.get(a));return b},B=()=>{var a=r[+Ra>>2];Ra+=4;return a},Sa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ta=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Sa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ua=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Va=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Wa=()=>a=>crypto.getRandomValues(a),Xa=a=>{(Xa=Wa())(a)},Ya=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Sa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Za=globalThis.TextDecoder&&new TextDecoder,D=(a,b=0,c)=>{var d=
b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Za)return Za.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},$a=[],ab=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?
b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},bb=[];
function cb(a,b){bb[a]={input:[],output:[],se:b};db(a,eb)}
var eb={open(a){var b=bb[a.node.Ke];if(!b)throw new F(43);a.Vd=b;a.seekable=!1},close(a){a.Vd.se.Qe(a.Vd)},Qe(a){a.Vd.se.Qe(a.Vd)},read(a,b,c,d){if(!a.Vd||!a.Vd.se.Hf)throw new F(60);for(var e=0,f=0;f<d;f++){try{var g=a.Vd.se.Hf(a.Vd)}catch(l){throw new F(29);}if(void 0===g&&0===e)throw new F(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.te=Date.now());return e},write(a,b,c,d){if(!a.Vd||!a.Vd.se.qf)throw new F(60);try{for(var e=0;e<d;e++)a.Vd.se.qf(a.Vd,b[c+e])}catch(f){throw new F(29);
}d&&(a.node.ce=a.node.Zd=Date.now());return e}},fb={Hf(){a:{if(!$a.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(ab(a)+1);a=E(a,b,0,b.length);b.length=a;$a=b}b=$a.shift()}return b},qf(a,b){null===b||10===b?(ha(D(a.output)),a.output=[]):0!=b&&a.output.push(b)},Qe(a){0<a.output?.length&&(ha(D(a.output)),a.output=[])},ng(){return{Gg:25856,Ig:5,Fg:191,Hg:35387,Eg:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0]}},og(){return 0},pg(){return[24,80]}},gb={qf(a,b){null===b||10===b?(k(D(a.output)),a.output=[]):0!=b&&a.output.push(b)},Qe(a){0<a.output?.length&&(k(D(a.output)),a.output=[])}},G={le:null,re(){return G.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);G.le||(G.le={dir:{node:{je:G.Rd.je,me:G.Rd.me,He:G.Rd.He,Ue:G.Rd.Ue,Nf:G.Rd.Nf,Qf:G.Rd.Qf,Ve:G.Rd.Ve,rf:G.Rd.rf,We:G.Rd.We},stream:{ke:G.Sd.ke}},file:{node:{je:G.Rd.je,me:G.Rd.me},
stream:{ke:G.Sd.ke,read:G.Sd.read,write:G.Sd.write,Jf:G.Sd.Jf,Lf:G.Sd.Lf}},link:{node:{je:G.Rd.je,me:G.Rd.me,Le:G.Rd.Le},stream:{}},Ef:{node:{je:G.Rd.je,me:G.Rd.me},stream:hb}});c=ib(a,b,c,d);H(c.mode)?(c.Rd=G.le.dir.node,c.Sd=G.le.dir.stream,c.Xd={}):32768===(c.mode&61440)?(c.Rd=G.le.file.node,c.Sd=G.le.file.stream,c.be=0,c.Xd=G.dg??(G.dg=new Uint8Array(0))):40960===(c.mode&61440)?(c.Rd=G.le.link.node,c.Sd=G.le.link.stream):8192===(c.mode&61440)&&(c.Rd=G.le.Ef.node,c.Sd=G.le.Ef.stream);c.te=c.ce=
c.Zd=Date.now();a&&(a.Xd[b]=c,a.te=a.ce=a.Zd=c.te);return c},Rd:{je(a){var b={};b.cg=8192===(a.mode&61440)?a.id:1;b.lg=a.id;b.mode=a.mode;b.sg=1;b.uid=0;b.ig=0;b.Ke=a.Ke;H(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.be:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.te=new Date(a.te);b.ce=new Date(a.ce);b.Zd=new Date(a.Zd);b.Vf=4096;b.Wf=Math.ceil(b.size/b.Vf);return b},me(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.be!=b&&
(c=a.Xd,a.Xd=new Uint8Array(b),a.Xd.set(c.subarray(0,Math.min(b,a.be))),a.be=b))},He(){G.af||(G.af=new F(44),G.af.stack="<generic error, no stack>");throw G.af;},Ue(a,b,c,d){return G.createNode(a,b,c,d)},Nf(a,b,c){try{var d=jb(b,c)}catch(f){}if(d){if(H(a.mode))for(var e in d.Xd)throw new F(55);kb(d)}delete a.parent.Xd[a.name];b.Xd[c]=a;a.name=c;b.Zd=b.ce=a.parent.Zd=a.parent.ce=Date.now()},Qf(a,b){delete a.Xd[b];a.Zd=a.ce=Date.now()},Ve(a,b){var c=jb(a,b),d;for(d in c.Xd)throw new F(55);delete a.Xd[b];
a.Zd=a.ce=Date.now()},rf(a){return[".","..",...Object.keys(a.Xd)]},We(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},Le(a){if(40960!==(a.mode&61440))throw new F(28);return a.link}},Sd:{read(a,b,c,d,e){if(e>=a.node.be)return 0;d=Math.min(a.node.be-e,d);b.set(a.node.Xd.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===m.buffer&&(f=!1);if(!d)return 0;a=a.node;a.ce=a.Zd=Date.now();if(f)a.Xd=b.subarray(c,c+d),a.be=d;else if(0===a.be&&0===e)a.Xd=b.slice(c,c+d),a.be=d;else{f=e+d;var g=a.Xd.length;
g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.Xd.subarray(0,a.be),a.Xd=new Uint8Array(f),a.Xd.set(g));a.Xd.set(b.subarray(c,c+d),e);a.be=Math.max(a.be,e+d)}return d},ke(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.be);if(0>b)throw new F(28);return b},Jf(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(43);a=a.node.Xd;if(e&2||a.buffer!==m.buffer){d=!0;Da();e=void 0;if(!e)throw new F(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,
c+b):a=Array.prototype.slice.call(a,c,c+b);m.set(a,e)}}else d=!1,e=a.byteOffset;return{Xg:e,Bg:d}},Lf(a,b,c,d){G.Sd.write(a,b,0,d,c,!1);return 0}}},lb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},mb=[],nb=null,ob={},Ba=[],pb=1,I=null,za=!1,qb=!0,F=class{name="ErrnoError";constructor(a){this.ee=a}},rb=class{Yd={};node=null;get flags(){return this.Yd.flags}set flags(a){this.Yd.flags=a}get position(){return this.Yd.position}set position(a){this.Yd.position=a}},sb=class{Rd={};Sd={};Je=null;constructor(a,
b,c,d){a||=this;this.parent=a;this.re=a.re;this.id=pb++;this.name=b;this.mode=c;this.Ke=d;this.te=this.ce=this.Zd=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function tb(a,b={}){if(!a)throw new F(44);b.gf??(b.gf=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(l=>!!l);for(var d=nb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Ua(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ta(e+"/"+a[f]);try{d=jb(d,a[f])}catch(l){if(44===l?.ee&&g&&b.tg)return{path:e};throw l;}!d.Je||g&&!b.gf||(d=d.Je.root);if(40960===(d.mode&61440)&&(!g||b.ff)){if(!d.Rd.Le)throw new F(52);
d=d.Rd.Le(d);"/"===d.charAt(0)||(d=Ua(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new F(32);}function ub(a){for(var b;;){if(a===a.parent)return a=a.re.Kf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function vb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%I.length}function kb(a){var b=vb(a.parent.id,a.name);if(I[b]===a)I[b]=a.Be;else for(b=I[b];b;){if(b.Be===a){b.Be=a.Be;break}b=b.Be}}
function jb(a,b){var c=H(a.mode)?(c=wb(a,"x"))?c:a.Rd.He?0:2:54;if(c)throw new F(c);for(c=I[vb(a.id,b)];c;c=c.Be){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Rd.He(a,b)}function ib(a,b,c,d){a=new sb(a,b,c,d);b=vb(a.parent.id,a.name);a.Be=I[b];return I[b]=a}function H(a){return 16384===(a&61440)}function wb(a,b){return qb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}
function xb(a,b){if(!H(a.mode))return 54;try{return jb(a,b),20}catch(c){}return wb(a,"wx")}function J(a){a=Ba[a];if(!a)throw new F(8);return a}function yb(a,b=-1){a=Object.assign(new rb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Ba[b])break a;throw new F(33);}a.ve=b;return Ba[b]=a}function zb(a,b=-1){a=yb(a,b);a.Sd?.Og?.(a);return a}function Ab(a,b){var c=null?.Sd.me,d=c?null:a;c??=a.Rd.me;if(!c)throw new F(63);c(d,b)}var hb={open(a){a.Sd=ob[a.node.Ke].Sd;a.Sd.open?.(a)},ke(){throw new F(70);}};
function db(a,b){ob[a]={Sd:b}}function Bb(a,b){var c="/"===b;if(c&&nb)throw new F(10);if(!c&&b){var d=tb(b,{gf:!1});b=d.path;d=d.node;if(d.Je)throw new F(10);if(!H(d.mode))throw new F(54);}b={type:a,Vg:{},Kf:b,rg:[]};a=a.re(b);a.re=b;b.root=a;c?nb=a:d&&(d.Je=b,d.re&&d.re.rg.push(b))}function Cb(a,b,c){var d=tb(a,{parent:!0}).node;a=Va(a);if(!a)throw new F(28);if("."===a||".."===a)throw new F(20);var e=xb(d,a);if(e)throw new F(e);if(!d.Rd.Ue)throw new F(63);return d.Rd.Ue(d,a,b,c)}
function K(a){return Cb(a,16895,0)}function Db(a,b,c){"undefined"==typeof c&&(c=b,b=438);Cb(a,b|8192,c)}function Eb(a,b){if(!Ya(a))throw new F(44);var c=tb(b,{parent:!0}).node;if(!c)throw new F(44);b=Va(b);var d=xb(c,b);if(d)throw new F(d);if(!c.Rd.We)throw new F(63);c.Rd.We(c,b,a)}
function Fb(a,b,c=438){if(""===a)throw new F(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var f=tb(a,{ff:!(b&131072),tg:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new F(20);}else{if(e)throw new F(31);d=Cb(a,c|511,0);f=!0}if(!d)throw new F(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!H(d.mode))throw new F(54);
if(!f&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=H(d.mode)&&("r"!==e||b&576)?31:wb(d,e)):e=44,e))throw new F(e);if(b&512&&!f){e=d;e="string"==typeof e?tb(e,{ff:!0}).node:e;if(H(e.mode))throw new F(31);if(32768!==(e.mode&61440))throw new F(28);if(a=wb(e,"w"))throw new F(a);Ab(e,{size:0,timestamp:Date.now()})}b=yb({node:d,path:ub(d),flags:b&-131713,seekable:!0,position:0,Sd:d.Sd,zg:[],error:!1});b.Sd.open&&b.Sd.open(b);f&&(c&=511,d="string"==typeof d?tb(d,{ff:!0}).node:
d,Ab(d,{mode:c&4095|d.mode&-4096,Zd:Date.now(),Ng:void 0}));return b}function Ca(a){if(null===a.ve)throw new F(8);a.jf&&(a.jf=null);try{a.Sd.close&&a.Sd.close(a)}catch(b){throw b;}finally{Ba[a.ve]=null}a.ve=null}function Gb(a,b,c){if(null===a.ve)throw new F(8);if(!a.seekable||!a.Sd.ke)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.Sd.ke(a,b,c);a.zg=[]}
function Hb(a,b,c,d,e){if(0>d||0>e)throw new F(28);if(null===a.ve)throw new F(8);if(0===(a.flags&2097155))throw new F(8);if(H(a.node.mode))throw new F(31);if(!a.Sd.write)throw new F(28);a.seekable&&a.flags&1024&&Gb(a,0,2);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new F(70);b=a.Sd.write(a,b,c,d,e,void 0);f||(a.position+=b);return b}
function L(a,b,c){a=Ta("/dev/"+a);var d=lb(!!b,!!c);L.If??(L.If=64);var e=L.If++<<8|0;db(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,l,n){for(var p=0,A=0;A<n;A++){try{var x=b()}catch(C){throw new F(29);}if(void 0===x&&0===p)throw new F(6);if(null===x||void 0===x)break;p++;g[l+A]=x}p&&(f.node.te=Date.now());return p},write(f,g,l,n){for(var p=0;p<n;p++)try{c(g[l+p])}catch(A){throw new F(29);}n&&(f.node.ce=f.node.Zd=Date.now());return p}});Db(a,d,e)}
var M={},Ra=void 0,N=0,Ib={},Jb=a=>{if(!(a instanceof Ka||"unwind"==a))throw a;},Kb=a=>{ma=a;y||0<N||(h.onExit?.(a),la=!0);throw new Ka(a);},Lb=()=>{if(!(qa||y||0<N))try{var a=ma;ma=a;y||0<N||va();Kb(a)}catch(b){Jb(b)}},Mb=a=>{if(!qa&&!la)try{a()}catch(b){Jb(b)}finally{Lb()}},Nb=[],Ob=(a,b)=>{Nb.length=0;for(var c;c=q[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Nb.push(112==c?t[b>>2]:106==c?w[b>>3]:105==c?r[b>>2]:v[b>>3]);b+=d?8:4}return Nb},Qb=(a,b,c)=>{b=Ob(b,c);return Pb[a](...b)},$b=(a,b)=>{Rb=
a;Sb=b;if(!Tb)return 1;Ub||(N+=1,Ub=!0);if(0==a)Vb=function(){setTimeout(Wb,Math.max(0,Xb+b-performance.now())|0)};else if(1==a)Vb=function(){Yb(Wb)};else{if(!Zb)if(globalThis.setImmediate)Zb=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Zb=d=>{c.push(d);postMessage("setimmediate","*")}}Vb=function(){Zb(Wb)}}return 0},ic=(a,b,c,d,e)=>{function f(){return g<ac?(--N,Lb(),!1):!0}Tb=a;bc=d;var g=
ac;Ub=!1;Wb=function(){if(!la)if(0<cc.length){var l=cc.shift();l.Qg(l.Cg);if(dc){var n=dc,p=0==n%1?n-1:Math.floor(n);dc=l.Kg?p:(8*n+(p+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=dc??0,p=ec.Pg??0,n?n<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(Wb,0)}else if(f())if(fc=fc+1|0,1==Rb&&1<Sb&&0!=fc%Sb)Vb();else{0==Rb&&(Xb=performance.now());a:if(!la){for(l of gc)if(!1===l())break a;Mb(a);for(n of hc)n()}f()&&Vb()}};e||(0<
b?$b(0,1E3/b):$b(1,1),Vb());if(c)throw"unwind";},Ub=!1,Vb=null,ac=0,Tb=null,bc=0,Rb=0,Sb=0,fc=0,cc=[],gc=[],hc=[];function jc(){Vb=null;ac++}var kc=0;function Yb(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===kc)kc=b+1E3/60;else for(;b+2>=kc;)kc+=1E3/60;setTimeout(a,Math.max(kc-b,0))}}var ec={},Xb,Wb,Zb,dc,ya=[];function lc(a){var b=O.$d[a];b.target.removeEventListener(b.ae,b.Gf,b.ne);O.$d.splice(a,1)}
function mc(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of O.ue)if(e.tf==a&&d(e.Cf,c))return;O.ue.push({tf:a,Mf:b,Cf:c});O.ue.sort((f,g)=>f.Mf-g.Mf)}function nc(a){O.ue=O.ue.filter(b=>b.tf!=a)}function oc(){return navigator.userActivation?navigator.userActivation.isActive:O.kf&&O.Yf.Uf}function pc(){if(oc()){var a=O.ue;O.ue=[];for(var b of a)b.tf(...b.Cf)}}
function P(a){if(!a.target)return-4;if(a.de)a.Gf=function(c){++O.kf;O.Yf=a;pc();a.qe(c);pc();--O.kf},a.target.addEventListener(a.ae,a.Gf,a.ne),O.$d.push(a),O.xg||(ya.push(O.vg),O.xg=!0);else for(var b=0;b<O.$d.length;++b)O.$d[b].target==a.target&&O.$d[b].ae==a.ae&&lc(b--);return 0}function qc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var O={Dg:0,Rg:0,lf:0,Tg:0,yf:0,vf:0,ef:0,Mg:0,nf:0,Lg:0,hf:0,pf:0,xf:0,bh:0,vg(){for(;O.$d.length;)lc(O.$d.length-1);O.ue=[]},kf:0,ue:[],$d:[],wg:(a,b)=>{for(var c=0;c<O.$d.length;++c)O.$d[c].target!=a||b&&b!=O.$d[c].ae||lc(c--)},Yg(a){let b=!1;for(let c=0;c<O.$d.length;++c){const d=O.$d[c];d.target===a.target&&d.ie===a.ie&&d.de===a.de&&d.oe===a.oe&&(lc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},rc=[0,document,window],Q=a=>
{a=2<a?a?D(q,a):"":a;return rc[a]||document.querySelector(a)},tc=a=>{var b=ab(a)+1,c=sc(b);E(a,q,c,b);return c},wc=a=>{var b=uc(),c=sc(8),d=c+4;a=tc(a.id);if(a=Q(a))r[c>>2]=a.width,r[d>>2]=a.height;c=[r[c>>2],r[d>>2]];vc(b);return c},xc=(a,b,c)=>{a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},yc=(a,b,c)=>{if(a.Jg){var d=uc();a=tc(a.id);xc(a,b,c);vc(d)}else a.width=b,a.height=c},zc={},Bc=a=>{function b(){Ac()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),yc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=A,a.style.paddingTop=x,a.style.paddingBottom=C,a.style.marginLeft=ba,a.style.marginRight=ia,a.style.marginTop=ja,a.style.marginBottom=U,document.body.style.margin=Ea,document.documentElement.style.overflow=Fa,document.body.scroll=Jd,a.style.we=Kd,a.Ce&&a.Ce.ye.viewport(0,0,d,e),zc.Ne&&z(zc.Ne)(37,0,
zc.Df))}var c=wc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,A=a.style.paddingRight,x=a.style.paddingTop,C=a.style.paddingBottom,ba=a.style.marginLeft,ia=a.style.marginRight,ja=a.style.marginTop,U=a.style.marginBottom,Ea=document.body.style.margin,Fa=document.documentElement.style.overflow,Jd=document.body.scroll,Kd=a.style.we;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},Cc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Dc=a=>0>rc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Ec=(a,b)=>{if(0!=b.sf||0!=b.Ze){Bc(a);var c=b.yg?innerWidth:screen.width,d=b.yg?innerHeight:screen.height,e=Dc(a),f=e.width;e=e.height;var g=wc(a),l=g[0];g=g[1];3==b.sf?(Cc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.sf&&(c*g<l*d?(f=g*c/l,Cc(a,(d-f)/2,0),d=f):(f=l*d/g,Cc(a,0,(c-f)/2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let p;(p=document.body.style).backgroundColor||(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.hg&&(a.style.we="optimizeSpeed",a.style.we="-moz-crisp-edges",a.style.we="-o-crisp-edges",a.style.we="-webkit-optimize-contrast",a.style.we="optimize-contrast",a.style.we="crisp-edges",a.style.we="pixelated");n=2==b.Ze?devicePixelRatio:1;0!=b.Ze&&(c=c*n|0,d=d*n|0,yc(a,c,d),a.Ce&&a.Ce.ye.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return O.fullscreenEnabled()?-3:-1;zc=b;b.Ne&&z(b.Ne)(37,0,b.Df);return 0},Fc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0};function Ac(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var Gc=a=>{var b=Ac(),c=!!b;m[a]=c;m[a+1]=O.fullscreenEnabled();var d=c?b:O.ug,e=d?.id||"";E(qc(d),q,a+2,128);E(e,q,a+130,128);r[a+260>>2]=d?d.clientWidth:0;r[a+264>>2]=d?d.clientHeight:0;r[a+268>>2]=screen.width;r[a+272>>2]=screen.height;c&&(O.ug=b)},Hc=a=>{N+=1;setTimeout(()=>{--N;Mb(a)},1E4)},Ic=!1,Jc=[];
function Kc(){function a(){Ic=document.pointerLockElement===h.canvas}if(!Lc){Lc=!0;mb.push({canHandle:c=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:Mc(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Mc(d)}));var f=URL.createObjectURL(e);return new Promise((g,l)=>{var n=new Image;n.onload=()=>{var p=document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(f);
g(c)};n.onerror=()=>{k(`Image ${f} could not be decoded`);l()};n.src=f})}});mb.push({canHandle:c=>!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,l=URL.createObjectURL(new Blob([c],{type:Mc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=()=>{if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var p="",A=0,x=0,C=0;C<c.length;C++)for(A=A<<
8|c[C],x+=8;6<=x;){var ba=A>>x-6&63;x-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[ba]}2==x?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(A&3)<<4],p+="=="):4==x&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(A&15)<<2],p+="=");n.src="data:audio/x-"+d.slice(-3)+";base64,"+p;f(n)}};n.src=l;Hc(()=>{f(n)})})});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Ic&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Nc(a){a=a.getContext("2d");if(!a)return null;h.ctx=a;Jc.forEach(b=>b());Kc();return a}function Mc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var Lc,R,Oc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Pc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},
Qc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Rc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Sc=1,Tc=[],S=[],Uc=[],Vc=[],Wc=[],T=[],Xc=[],Yc=[],V=[],Zc={},$c=4,ad=0,bd=a=>{for(var b=Sc++,c=a.length;c<b;c++)a[c]=null;return b},cd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=R[c](),g=f&&bd(d);f?(f.name=g,d[g]=f):W||=1282;r[b+4*e>>2]=g}},ed=(a,b)=>{a.Bf||(a.Bf=a.getContext,a.getContext=function(d,e){e=a.Bf(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?dd(c,b):0},dd=(a,b)=>{var c=
bd(Yc),d={handle:c,attributes:b,version:b.qg,ye:a};a.canvas&&(a.canvas.Ce=d);Yc[c]=d;if("undefined"==typeof b.Ff||b.Ff)if((a=d)||(a=fd),!a.kg){a.kg=!0;a=a.ye;a.Ug=a.getExtension("WEBGL_multi_draw");a.gg=a.getExtension("EXT_polygon_offset_clamp");a.fg=a.getExtension("EXT_clip_control");a.Ag=a.getExtension("WEBGL_polygon_mode");Oc(a);Pc(a);Qc(a);a.pe=a.getExtension("EXT_disjoint_timer_query");for(var e of Rc(a))e.includes("lose_context")||e.includes("debug")||a.getExtension(e)}return c},W,fd,gd=[],
hd=(a,b,c,d,e,f,g,l)=>{b=S[b];if(a=R[a](b,c))d=l&&E(a.name,q,l,d),e&&(r[e>>2]=d),f&&(r[f>>2]=a.size),g&&(r[g>>2]=a.type)},jd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(W||=1280);return;case 36345:d=0;break;case 34466:var e=R.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=R.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":W||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=
0;break;default:W||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+4*a>>2]=e[a];break;case 2:u[b+4*a>>2]=e[a];break;case 4:m[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){W||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:W||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;t[b>>2]=c;t[b+4>>2]=(c-t[b>>2])/4294967296;break;case 0:r[b>>2]=d;break;case 2:u[b>>2]=d;break;case 4:m[b]=d?1:0}}else W||=1281},kd=(a,b,c)=>{if(c){a=R.pe.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d;t[c+4>>2]=(d-t[c>>2])/4294967296}else W||=1281},ld=(a,b,c)=>{if(c){a=R.pe.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;r[c>>2]=d}else W||=1281},md=a=>{var b=ab(a)+1,c=X(b);c&&E(a,q,c,b);return c},nd=()=>{var a=Rc(R);return a=
a.concat(a.map(b=>"GL_"+b))},od=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),pd=a=>{var b=a.Me,c=a.Pf,d;if(!b){a.Me=b={};a.Of={};var e=R.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=R.getActiveUniform(a,d);var g=f.name;f=f.size;var l=od(g);l=0<l?g.slice(0,l):g;var n=a.wf;a.wf+=f;c[l]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Of[n++]=l}}},Y=a=>{var b=R.Zf;if(b){var c=b.Me[a];"number"==typeof c&&(b.Me[a]=c=R.getUniformLocation(b,b.Of[a]+(0<c?`[${c}]`:"")));return c}W||=1282},qd=(a,b,c,d)=>{if(c)if(a=S[a],pd(a),
a=R.getUniform(a,Y(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:u[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:u[c+4*b>>2]=a[b]}else W||=1281},rd=(a,b,c,d)=>{if(c)if(a=R.getVertexAttrib(a,b),34975==b)r[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:u[c>>2]=a;break;case 5:r[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:u[c+
4*b>>2]=a[b];break;case 5:r[c+4*b>>2]=Math.fround(a[b])}else W||=1281},sd=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?r:6==a?u:5==a||28922==a?t:ua;b=d*((ad||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+$c-1&-$c);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},td=[],ud=[],vd=(a,b)=>{if(!O.fullscreenEnabled())return-1;a=Q(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?oc()?Ec(a,b):b.bg?(mc(Ec,1,[a,b]),1):-2:-3:-4},wd=(a,b)=>
{var c={target:Q(2),ae:"beforeunload",ie:28,oe:a,de:b,qe:d=>{var e=z(b)(28,0,a);e&&=e?D(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},ne:!0};return P(c)},xd=(a,b,c,d,e,f)=>{O.ef||(O.ef=X(256));a={target:Q(a),ae:f,ie:e,oe:b,de:d,qe:g=>{var l=g.target.id?g.target.id:"",n=O.ef;E(qc(g.target),q,n+0,128);E(l,q,n+128,128);z(d)(e,n,b)&&g.preventDefault()},ne:c};return P(a)},yd=(a,b,c,d,e)=>{O.hf||(O.hf=X(276));return P({target:a,ae:e,ie:19,oe:b,de:d,qe:f=>{var g=O.hf;Gc(g);z(d)(19,g,b)&&f.preventDefault()},
ne:c})},zd=(a,b,c,d,e,f)=>{O.lf||(O.lf=X(160));a={target:Q(a),ae:f,ie:e,oe:b,de:d,qe:g=>{var l=O.lf;v[l>>3]=g.timeStamp;var n=l>>2;r[n+2]=g.location;m[l+12]=g.ctrlKey;m[l+13]=g.shiftKey;m[l+14]=g.altKey;m[l+15]=g.metaKey;m[l+16]=g.repeat;r[n+5]=g.charCode;r[n+6]=g.keyCode;r[n+7]=g.which;E(g.key||"",q,l+32,32);E(g.code||"",q,l+64,32);E(g.char||"",q,l+96,32);E(g.locale||"",q,l+128,32);z(d)(e,l,b)&&g.preventDefault()},ne:c};return P(a)},Ad=(a,b,c)=>{var d=screen.orientation;O.nf||(O.nf=X(8));return P({target:d,
ae:"change",ie:18,oe:a,de:c,qe:e=>{var f=O.nf,g=["portrait-primary","portrait-secondary","landscape-primary","landscape-secondary"],l=["portrait","portrait","landscape","landscape"],n=0;var p=window.screen?screen.orientation||screen.mozOrientation||screen.webkitOrientation:void 0;"object"===typeof p?(n=g.indexOf(p.type),0>n&&(n=l.indexOf(p.type)),0<=n&&(n=1<<n),g=p.angle):g=window.orientation;r[f>>2]=n;r[f+4>>2]=g;z(c)(18,f,a)&&e.preventDefault()},ne:b})},Bd=(a,b,c,d)=>{O.pf||(O.pf=X(257));return P({target:a,
ae:"pointerlockchange",ie:20,oe:b,de:d,qe:e=>{var f=O.pf,g=document.pointerLockElement;m[f]=!!g;var l=g?.id||"";E(qc(g),q,f+1,128);E(l,q,f+129,128);z(d)(20,f,b)&&e.preventDefault()},ne:c})},Cd=(a,b,c,d)=>{O.vf||(O.vf=X(36));a=Q(a);return P({target:a,ae:"resize",ie:10,oe:b,de:d,qe:e=>{if(e.target==a){var f=document.body;if(f){var g=O.vf;r[g>>2]=0;r[g+4>>2]=f.clientWidth;r[g+8>>2]=f.clientHeight;r[g+12>>2]=innerWidth;r[g+16>>2]=innerHeight;r[g+20>>2]=outerWidth;r[g+24>>2]=outerHeight;r[g+28>>2]=pageXOffset|
0;r[g+32>>2]=pageYOffset|0;z(d)(10,g,b)&&e.preventDefault()}}},ne:c})},Dd=(a,b,c)=>{var d=rc[1];O.xf||(O.xf=X(8));return P({target:d,ae:"visibilitychange",ie:21,oe:a,de:c,qe:e=>{var f=O.xf,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);m[f]=document.hidden;r[f+4>>2]=g;z(c)(21,f,a)&&e.preventDefault()},ne:b})},Ed=(a,b,c,d)=>{O.yf||(O.yf=X(96));return P({target:a,Uf:!0,ae:"wheel",ie:9,oe:b,de:d,qe:e=>{var f=O.yf;v[f>>3]=e.timeStamp;var g=f>>2;r[g+2]=e.screenX;r[g+3]=
e.screenY;r[g+4]=e.clientX;r[g+5]=e.clientY;m[f+24]=e.ctrlKey;m[f+25]=e.shiftKey;m[f+26]=e.altKey;m[f+27]=e.metaKey;ta[2*g+14]=e.button;ta[2*g+15]=e.buttons;r[g+8]=e.movementX;r[g+9]=e.movementY;var l=Dc(a);r[g+10]=e.clientX-(l.left|0);r[g+11]=e.clientY-(l.top|0);v[f+64>>3]=e.deltaX;v[f+72>>3]=e.deltaY;v[f+80>>3]=e.deltaZ;r[f+88>>2]=e.deltaMode;z(d)(9,f,b)&&e.preventDefault()},ne:c})},Fd=["default","low-power","high-performance"],Gd={},Id=()=>{if(!Hd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",
PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Gd)void 0===Gd[b]?delete a[b]:a[b]=Gd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Hd=c}return Hd},Hd,Ld=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{"suspended"===a.state&&a.resume()},{once:!0})},Md=(a,b=[])=>{z(a)(...b)},Nd=(a,b,c,d)=>{var e={string:p=>{var A=0;null!==p&&
void 0!==p&&0!==p&&(A=tc(p));return A},array:p=>{var A=sc(p.length);m.set(p,A);return A}};a=h["_"+a];var f=[],g=0;if(d)for(var l=0;l<d.length;l++){var n=e[c[l]];n?(0===g&&(g=uc()),f[l]=n(d[l])):f[l]=d[l]}c=a(...f);return c=function(p){0!==g&&vc(g);return"string"===b?p?D(q,p):"":"boolean"===b?!!p:p}(c)};I=Array(4096);Bb(G,"/");K("/tmp");K("/home");K("/home/web_user");
(function(){K("/dev");db(259,{read:()=>0,write:(d,e,f,g)=>g,ke:()=>0});Db("/dev/null",259);cb(1280,fb);cb(1536,gb);Db("/dev/tty",1280);Db("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Xa(a),b=a.byteLength);return a[--b]};L("random",c);L("urandom",c);K("/dev/shm");K("/dev/shm/tmp")})();
(function(){K("/proc");var a=K("/proc/self");K("/proc/self/fd");Bb({re(){var b=ib(a,"fd",16895,73);b.Sd={ke:G.Sd.ke};b.Rd={He(c,d){c=+d;var e=J(c);c={parent:null,re:{Kf:"fake"},Rd:{Le:()=>e.path},id:c+1};return c.parent=c},rf(){return Array.from(Ba.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.requestAnimationFrame=Yb;h.pauseMainLoop=jc;h.resumeMainLoop=function(){ac++;var a=Rb,b=Sb,c=Tb;Tb=null;ic(c,0,!1,bc,!0);$b(a,b);Vb()};h.preMainLoop&&gc.push(h.preMainLoop);
h.postMainLoop&&hc.push(h.postMainLoop);for(let a=0;32>a;++a)gd.push(Array(a));for(var Od=new Float32Array(288),Z=0;288>=Z;++Z)td[Z]=Od.subarray(0,Z);var Pd=new Int32Array(288);for(Z=0;288>=Z;++Z)ud[Z]=Pd.subarray(0,Z);h.noExitRuntime&&(y=h.noExitRuntime);h.preloadPlugins&&(mb=h.preloadPlugins);h.print&&(ha=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(ka=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ca=h.thisProgram);
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.ccall=Nd;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>Nd(a,b,c,f,d)};h.writeArrayToMemory=(a,b)=>{m.set(a,b)};
var Pb={55484:()=>{"undefined"===typeof h.SDL3&&(h.SDL3={});var a=h.SDL3;"undefined"===typeof a.Ae&&(a.Ae=function(b){return b});"undefined"===typeof a.Xe&&(a.Xe=function(b){return b>>>2})},55798:()=>{h.SDL3.Fe={};h.SDL3.Fe.xe=[];h.SDL3.Fe.xe[0]=void 0;h.SDL3.Fe.xe[1]=void 0},55975:(a,b,c,d,e)=>{var f=h.SDL3.Fe;void 0!==f.xe[a]&&clearInterval(f.xe[a]);f.xe[a]=setInterval(function(){Md(d,[e])},b/c*1E3)},56167:a=>{var b=h.SDL3.Fe;void 0!==b.xe[a]&&clearInterval(b.xe[a]);b.xe[a]=void 0},56298:()=>"undefined"!==
typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,56445:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,56679:()=>{var a=h.SDL3;"undefined"===typeof a.Ud&&(a.Ud={});"undefined"===typeof a.Td&&(a.Td={});a.Wd||("undefined"!==typeof AudioContext?a.Wd=new AudioContext:"undefined"!==typeof webkitAudioContext&&(a.Wd=new webkitAudioContext),a.Wd&&"undefined"===typeof navigator.userActivation&&
Ld(a.Wd));return void 0!==a.Wd},57258:()=>h.SDL3.Wd.sampleRate,57309:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.Td.ge&&(clearInterval(g.Td.ge),g.Td.ge=void 0,g.Td.ze=void 0);g.Td.mf=g.Wd.createMediaStreamSource(l);g.Td.fe=g.Wd.createScriptProcessor(b,a,1);g.Td.fe.onaudioprocess=function(n){void 0!==g&&void 0!==g.Td&&(n.outputBuffer.getChannelData(0).fill(0),g.Td.$e=n.inputBuffer,Md(c,[d]))};g.Td.mf.connect(g.Td.fe);g.Td.fe.connect(g.Wd.destination);g.Td.stream=l}var g=h.SDL3;g.Td.ze=g.Wd.createBuffer(a,
b,g.Wd.sampleRate);g.Td.ze.getChannelData(0).fill(0);g.Td.ge=setInterval(function(){g.Td.$e=g.Td.ze;Md(c,[d])},b/g.Wd.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},59150:(a,b,c,d)=>{var e=h.SDL3;e.Ud.fe=e.Wd.createScriptProcessor(b,0,a);e.Ud.fe.onaudioprocess=function(f){void 0!==e&&void 0!==
e.Ud&&(void 0!==e.Ud.ge&&(clearInterval(e.Ud.ge),e.Ud.ge=void 0,e.Ud.ze=void 0),e.Ud.Oe=f.outputBuffer,Md(c,[d]))};e.Ud.fe.connect(e.Wd.destination);"suspended"===e.Wd.state&&(e.Ud.ze=e.Wd.createBuffer(a,b,e.Wd.sampleRate),e.Ud.ze.getChannelData(0).fill(0),e.Ud.ge=setInterval(function(){"undefined"!==typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.Wd.resume();e.Ud.Oe=e.Ud.ze;Md(c,[d]);e.Ud.Oe=void 0},b/e.Wd.sampleRate*1E3))},60466:a=>{var b=h.SDL3;if(a){void 0!==b.Td.ge&&
clearInterval(b.Td.ge);if(void 0!==b.Td.stream){a=b.Td.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.Td.stream.removeTrack(a[c])}void 0!==b.Td.fe&&(b.Td.fe.onaudioprocess=function(){},b.Td.fe.disconnect());void 0!==b.Td.mf&&b.Td.mf.disconnect();b.Td=void 0}else void 0!=b.Ud.fe&&b.Ud.fe.disconnect(),void 0!==b.Ud.ge&&clearInterval(b.Ud.ge),b.Ud=void 0;void 0!==b.Wd&&void 0===b.Ud&&void 0===b.Td&&(b.Wd.close(),b.Wd=void 0)},61622:(a,b)=>{var c=h.SDL3;a=c.Xe(a);for(var d=c.Ud.Oe.numberOfChannels,
e=0;e<d;++e){var f=c.Ud.Oe.getChannelData(e);if(f.length!=b)throw"Web Audio playback buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=u[a+(g*d+e)]}},62155:(a,b)=>{for(var c=h.SDL3,d=c.Td.$e.numberOfChannels,e=0;e<d;++e){var f=c.Td.$e.getChannelData(e);if(f.length!=b)throw"Web Audio recording buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Oa(a+4*g,f[g]);else for(g=
0;g<b;++g)Oa(a+4*(g*d+e),f[g])}},62782:()=>window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?0:window.matchMedia("(prefers-color-scheme: dark)").matches?1:-1:-1,62991:()=>{if("undefined"!==typeof h.SDL3){var a=h.SDL3;a.uf.removeEventListener("change",a.df);a.uf=void 0;a.df=void 0}},63244:()=>window.innerWidth,63274:()=>window.innerHeight,63305:a=>{h.requestFullscreen=function(){Qd(a)}},63414:()=>{h.requestFullscreen=function(){}},63488:()=>window.innerWidth,63518:()=>window.innerHeight,
63549:a=>{a=document.querySelector(a?D(q,a):"");a.Sf=a.style.position;a.Tf=a.style.top;a.Rf=a.style.left;var b=document.createElement("div");b.id="SDL3_fill_document_background_elements";b.Yd=a;b.Af=a.parentNode;b.zf=a.nextSibling;var c=Array.from(document.body.children),d;for(d of c)b.appendChild(d);document.body.appendChild(b);b.style.display="none";document.body.appendChild(a);a.style.position="fixed";a.style.top="0";a.style.left="0"},64247:()=>{var a=document.getElementById("SDL3_fill_document_background_elements");
if(a){for(a.zf?a.Af.insertBefore(a.Yd,a.zf):a.Af.appendChild(a.Yd);a.firstChild;)document.body.insertBefore(a.firstChild,a);a.Yd.style.position=a.Yd.Sf;a.Yd.style.top=a.Yd.Tf;a.Yd.style.left=a.Yd.Rf;a.remove()}},64806:()=>{if(window.matchMedia){var a=h.SDL3;a.df=function(){Rd()};a.uf=window.matchMedia("(prefers-color-scheme: dark)");a.uf.addEventListener("change",a.df)}},65128:(a,b,c,d,e)=>{a=a?D(q,a):"";b=b?D(q,b):"";c=c?D(q,c):"";d=d?D(q,d):"";var f=e?D(q,e):"";e=document.createElement("dialog");
e.classList.add("SDL3_messagebox");e.id=f;e.style.color=d;e.style.backgroundColor=c;document.body.append(e);d=document.createElement("h1");d.innerText=a;e.append(d);a=document.createElement("p");a.innerText=b;e.append(a);e.showModal()},65669:(a,b,c,d,e,f,g,l)=>{a=a?D(q,a):"";b=b?D(q,b):"";f=f?D(q,f):"";var n=g?D(q,g):"",p=l?D(q,l):"",A=document.getElementById(a);if(!A)return!1;var x=document.createElement("button");x.innerText=b;x.style.borderColor=f;x.style.backgroundColor=n;A.addEventListener("keydown",
function(C){d&&"Enter"===C.key?(C.preventDefault(),x.click()):e&&"Escape"===C.key&&(C.preventDefault(),x.click())});A.addEventListener("cancel",function(C){C.preventDefault()});x.onmouseenter=function(){x.style.backgroundColor=p};x.onmouseleave=function(){x.style.backgroundColor=n};x.onclick=function(){A.close(c)};A.append(x);return!0},66678:a=>{a=a?D(q,a):"";return(a=document.getElementById(a))?a.open:!1},66816:a=>{a=a?D(q,a):"";a=document.getElementById(a);if(!a)return 0;try{return parseInt(a.returnValue)}catch(b){return 0}},
66998:(a,b)=>{alert((a?D(q,a):"")+"\n\n"+(b?D(q,b):""))},67055:(a,b,c,d)=>{d=d?D(q,d):"";var e=document.querySelector(d);d=h.SDL3;if(d.Xf!==e){d.Ee=Nc(e);if(!d.Ee)return!1;d.Xf=e}if(d.w!==a||d.h!==b||d.jg!==d.Ee)d.image=d.Ee.createImageData(a,b),d.w=a,d.h=b,d.jg=d.Ee;a=d.image.data;c/=4;d.ag!==a&&(d.$f=new Int32Array(a.buffer),d.ag=a);a=d.$f;a.set(r.subarray(c,c+a.length));d.Ee.putImageData(d.image,0,0);return!0},67804:()=>{var a=h.SDL3;a.mouse_x=0;a.mouse_y=0;a.mouse_buttons=[];for(var b=0;5>b;++b)a.mouse_buttons[b]=
!1;document.addEventListener("mousemove",function(c){var d=h.SDL3;d.mouse_x=c.clientX;d.mouse_y=c.clientY});document.addEventListener("mousedown",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!0)});document.addEventListener("mouseup",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!1)})},68492:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,
b);e/=4;b=new Int32Array(a.data.buffer);b.set(r.subarray(e,e+b.length));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=Sd(c.length+1);E(c,q,d,c.length+1);return d},69150:a=>{h.canvas&&(h.canvas.style.cursor=a?D(q,a):"")},69233:()=>{h.canvas&&(h.canvas.style.cursor="none")},69302:()=>h.SDL3.mouse_x,69340:()=>h.SDL3.mouse_y,69378:a=>h.SDL3.mouse_buttons[a],69426:a=>{document.he=function(b){"CapsLock"!=b.key&&"NumLock"!=b.key&&"ScrollLock"!=
b.key&&Td(h.SDL3.Ae(a),b.getModifierState("CapsLock"),b.getModifierState("NumLock"),b.getModifierState("ScrollLock"))};document.addEventListener("keydown",document.he)},69853:()=>{document.removeEventListener("keydown",document.he)},69937:a=>{var b=document;b&&(b.Yd=function(c){var d=h.SDL3;c=d.Ie(0,0,c);0!=c&&(Ud(d.Ae(a),c),Vd(c))},b.addEventListener("pointerup",b.Yd))},70298:a=>{var b=h.SDL3;void 0===b.Ie&&(b.Ie=function(c,d,e){if("mouse"==e.pointerType)var f=1;else if("touch"==e.pointerType)f=
2;else if("pen"==e.pointerType)f=3;else return 0;var g=Sd(a);if(0!=g){var l=b.Xe(g);r[l++]=f;r[l++]=e.pointerId;r[l++]="undefined"!==typeof e.button?e.button:-1;r[l++]=e.buttons;r[l++]="pointerdown"==e.type?1:0;u[l++]=e.movementX;u[l++]=e.movementY;u[l++]=e.clientX-c;u[l++]=e.clientY-d;3==f&&(u[l++]=e.pressure,u[l++]=e.$g,u[l++]=e.tiltX,u[l++]=e.tiltY,u[l++]=e.dh)}return g})},71290:a=>{a=a?D(q,a):"";try{var b=document.querySelector(a);if(b)return b===document.activeElement}catch(c){}return!1},71456:()=>
document.hasFocus(),71488:()=>{var a=document;a&&(a.removeEventListener("pointerup",a.Yd),a.Yd=void 0)},71670:()=>document.body.clientWidth,71708:()=>document.body.clientHeight,71747:()=>window.innerWidth,71777:()=>window.innerHeight,71808:()=>window.outerWidth,71838:()=>window.outerHeight,71869:()=>window.pageXOffset,71900:()=>window.pageYOffset,71931:(a,b)=>{var c=document.querySelector(b?D(q,b):"");if(c){var d=h.SDL3;c.Ye=function(e){var f=c.getBoundingClientRect();e=d.Ie(f.left,f.top,e);0!=e&&
(Wd(d.Ae(a),e),Vd(e))};c.De=function(e){var f=c.getBoundingClientRect();e=d.Ie(f.left,f.top,e);0!=e&&(Xd(d.Ae(a),e),Vd(e))};c.he=function(e){var f=c.getBoundingClientRect();e=d.Ie(f.left,f.top,e);0!=e&&(Yd(d.Ae(a),e),Vd(e))};c.style.touchAction="none";c.addEventListener("pointerenter",c.Ye);c.addEventListener("pointerleave",c.De);c.addEventListener("pointercancel",c.De);c.addEventListener("pointerdown",c.he);c.addEventListener("pointermove",c.he);c.addEventListener("pointerup",c.he)}},73319:(a,b,
c)=>{var d=document.querySelector(b?D(q,b):"");if(d){var e=h.SDL3,f=function(g){var l=Sd(c);if(0!=l){var n=l>>2,p=d.getBoundingClientRect();r[n++]=g.clientX-p.left;r[n++]=g.clientY-p.top}return l};e.bf=function(g){g.preventDefault();g=f(g);0!=g&&(Zd(a,g),Vd(g))};d.addEventListener("dragover",e.bf);e.Pe=0;try{K("/tmp/filedrop")}catch(g){}e.cf=function(g){g.preventDefault();if(g.dataTransfer.types.includes("text/plain"))g=md(g.dataTransfer.getData("text/plain")),$d(a,g),ae(g);else if(g.dataTransfer.types.includes("Files")){let l=
0;const n=g.dataTransfer.files.length;for(let p=0;p<n;p++){const A=g.dataTransfer.files.item(p),x=new FileReader;x.readAsArrayBuffer(A);x.onload=function(C){const ba=`/tmp/filedrop/${e.Pe}`;e.Pe+=1;const ia=`${ba}/${A.name}`,ja=md(ia);C=new Uint8Array(C.target.result);try{K(ba);var U=Fb(ia,"w");Hb(U,C,0,C.length,0);Ca(U);be(a,ja)}catch(Ea){}ae(ja);++l;l===n&&ce(a)};x.onerror=function(){++l;l===n&&ce(a)}}}ce(a)};d.addEventListener("drop",e.cf);e.Ge=function(g){g.preventDefault();ce(a)};d.addEventListener("dragend",
e.Ge);d.addEventListener("dragleave",e.Ge)}},75686:a=>{if(a=document.querySelector(a?D(q,a):"")){var b=h.SDL3;a.removeEventListener("dragleave",b.Ge);a.removeEventListener("dragend",b.Ge);a.removeEventListener("drop",b.cf);b.Pe=void 0;"/tmp/filedrop";var c=tb("/tmp/filedrop",{parent:!0}).node,d=Va("/tmp/filedrop"),e=jb(c,d);a:{try{var f=jb(c,d)}catch(l){f=l.ee;break a}var g=wb(c,"wx");f=g?g:H(f.mode)?f===f.parent||"/"===ub(f)?10:0:54}if(f)throw new F(f);if(!c.Rd.Ve)throw new F(63);if(e.Je)throw new F(10);
c.Rd.Ve(c,d);kb(e);a.removeEventListener("dragover",b.bf);b.bf=void 0;b.cf=void 0;b.Ge=void 0}},76516:a=>{if(a=document.querySelector(a?D(q,a):""))a.removeEventListener("pointerenter",a.Ye),a.removeEventListener("pointerleave",a.De),a.removeEventListener("pointercancel",a.De),a.removeEventListener("pointerdown",a.he),a.removeEventListener("pointermove",a.he),a.removeEventListener("pointerup",a.he),a.style.touchAction="",a.Ye=void 0,a.De=void 0,a.he=void 0}},de,Vd,Sd,ae,Aa,X,Wd,Xd,Yd,Ud,Zd,ce,$d,be,
Td,Rd,Qd,wa,ee,vc,sc,uc,sa,Qa,fe={Ra:(a,b)=>z(a)(b),u:function(a,b,c){Ra=c;try{var d=J(a);switch(b){case 0:var e=B();if(0>e)break;for(;Ba[e];)e++;return zb(d,e).ve;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=B(),d.flags|=e,0;case 12:return e=B(),ta[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.ee}},ab:function(a){try{return J(a),0}catch(b){if("undefined"==typeof M||"ErrnoError"!==b.name)throw b;return-b.ee}},
Xa:function(a,b){try{var c=J(a),d=c.node,e=c.Sd.je;a=e?c:d;e??=d.Rd.je;if(!e)throw new F(63);var f=e(a);t[b>>2]=f.cg;t[b+4>>2]=f.mode;t[b+8>>2]=f.sg;t[b+12>>2]=f.uid;t[b+16>>2]=f.ig;t[b+20>>2]=f.Ke;w[b+24>>3]=BigInt(f.size);r[b+32>>2]=4096;r[b+36>>2]=f.Wf;var g=f.te.getTime(),l=f.ce.getTime(),n=f.Zd.getTime();w[b+40>>3]=BigInt(Math.floor(g/1E3));t[b+48>>2]=g%1E3*1E6;w[b+56>>3]=BigInt(Math.floor(l/1E3));t[b+64>>2]=l%1E3*1E6;w[b+72>>3]=BigInt(Math.floor(n/1E3));t[b+80>>2]=n%1E3*1E6;w[b+88>>3]=BigInt(f.lg);
return 0}catch(p){if("undefined"==typeof M||"ErrnoError"!==p.name)throw p;return-p.ee}},_a:function(a,b,c){Ra=c;try{var d=J(a);switch(b){case 21509:return d.Vd?0:-59;case 21505:if(!d.Vd)return-59;if(d.Vd.se.ng){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=B();r[e>>2]=25856;r[e+4>>2]=5;r[e+8>>2]=191;r[e+12>>2]=35387;for(var f=0;32>f;f++)m[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Vd?0:-59;case 21506:case 21507:case 21508:if(!d.Vd)return-59;
if(d.Vd.se.og)for(e=B(),a=[],f=0;32>f;f++)a.push(m[e+f+17]);return 0;case 21519:if(!d.Vd)return-59;e=B();return r[e>>2]=0;case 21520:return d.Vd?-28:-59;case 21537:case 21531:e=B();if(!d.Sd.mg)throw new F(59);return d.Sd.mg(d,b,e);case 21523:if(!d.Vd)return-59;d.Vd.se.pg&&(f=[24,80],e=B(),ta[e>>1]=f[0],ta[e+2>>1]=f[1]);return 0;case 21524:return d.Vd?0:-59;case 21515:return d.Vd?0:-59;default:return-28}}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return-g.ee}},$a:function(a,b,
c,d){Ra=d;try{b=b?D(q,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":J(a).path;if(0==e.length)throw new F(44);b=f+"/"+e}var g=d?B():0;return Fb(b,c,g).ve}catch(l){if("undefined"==typeof M||"ErrnoError"!==l.name)throw l;return-l.ee}},cb:()=>Da(""),Ta:()=>{y=!1;N=0},Ua:(a,b)=>{Ib[a]&&(clearTimeout(Ib[a].id),delete Ib[a]);if(!b)return 0;var c=setTimeout(()=>{delete Ib[a];Mb(()=>ee(a,performance.now()))},b);Ib[a]={id:c,ah:b};return 0},y:Qb,d:(a,b,c)=>{b=Ob(b,c);return Pb[a](...b)},a:Qb,
pc:(a,b,c)=>{b=Ob(b,c);return Pb[a](...b)},dd:()=>{jc();Tb=null},bb:()=>Date.now(),Ma:()=>{if(!O.fullscreenEnabled())return-1;nc(Ec);var a=rc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Wb:()=>{nc(Fc);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},hb:a=>{y=!1;N=0;ma=a;y||0<N||va();Kb(a)},f:()=>devicePixelRatio,b:(a,b,c)=>{a=Q(a);if(!a)return-4;a=
Dc(a);v[b>>3]=a.width;v[c>>3]=a.height;return 0},Oa:a=>{if(!O.fullscreenEnabled())return-1;Gc(a);return 0},X:(a,b)=>{a&&(r[a>>2]=Rb);b&&(r[b>>2]=Sb)},j:()=>performance.now(),Kc:(a,b)=>{r[a>>2]=screen.width;r[b>>2]=screen.height},sa:a=>R.activeTexture(a),ra:(a,b)=>{R.attachShader(S[a],T[b])},Ia:(a,b)=>{R.pe.beginQueryEXT(a,V[b])},qa:(a,b,c)=>{R.bindAttribLocation(S[a],b,c?D(q,c):"")},pa:(a,b)=>{R.bindBuffer(a,Tc[b])},oa:(a,b)=>{R.bindFramebuffer(a,Uc[b])},na:(a,b)=>{R.bindRenderbuffer(a,Vc[b])},ma:(a,
b)=>{R.bindTexture(a,Wc[b])},Aa:a=>{R.bindVertexArray(Xc[a])},la:(a,b,c,d)=>R.blendColor(a,b,c,d),ka:a=>R.blendEquation(a),ja:(a,b)=>R.blendEquationSeparate(a,b),ia:(a,b)=>R.blendFunc(a,b),ha:(a,b,c,d)=>R.blendFuncSeparate(a,b,c,d),ga:(a,b,c,d)=>{R.bufferData(a,c?q.subarray(c,c+b):b,d)},fa:(a,b,c,d)=>{R.bufferSubData(a,b,q.subarray(d,d+c))},ea:a=>R.checkFramebufferStatus(a),da:a=>R.clear(a),ca:(a,b,c,d)=>R.clearColor(a,b,c,d),ba:a=>R.clearDepth(a),aa:a=>R.clearStencil(a),gb:(a,b)=>{R.fg.clipControlEXT(a,
b)},$:(a,b,c,d)=>{R.colorMask(!!a,!!b,!!c,!!d)},_:a=>{R.compileShader(T[a])},Z:(a,b,c,d,e,f,g,l)=>{R.compressedTexImage2D(a,b,c,d,e,f,q.subarray(l,l+g))},Y:(a,b,c,d,e,f,g,l,n)=>{R.compressedTexSubImage2D(a,b,c,d,e,f,g,q.subarray(n,n+l))},W:(a,b,c,d,e,f,g,l)=>R.copyTexImage2D(a,b,c,d,e,f,g,l),V:(a,b,c,d,e,f,g,l)=>R.copyTexSubImage2D(a,b,c,d,e,f,g,l),U:()=>{var a=bd(S),b=R.createProgram();b.name=a;b.Te=b.Re=b.Se=0;b.wf=1;S[a]=b;return a},T:a=>{var b=bd(T);T[b]=R.createShader(a);return b},S:a=>R.cullFace(a),
R:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Tc[d];e&&(R.deleteBuffer(e),e.name=0,Tc[d]=null)}},Q:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+4*c>>2],e=Uc[d];e&&(R.deleteFramebuffer(e),e.name=0,Uc[d]=null)}},P:a=>{if(a){var b=S[a];b?(R.deleteProgram(b),b.name=0,S[a]=null):W||=1281}},Ka:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=V[d];e&&(R.pe.deleteQueryEXT(e),V[d]=null)}},O:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Vc[d];e&&(R.deleteRenderbuffer(e),e.name=0,Vc[d]=null)}},N:a=>{if(a){var b=
T[a];b?(R.deleteShader(b),T[a]=null):W||=1281}},L:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Wc[d];e&&(R.deleteTexture(e),e.name=0,Wc[d]=null)}},za:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2];R.deleteVertexArray(Xc[d]);Xc[d]=null}},K:a=>R.depthFunc(a),J:a=>{R.depthMask(!!a)},I:(a,b)=>R.depthRange(a,b),H:(a,b)=>{R.detachShader(S[a],T[b])},G:a=>R.disable(a),F:a=>{R.disableVertexAttribArray(a)},E:(a,b,c)=>{R.drawArrays(a,b,c)},va:(a,b,c,d)=>{R.drawArraysInstanced(a,b,c,d)},wa:(a,b)=>{for(var c=
gd[a],d=0;d<a;d++)c[d]=r[b+4*d>>2];R.drawBuffers(c)},D:(a,b,c,d)=>{R.drawElements(a,b,c,d)},ua:(a,b,c,d,e)=>{R.drawElementsInstanced(a,b,c,d,e)},C:a=>R.enable(a),cd:a=>{R.enableVertexAttribArray(a)},Ha:a=>{R.pe.endQueryEXT(a)},bd:()=>R.finish(),ad:()=>R.flush(),$c:(a,b,c,d)=>{R.framebufferRenderbuffer(a,b,c,Vc[d])},_c:(a,b,c,d,e)=>{R.framebufferTexture2D(a,b,c,Wc[d],e)},Zc:a=>R.frontFace(a),Yc:(a,b)=>{cd(a,b,"createBuffer",Tc)},Wc:(a,b)=>{cd(a,b,"createFramebuffer",Uc)},La:(a,b)=>{for(var c=0;c<a;c++){var d=
R.pe.createQueryEXT();if(!d){for(W||=1282;c<a;)r[b+4*c++>>2]=0;break}var e=bd(V);d.name=e;V[e]=d;r[b+4*c>>2]=e}},Vc:(a,b)=>{cd(a,b,"createRenderbuffer",Vc)},Uc:(a,b)=>{cd(a,b,"createTexture",Wc)},ya:(a,b)=>{cd(a,b,"createVertexArray",Xc)},Xc:a=>R.generateMipmap(a),Tc:(a,b,c,d,e,f,g)=>hd("getActiveAttrib",a,b,c,d,e,f,g),Sc:(a,b,c,d,e,f,g)=>hd("getActiveUniform",a,b,c,d,e,f,g),Rc:(a,b,c,d)=>{a=R.getAttachedShaders(S[a]);var e=a.length;e>b&&(e=b);r[c>>2]=e;for(b=0;b<e;++b)r[d+4*b>>2]=T.indexOf(a[b])},
Qc:(a,b)=>R.getAttribLocation(S[a],b?D(q,b):""),Pc:(a,b)=>jd(a,b,4),Oc:(a,b,c)=>{c?r[c>>2]=R.getBufferParameter(a,b):W||=1281},Nc:()=>{var a=R.getError()||W;W=0;return a},Mc:(a,b)=>jd(a,b,2),Lc:(a,b,c,d)=>{a=R.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r[d>>2]=a},Jc:(a,b)=>jd(a,b,0),Hc:(a,b,c,d)=>{a=R.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,q,d,b):0;c&&(r[c>>2]=b)},Ic:(a,b,c)=>{if(c)if(a>=Sc)W||=1281;
else if(a=S[a],35716==b)a=R.getProgramInfoLog(a),null===a&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(35719==b){if(!a.Te){var d=R.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Te=Math.max(a.Te,R.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.Te}else if(35722==b){if(!a.Re)for(d=R.getProgramParameter(a,35721),b=0;b<d;++b)a.Re=Math.max(a.Re,R.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.Re}else if(35381==b){if(!a.Se)for(d=R.getProgramParameter(a,35382),b=0;b<d;++b)a.Se=Math.max(a.Se,R.getActiveUniformBlockName(a,
b).length+1);r[c>>2]=a.Se}else r[c>>2]=R.getProgramParameter(a,b);else W||=1281},Ca:kd,Ea:ld,Ba:kd,Da:ld,Fa:(a,b,c)=>{c?r[c>>2]=R.pe.getQueryEXT(a,b):W||=1281},Gc:(a,b,c)=>{c?r[c>>2]=R.getRenderbufferParameter(a,b):W||=1281},Ec:(a,b,c,d)=>{a=R.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,q,d,b):0;c&&(r[c>>2]=b)},Dc:(a,b,c,d)=>{a=R.getShaderPrecisionFormat(a,b);r[c>>2]=a.rangeMin;r[c+4>>2]=a.rangeMax;r[d>>2]=a.precision},Cc:(a,b,c,d)=>{if(a=R.getShaderSource(T[a]))b=0<b&&d?E(a,
q,d,b):0,c&&(r[c>>2]=b)},Fc:(a,b,c)=>{c?35716==b?(a=R.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?(a=R.getShaderSource(T[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=R.getShaderParameter(T[a],b):W||=1281},Bc:a=>{var b=Zc[a];if(!b){switch(a){case 7939:b=md(nd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=R.getParameter(a))||(W||=1280);b=b?md(b):0;break;case 7938:b=md(`OpenGL ES 2.0 (${R.getParameter(7938)})`);break;case 35724:b=R.getParameter(35724);
var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=md(b);break;default:W||=1280}Zc[a]=b}return b},Ac:(a,b,c)=>{c?u[c>>2]=R.getTexParameter(a,b):W||=1281},zc:(a,b,c)=>{c?r[c>>2]=R.getTexParameter(a,b):W||=1281},wc:(a,b)=>{b=b?D(q,b):"";if(a=S[a]){pd(a);var c=a.Me,d=0,e=b,f=od(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Pf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||R.getUniformLocation(a,b)))return d}else W||=
1281;return-1},yc:(a,b,c)=>{qd(a,b,c,2)},xc:(a,b,c)=>{qd(a,b,c,0)},tc:(a,b,c)=>{c?r[c>>2]=R.getVertexAttribOffset(a,b):W||=1281},vc:(a,b,c)=>{rd(a,b,c,2)},uc:(a,b,c)=>{rd(a,b,c,5)},sc:(a,b)=>R.hint(a,b),rc:a=>(a=Tc[a])?R.isBuffer(a):0,qc:a=>R.isEnabled(a),oc:a=>(a=Uc[a])?R.isFramebuffer(a):0,nc:a=>(a=S[a])?R.isProgram(a):0,Ja:a=>(a=V[a])?R.pe.isQueryEXT(a):0,mc:a=>(a=Vc[a])?R.isRenderbuffer(a):0,lc:a=>(a=T[a])?R.isShader(a):0,kc:a=>(a=Wc[a])?R.isTexture(a):0,xa:a=>(a=Xc[a])?R.isVertexArray(a):0,jc:a=>
R.lineWidth(a),ic:a=>{a=S[a];R.linkProgram(a);a.Me=0;a.Pf={}},hc:(a,b)=>{3317==a?$c=b:3314==a&&(ad=b);R.pixelStorei(a,b)},fb:(a,b)=>{R.Ag.polygonModeWEBGL(a,b)},gc:(a,b)=>R.polygonOffset(a,b),ib:(a,b,c)=>{R.gg.polygonOffsetClampEXT(a,b,c)},Ga:(a,b)=>{R.pe.queryCounterEXT(V[a],b)},fc:(a,b,c,d,e,f,g)=>{(g=sd(f,e,c,d,g))?R.readPixels(a,b,c,d,e,f,g):W||=1280},ec:()=>{},dc:(a,b,c,d)=>R.renderbufferStorage(a,b,c,d),cc:(a,b)=>{R.sampleCoverage(a,!!b)},bc:(a,b,c,d)=>R.scissor(a,b,c,d),ac:()=>{W||=1280},$b:(a,
b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=t[c+4*f>>2])?D(q,g,d?t[d+4*f>>2]:void 0):"";e+=g}R.shaderSource(T[a],e)},_b:(a,b,c)=>R.stencilFunc(a,b,c),Zb:(a,b,c,d)=>R.stencilFuncSeparate(a,b,c,d),Yb:a=>R.stencilMask(a),Xb:(a,b)=>R.stencilMaskSeparate(a,b),Vb:(a,b,c)=>R.stencilOp(a,b,c),Ub:(a,b,c,d)=>R.stencilOpSeparate(a,b,c,d),Tb:(a,b,c,d,e,f,g,l,n)=>{n=n?sd(l,g,d,e,n):null;R.texImage2D(a,b,c,d,e,f,g,l,n)},Sb:(a,b,c)=>R.texParameterf(a,b,c),Rb:(a,b,c)=>{R.texParameterf(a,b,u[c>>2])},Qb:(a,b,c)=>R.texParameteri(a,
b,c),Pb:(a,b,c)=>{R.texParameteri(a,b,r[c>>2])},Ob:(a,b,c,d,e,f,g,l,n)=>{n=n?sd(l,g,e,f,n):null;R.texSubImage2D(a,b,c,d,e,f,g,l,n)},Nb:(a,b)=>{R.uniform1f(Y(a),b)},Mb:(a,b,c)=>{if(288>=b)for(var d=td[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);R.uniform1fv(Y(a),d)},Lb:(a,b)=>{R.uniform1i(Y(a),b)},Kb:(a,b,c)=>{if(288>=b)for(var d=ud[b],e=0;e<b;++e)d[e]=r[c+4*e>>2];else d=r.subarray(c>>2,c+4*b>>2);R.uniform1iv(Y(a),d)},Jb:(a,b,c)=>{R.uniform2f(Y(a),b,c)},Ib:(a,b,c)=>{if(144>=b){b*=
2;for(var d=td[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);R.uniform2fv(Y(a),d)},Hb:(a,b,c)=>{R.uniform2i(Y(a),b,c)},Gb:(a,b,c)=>{if(144>=b){b*=2;for(var d=ud[b],e=0;e<b;e+=2)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2]}else d=r.subarray(c>>2,c+8*b>>2);R.uniform2iv(Y(a),d)},Fb:(a,b,c,d)=>{R.uniform3f(Y(a),b,c,d)},Eb:(a,b,c)=>{if(96>=b){b*=3;for(var d=td[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*
b>>2);R.uniform3fv(Y(a),d)},Db:(a,b,c,d)=>{R.uniform3i(Y(a),b,c,d)},Cb:(a,b,c)=>{if(96>=b){b*=3;for(var d=ud[b],e=0;e<b;e+=3)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2]}else d=r.subarray(c>>2,c+12*b>>2);R.uniform3iv(Y(a),d)},Bb:(a,b,c,d,e)=>{R.uniform4f(Y(a),b,c,d,e)},Ab:(a,b,c)=>{if(72>=b){var d=td[4*b],e=u;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=u.subarray(c>>2,c+16*b>>2);R.uniform4fv(Y(a),d)},zb:(a,b,c,d,e)=>{R.uniform4i(Y(a),
b,c,d,e)},yb:(a,b,c)=>{if(72>=b){b*=4;for(var d=ud[b],e=0;e<b;e+=4)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2],d[e+3]=r[c+(4*e+12)>>2]}else d=r.subarray(c>>2,c+16*b>>2);R.uniform4iv(Y(a),d)},xb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=td[b],f=0;f<b;f+=4)e[f]=u[d+4*f>>2],e[f+1]=u[d+(4*f+4)>>2],e[f+2]=u[d+(4*f+8)>>2],e[f+3]=u[d+(4*f+12)>>2]}else e=u.subarray(d>>2,d+16*b>>2);R.uniformMatrix2fv(Y(a),!!c,e)},wb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=td[b],f=0;f<b;f+=9)e[f]=u[d+4*f>>2],e[f+
1]=u[d+(4*f+4)>>2],e[f+2]=u[d+(4*f+8)>>2],e[f+3]=u[d+(4*f+12)>>2],e[f+4]=u[d+(4*f+16)>>2],e[f+5]=u[d+(4*f+20)>>2],e[f+6]=u[d+(4*f+24)>>2],e[f+7]=u[d+(4*f+28)>>2],e[f+8]=u[d+(4*f+32)>>2]}else e=u.subarray(d>>2,d+36*b>>2);R.uniformMatrix3fv(Y(a),!!c,e)},vb:(a,b,c,d)=>{if(18>=b){var e=td[16*b],f=u;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=
f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=u.subarray(d>>2,d+64*b>>2);R.uniformMatrix4fv(Y(a),!!c,e)},ub:a=>{a=S[a];R.useProgram(a);R.Zf=a},tb:a=>{R.validateProgram(S[a])},sb:(a,b)=>R.vertexAttrib1f(a,b),rb:(a,b)=>{R.vertexAttrib1f(a,u[b>>2])},qb:(a,b,c)=>R.vertexAttrib2f(a,b,c),pb:(a,b)=>{R.vertexAttrib2f(a,u[b>>2],u[b+4>>2])},ob:(a,b,c,d)=>R.vertexAttrib3f(a,b,c,d),nb:(a,b)=>{R.vertexAttrib3f(a,u[b>>2],u[b+4>>2],u[b+8>>2])},mb:(a,b,c,d,e)=>R.vertexAttrib4f(a,
b,c,d,e),lb:(a,b)=>{R.vertexAttrib4f(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},ta:(a,b)=>{R.vertexAttribDivisor(a,b)},kb:(a,b,c,d,e,f)=>{R.vertexAttribPointer(a,b,c,!!d,e,f)},jb:(a,b,c,d)=>R.viewport(a,b,c,d),i:()=>0,Na:(a,b,c)=>vd(a,{sf:r[c>>2],Ze:r[c+4>>2],hg:r[c+8>>2],bg:b,Ne:r[c+12>>2],Df:r[c+16>>2]}),z:(a,b)=>{a=Q(a);return a?a.requestPointerLock?oc()?Fc(a):b?(mc(Fc,2,[a]),1):-2:-1:-4},Va:a=>{var b=q.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,
a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},k:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:wd(a,b),w:(a,b,c,d)=>xd(a,b,c,d,12,"blur"),c:xc,e:(a,b,c)=>{a=Q(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},x:(a,b,c,d)=>xd(a,b,c,d,13,"focus"),s:(a,b,c,d)=>{if(!O.fullscreenEnabled())return-1;a=Q(a);if(!a)return-4;yd(a,b,c,
d,"webkitfullscreenchange");return yd(a,b,c,d,"fullscreenchange")},o:(a,b,c,d)=>zd(a,b,c,d,2,"keydown"),m:(a,b,c,d)=>zd(a,b,c,d,1,"keypress"),n:(a,b,c,d)=>zd(a,b,c,d,3,"keyup"),Qa:(a,b,c,d)=>{ic(()=>z(a)(b),c,d,b)},g:$b,p:(a,b,c)=>window.screen&&screen.orientation?Ad(a,b,c):-1,t:(a,b,c,d)=>document.body?.requestPointerLock?(a=Q(a))?Bd(a,b,c,d):-4:-1,r:(a,b,c,d)=>Cd(a,b,c,d),l:(a,b,c)=>Dd(a,b,c),q:(a,b,c,d)=>(a=Q(a))?"undefined"!=typeof a.onwheel?Ed(a,b,c,d):-1:-4,Pa:a=>document.title=a?D(q,a):"",
h:()=>{Da("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},M:(a,b)=>{var c=b>>2;b={alpha:!!m[b+0],depth:!!m[b+1],stencil:!!m[b+2],antialias:!!m[b+3],premultipliedAlpha:!!m[b+4],preserveDrawingBuffer:!!m[b+5],powerPreference:Fd[r[c+2]],failIfMajorPerformanceCaveat:!!m[b+12],qg:r[c+4],Sg:r[c+5],Ff:m[b+24],eg:m[b+25],Wg:r[c+7],Zg:m[b+32]};a=Q(a);return!a||b.eg?0:ed(a,b)},A:a=>{fd==a&&(fd=0);fd===Yc[a]&&(fd=null);"object"==typeof O&&O.wg(Yc[a].ye.canvas);
Yc[a]?.ye.canvas&&(Yc[a].ye.canvas.Ce=void 0);Yc[a]=null},B:a=>{fd=Yc[a];h.ctx=R=fd?.ye;return!a||R?0:-5},db:(a,b)=>{var c=0,d=0,e;for(e of Id()){var f=b+c;t[a+d>>2]=f;c+=E(e,q,f,Infinity)+1;d+=4}return 0},eb:(a,b)=>{var c=Id();t[a>>2]=c.length;a=0;for(var d of c)a+=ab(d)+1;t[b>>2]=a;return 0},v:function(a){try{var b=J(a);Ca(b);return 0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return c.ee}},Za:function(a,b,c,d){try{a:{var e=J(a);a=b;for(var f,g=b=0;g<c;g++){var l=t[a>>2],n=
t[a+4>>2];a+=8;var p=e,A=l,x=n,C=f,ba=m;if(0>x||0>C)throw new F(28);if(null===p.ve)throw new F(8);if(1===(p.flags&2097155))throw new F(8);if(H(p.node.mode))throw new F(31);if(!p.Sd.read)throw new F(28);var ia="undefined"!=typeof C;if(!ia)C=p.position;else if(!p.seekable)throw new F(70);var ja=p.Sd.read(p,ba,A,x,C);ia||(p.position+=ja);var U=ja;if(0>U){var Ea=-1;break a}b+=U;if(U<n)break;"undefined"!=typeof f&&(f+=U)}Ea=b}t[d>>2]=Ea;return 0}catch(Fa){if("undefined"==typeof M||"ErrnoError"!==Fa.name)throw Fa;
return Fa.ee}},Wa:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=J(a);Gb(e,b,c);w[d>>3]=BigInt(e.position);e.jf&&0===b&&0===c&&(e.jf=null);return 0}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return f.ee}},Ya:function(a,b,c,d){try{a:{var e=J(a);a=b;for(var f,g=b=0;g<c;g++){var l=t[a>>2],n=t[a+4>>2];a+=8;var p=Hb(e,m,l,n,f);if(0>p){var A=-1;break a}b+=p;if(p<n)break;"undefined"!=typeof f&&(f+=p)}A=b}t[d>>2]=A;return 0}catch(x){if("undefined"==
typeof M||"ErrnoError"!==x.name)throw x;return x.ee}},Sa:Kb};function ge(a=[]){var b=de;a.unshift(ca);var c=a.length,d=sc(4*(c+1)),e=d,f;for(f of a)t[e>>2]=tc(f),e+=4;t[e>>2]=0;try{var g=b(c,d);ma=g;y||0<N||va();Kb(g)}catch(l){Jb(l)}}var he;
he=await (async function(){function a(c){c=he=c.exports;h._upload_rom=c.gd;h._set_button_state=c.hd;h._set_channel_muted=c.id;h._is_channel_muted=c.jd;h._set_master_volume=c.kd;h._get_master_volume=c.ld;h._get_frame_count=c.md;h._get_cart_ram_ptr=c.nd;h._get_cart_ram_size=c.od;h._import_save=c.pd;h._shutdown_emulator=c.qd;de=h._main=c.rd;Vd=h._SDL_free=c.sd;Sd=h._SDL_malloc=c.td;h._SDL_calloc=c.ud;ae=h._Emscripten_force_free=c.vd;h._free=c.wd;h._SDL_realloc=c.xd;Aa=c.yd;X=h._malloc=c.zd;
Wd=h._Emscripten_HandlePointerEnter=c.Ad;Xd=h._Emscripten_HandlePointerLeave=c.Bd;Yd=h._Emscripten_HandlePointerGeneric=c.Cd;Ud=h._Emscripten_HandleMouseButtonUpGlobal=c.Dd;Zd=h._Emscripten_SendDragEvent=c.Ed;ce=h._Emscripten_SendDragCompleteEvent=c.Fd;$d=h._Emscripten_SendDragTextEvent=c.Gd;be=h._Emscripten_SendDragFileEvent=c.Hd;Td=h._Emscripten_HandleLockKeysCheck=c.Id;Rd=h._Emscripten_SendSystemThemeChangedEvent=c.Jd;Qd=h._requestFullscreenThroughSDL=c.Kd;wa=c.Md;ee=c.Nd;vc=c.Od;sc=c.Pd;uc=c.Qd;
sa=c.ed;Qa=c.Ld;ra();return he}var b={a:fe};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});Ga??=h.locateFile?h.locateFile?h.locateFile("GBC.wasm",ea):ea+"GBC.wasm":(new URL("GBC.wasm",import.meta.url)).href;return a((await Ja(b)).instance)}());
(function(a=aa){function b(){h.calledRun=!0;if(!la){pa=!0;if(!h.noFSInit&&!za){var c,d;za=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?L("stdin",c):Eb("/dev/tty","/dev/stdin");d?L("stdout",null,d):Eb("/dev/tty","/dev/stdout");e?L("stderr",null,e):Eb("/dev/tty1","/dev/stderr");Fb("/dev/stdin",0);Fb("/dev/stdout",1);Fb("/dev/stderr",1)}he.fd();qb=!1;na?.(h);h.onRuntimeInitialized?.();h.noInitialRun||ge(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();La.push(e)}xa(La)}}if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Na();xa(Ma);h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()})();pa?moduleRtn=h:moduleRtn=new Promise((a,b)=>{na=a;oa=b});
;return moduleRtn}export default createGBCModule;
