async function createGBCModule(moduleArg={}){var moduleRtn;var h=moduleArg,aa=[],ba="./this.program",ca=import.meta.url,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),k=console.error.bind(console),ha,ia=!1,ja,ka,la,ma=!1,na=!1;
function oa(){var a=pa.buffer;h.HEAP8=m=new Int8Array(a);qa=new Int16Array(a);h.HEAPU8=q=new Uint8Array(a);ra=new Uint16Array(a);r=new Int32Array(a);t=new Uint32Array(a);u=new Float32Array(a);w=new Float64Array(a);sa=new BigInt64Array(a);new BigUint64Array(a)}function ta(){ua();va(wa);xa=!1;ya(0);for(var a of za)a&&Aa(a);na=!0}function y(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);ia=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");la?.(a);throw a;}var Ba;
async function Ca(a){if(!ha)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==Ba&&ha)a=new Uint8Array(ha);else throw"both async and sync fetching of the wasm failed";return a}async function Da(a,b){try{var c=await Ca(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),y(d)}}
async function Ea(a){var b=Ba;if(!ha)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return Da(b,a)}class Fa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var qa,r,sa,m,u,w,ra,t,q,va=a=>{for(;0<a.length;)a.shift()(h)},Ga=[],Ha=[],Ia=()=>{var a=h.preRun.shift();Ha.push(a)},Ja=!1;
function Ka(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":m[a]=b;break;case "i8":m[a]=b;break;case "i16":qa[a>>1]=b;break;case "i32":r[a>>2]=b;break;case "i64":sa[a>>3]=BigInt(b);break;case "float":u[a>>2]=b;break;case "double":w[a>>3]=b;break;case "*":t[a>>2]=b;break;default:y(`invalid type for setValue: ${c}`)}}
var La=[],z=a=>{var b=La[a];b||(La[a]=b=Ma.get(a));return b},A=0,Na={},Oa=a=>{if(!(a instanceof Fa||"unwind"==a))throw a;},Pa=a=>{ja=a;Ja||0<A||(h.onExit?.(a),ia=!0);throw new Fa(a);},Qa=()=>{if(!(na||Ja||0<A))try{var a=ja;ja=a;Ja||0<A||ta();Pa(a)}catch(b){Oa(b)}},Ra=a=>{if(!na&&!ia)try{a()}catch(b){Oa(b)}finally{Qa()}},Sa=[],Ta=(a,b)=>{Sa.length=0;for(var c;c=q[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Sa.push(112==c?t[b>>2]:106==c?sa[b>>3]:105==c?r[b>>2]:w[b>>3]);b+=d?8:4}return Sa},Va=(a,b,c)=>
{b=Ta(b,c);return Ua[a](...b)},eb=(a,b)=>{Wa=a;Xa=b;if(!Ya)return 1;Za||(A+=1,Za=!0);if(0==a)$a=function(){setTimeout(ab,Math.max(0,bb+b-performance.now())|0)};else if(1==a)$a=function(){cb(ab)};else{if(!db)if(globalThis.setImmediate)db=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);db=d=>{c.push(d);postMessage("setimmediate","*")}}$a=function(){db(ab)}}return 0},nb=(a,b,c,d,e)=>{function f(){return g<
fb?(--A,Qa(),!1):!0}Ya=a;gb=d;var g=fb;Za=!1;ab=function(){if(!ia)if(0<hb.length){var l=hb.shift();l.Dg(l.og);if(ib){var n=ib,p=0==n%1?n-1:Math.floor(n);ib=l.xg?p:(8*n+(p+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=ib??0,p=jb.Cg??0,n?n<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(ab,0)}else if(f())if(kb=kb+1|0,1==Wa&&1<Xa&&0!=kb%Xa)$a();else{0==Wa&&(bb=performance.now());a:if(!ia){for(l of lb)if(!1===l())break a;Ra(a);
for(n of mb)n()}f()&&$a()}};e||(0<b?eb(0,1E3/b):eb(1,1),$a());if(c)throw"unwind";},Za=!1,$a=null,fb=0,Ya=null,gb=0,Wa=0,Xa=0,kb=0,hb=[],lb=[],mb=[];function ob(){$a=null;fb++}var pb=0;function cb(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===pb)pb=b+1E3/60;else for(;b+2>=pb;)pb+=1E3/60;setTimeout(a,Math.max(pb-b,0))}}var jb={},bb,ab,db,ib,wa=[];function qb(a){var b=C.Ud[a];b.target.removeEventListener(b.Vd,b.Af,b.fe);C.Ud.splice(a,1)}
function rb(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of C.le)if(e.qf==a&&d(e.wf,c))return;C.le.push({qf:a,Ff:b,wf:c});C.le.sort((f,g)=>f.Ff-g.Ff)}function sb(a){C.le=C.le.filter(b=>b.qf!=a)}function tb(){return navigator.userActivation?navigator.userActivation.isActive:C.ff&&C.Qf.Nf}function ub(){if(tb()){var a=C.le;C.le=[];for(var b of a)b.qf(...b.wf)}}
function E(a){if(!a.target)return-4;if(a.Yd)a.Af=function(c){++C.ff;C.Qf=a;ub();a.je(c);ub();--C.ff},a.target.addEventListener(a.Vd,a.Af,a.fe),C.Ud.push(a),C.jg||(wa.push(C.hg),C.jg=!0);else for(var b=0;b<C.Ud.length;++b)C.Ud[b].target==a.target&&C.Ud[b].Vd==a.Vd&&qb(b--);return 0}function vb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var C={pg:0,Eg:0,gf:0,Lg:0,vf:0,sf:0,af:0,Ag:0,kf:0,zg:0,df:0,lf:0,uf:0,Vg:0,hg(){for(;C.Ud.length;)qb(C.Ud.length-1);C.le=[]},ff:0,le:[],Ud:[],ig:(a,b)=>{for(var c=0;c<C.Ud.length;++c)C.Ud[c].target!=a||b&&b!=C.Ud[c].Vd||qb(c--)},Rg(a){let b=!1;for(let c=0;c<C.Ud.length;++c){const d=C.Ud[c];d.target===a.target&&d.be===a.be&&d.Yd===a.Yd&&d.ge===a.ge&&(qb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},wb=[0,document,window],xb=globalThis.TextDecoder&&
new TextDecoder,F=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&xb)return xb.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},H=a=>{a=2<a?a?F(q,a):"":a;return wb[a]||document.querySelector(a)},
yb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},J=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|
g&63;f++}}b[c]=0;return c-e},Bb=a=>{var b=yb(a)+1,c=zb(b);J(a,q,c,b);return c},Eb=a=>{var b=Cb(),c=zb(8),d=c+4;a=Bb(a.id);if(a=H(a))r[c>>2]=a.width,r[d>>2]=a.height;c=[r[c>>2],r[d>>2]];Db(b);return c},Fb=(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},Gb=(a,b,c)=>{if(a.wg){var d=Cb();a=Bb(a.id);Fb(a,b,c);Db(d)}else a.width=b,a.height=c},Hb={},Jb=a=>{function b(){Ib()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Gb(a,d,
e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=v,a.style.paddingTop=x,a.style.paddingBottom=B,a.style.marginLeft=G,a.style.marginRight=D,a.style.marginTop=R,a.style.marginBottom=T,document.body.style.margin=W,document.documentElement.style.overflow=Ab,document.body.scroll=I,a.style.ne=Kd,a.xe&&a.xe.oe.viewport(0,0,d,e),Hb.Ie&&z(Hb.Ie)(37,0,Hb.xf))}var c=
Eb(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,v=a.style.paddingRight,x=a.style.paddingTop,B=a.style.paddingBottom,G=a.style.marginLeft,D=a.style.marginRight,R=a.style.marginTop,T=a.style.marginBottom,W=document.body.style.margin,Ab=document.documentElement.style.overflow,I=document.body.scroll,Kd=a.style.ne;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},Kb=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Lb=a=>0>wb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Mb=(a,b)=>{if(0!=b.pf||0!=b.Ve){Jb(a);var c=b.kg?innerWidth:screen.width,d=b.kg?innerHeight:screen.height,e=Lb(a),f=e.width;e=e.height;var g=Eb(a),l=g[0];g=g[1];3==b.pf?(Kb(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.pf&&(c*g<l*d?(f=g*c/l,Kb(a,(d-f)/2,0),d=f):(f=l*d/g,Kb(a,0,(c-f)/2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let p;(p=document.body.style).backgroundColor||(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Zf&&(a.style.ne="optimizeSpeed",a.style.ne="-moz-crisp-edges",a.style.ne="-o-crisp-edges",a.style.ne="-webkit-optimize-contrast",a.style.ne="optimize-contrast",a.style.ne="crisp-edges",a.style.ne="pixelated");n=2==b.Ve?devicePixelRatio:1;0!=b.Ve&&(c=c*n|0,d=d*n|0,Gb(a,c,d),a.xe&&a.xe.oe.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return C.fullscreenEnabled()?-3:-1;Hb=b;b.Ie&&z(b.Ie)(37,0,b.xf);return 0},Nb=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0};function Ib(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var Ob=a=>{var b=Ib(),c=!!b;m[a]=c;m[a+1]=C.fullscreenEnabled();var d=c?b:C.gg,e=d?.id||"";J(vb(d),q,a+2,128);J(e,q,a+130,128);r[a+260>>2]=d?d.clientWidth:0;r[a+264>>2]=d?d.clientHeight:0;r[a+268>>2]=screen.width;r[a+272>>2]=screen.height;c&&(C.gg=b)},Pb=a=>{A+=1;setTimeout(()=>{--A;Ra(a)},1E4)},Qb=[],Rb=!1,Sb=[];
function Tb(){function a(){Rb=document.pointerLockElement===h.canvas}if(!Ub){Ub=!0;Qb.push({canHandle:c=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:Vb(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Vb(d)}));var f=URL.createObjectURL(e);return new Promise((g,l)=>{var n=new Image;n.onload=()=>{var p=document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(f);
g(c)};n.onerror=()=>{k(`Image ${f} could not be decoded`);l()};n.src=f})}});Qb.push({canHandle:c=>!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,l=URL.createObjectURL(new Blob([c],{type:Vb(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=()=>{if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var p="",v=0,x=0,B=0;B<c.length;B++)for(v=v<<
8|c[B],x+=8;6<=x;){var G=v>>x-6&63;x-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[G]}2==x?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&3)<<4],p+="=="):4==x&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&15)<<2],p+="=");n.src="data:audio/x-"+d.slice(-3)+";base64,"+p;f(n)}};n.src=l;Pb(()=>{f(n)})})});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Rb&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Wb(a){a=a.getContext("2d");if(!a)return null;h.ctx=a;Sb.forEach(b=>b());Tb();return a}function Vb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var Xb={},Ub,K,Yb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Zb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>
b.isVertexArrayOES(c))},$b=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},ac=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},bc=1,cc=[],L=[],dc=[],ec=[],fc=[],M=[],gc=[],hc=[],N=[],ic={},jc=4,kc=0,lc=a=>{for(var b=bc++,c=a.length;c<b;c++)a[c]=null;return b},mc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=K[c](),g=f&&lc(d);f?(f.name=g,d[g]=f):O||=1282;r[b+4*e>>2]=g}},oc=(a,b)=>{a.Ae||(a.Ae=a.getContext,a.getContext=function(d,e){e=a.Ae(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?nc(c,b):0},nc=(a,b)=>{var c=
lc(hc),d={handle:c,attributes:b,version:b.dg,oe:a};a.canvas&&(a.canvas.xe=d);hc[c]=d;if("undefined"==typeof b.zf||b.zf)if((a=d)||(a=pc),!a.ag){a.ag=!0;a=a.oe;a.Mg=a.getExtension("WEBGL_multi_draw");a.Yf=a.getExtension("EXT_polygon_offset_clamp");a.Xf=a.getExtension("EXT_clip_control");a.mg=a.getExtension("WEBGL_polygon_mode");Yb(a);Zb(a);$b(a);a.ie=a.getExtension("EXT_disjoint_timer_query");for(var e of ac(a))e.includes("lose_context")||e.includes("debug")||a.getExtension(e)}return c},O,pc,qc=[],
rc=(a,b,c,d,e,f,g,l)=>{b=L[b];if(a=K[a](b,c))d=l&&J(a.name,q,l,d),e&&(r[e>>2]=d),f&&(r[f>>2]=a.size),g&&(r[g>>2]=a.type)},sc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(O||=1280);return;case 36345:d=0;break;case 34466:var e=K.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":O||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=
0;break;default:O||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+4*a>>2]=e[a];break;case 2:u[b+4*a>>2]=e[a];break;case 4:m[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){O||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:O||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;t[b>>2]=c;t[b+4>>2]=(c-t[b>>2])/4294967296;break;case 0:r[b>>2]=d;break;case 2:u[b>>2]=d;break;case 4:m[b]=d?1:0}}else O||=1281},tc=(a,b,c)=>{if(c){a=K.ie.getQueryObjectEXT(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d;t[c+4>>2]=(d-t[c>>2])/4294967296}else O||=1281},uc=(a,b,c)=>{if(c){a=K.ie.getQueryObjectEXT(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;r[c>>2]=d}else O||=1281},vc=a=>{var b=yb(a)+1,c=P(b);c&&J(a,q,c,b);return c},wc=()=>{var a=ac(K);return a=
a.concat(a.map(b=>"GL_"+b))},xc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),yc=a=>{var b=a.He,c=a.If,d;if(!b){a.He=b={};a.Hf={};var e=K.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=K.getActiveUniform(a,d);var g=f.name;f=f.size;var l=xc(g);l=0<l?g.slice(0,l):g;var n=a.tf;a.tf+=f;c[l]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Hf[n++]=l}}},Q=a=>{var b=K.Rf;if(b){var c=b.He[a];"number"==typeof c&&(b.He[a]=c=K.getUniformLocation(b,b.Hf[a]+(0<c?`[${c}]`:"")));return c}O||=1282},zc=(a,b,c,d)=>{if(c)if(a=L[a],yc(a),
a=K.getUniform(a,Q(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:u[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:u[c+4*b>>2]=a[b]}else O||=1281},Ac=(a,b,c,d)=>{if(c)if(a=K.getVertexAttrib(a,b),34975==b)r[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:u[c>>2]=a;break;case 5:r[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:u[c+
4*b>>2]=a[b];break;case 5:r[c+4*b>>2]=Math.fround(a[b])}else O||=1281},Bc=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?r:6==a?u:5==a||28922==a?t:ra;b=d*((kc||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+jc-1&-jc);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Cc=[],Dc=[],Ec=(a,b)=>{if(!C.fullscreenEnabled())return-1;a=H(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?tb()?Mb(a,b):b.Uf?(rb(Mb,1,[a,b]),1):-2:-3:-4},Fc=(a,b)=>
{var c={target:H(2),Vd:"beforeunload",be:28,ge:a,Yd:b,je:d=>{var e=z(b)(28,0,a);e&&=e?F(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},fe:!0};return E(c)},Gc=(a,b,c,d,e,f)=>{C.af||(C.af=P(256));a={target:H(a),Vd:f,be:e,ge:b,Yd:d,je:g=>{var l=g.target.id?g.target.id:"",n=C.af;J(vb(g.target),q,n+0,128);J(l,q,n+128,128);z(d)(e,n,b)&&g.preventDefault()},fe:c};return E(a)},Hc=(a,b,c,d,e)=>{C.df||(C.df=P(276));return E({target:a,Vd:e,be:19,ge:b,Yd:d,je:f=>{var g=C.df;Ob(g);z(d)(19,g,b)&&f.preventDefault()},
fe:c})},Ic=(a,b,c,d,e,f)=>{C.gf||(C.gf=P(160));a={target:H(a),Vd:f,be:e,ge:b,Yd:d,je:g=>{var l=C.gf;w[l>>3]=g.timeStamp;var n=l>>2;r[n+2]=g.location;m[l+12]=g.ctrlKey;m[l+13]=g.shiftKey;m[l+14]=g.altKey;m[l+15]=g.metaKey;m[l+16]=g.repeat;r[n+5]=g.charCode;r[n+6]=g.keyCode;r[n+7]=g.which;J(g.key||"",q,l+32,32);J(g.code||"",q,l+64,32);J(g.char||"",q,l+96,32);J(g.locale||"",q,l+128,32);z(d)(e,l,b)&&g.preventDefault()},fe:c};return E(a)},Jc=(a,b,c)=>{var d=screen.orientation;C.kf||(C.kf=P(8));return E({target:d,
Vd:"change",be:18,ge:a,Yd:c,je:e=>{var f=C.kf,g=["portrait-primary","portrait-secondary","landscape-primary","landscape-secondary"],l=["portrait","portrait","landscape","landscape"],n=0;var p=window.screen?screen.orientation||screen.mozOrientation||screen.webkitOrientation:void 0;"object"===typeof p?(n=g.indexOf(p.type),0>n&&(n=l.indexOf(p.type)),0<=n&&(n=1<<n),g=p.angle):g=window.orientation;r[f>>2]=n;r[f+4>>2]=g;z(c)(18,f,a)&&e.preventDefault()},fe:b})},Kc=(a,b,c,d)=>{C.lf||(C.lf=P(257));return E({target:a,
Vd:"pointerlockchange",be:20,ge:b,Yd:d,je:e=>{var f=C.lf,g=document.pointerLockElement;m[f]=!!g;var l=g?.id||"";J(vb(g),q,f+1,128);J(l,q,f+129,128);z(d)(20,f,b)&&e.preventDefault()},fe:c})},Lc=(a,b,c,d)=>{C.sf||(C.sf=P(36));a=H(a);return E({target:a,Vd:"resize",be:10,ge:b,Yd:d,je:e=>{if(e.target==a){var f=document.body;if(f){var g=C.sf;r[g>>2]=0;r[g+4>>2]=f.clientWidth;r[g+8>>2]=f.clientHeight;r[g+12>>2]=innerWidth;r[g+16>>2]=innerHeight;r[g+20>>2]=outerWidth;r[g+24>>2]=outerHeight;r[g+28>>2]=pageXOffset|
0;r[g+32>>2]=pageYOffset|0;z(d)(10,g,b)&&e.preventDefault()}}},fe:c})},Mc=(a,b,c)=>{var d=wb[1];C.uf||(C.uf=P(8));return E({target:d,Vd:"visibilitychange",be:21,ge:a,Yd:c,je:e=>{var f=C.uf,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);m[f]=document.hidden;r[f+4>>2]=g;z(c)(21,f,a)&&e.preventDefault()},fe:b})},Nc=(a,b,c,d)=>{C.vf||(C.vf=P(96));return E({target:a,Nf:!0,Vd:"wheel",be:9,ge:b,Yd:d,je:e=>{var f=C.vf;w[f>>3]=e.timeStamp;var g=f>>2;r[g+2]=e.screenX;r[g+3]=
e.screenY;r[g+4]=e.clientX;r[g+5]=e.clientY;m[f+24]=e.ctrlKey;m[f+25]=e.shiftKey;m[f+26]=e.altKey;m[f+27]=e.metaKey;qa[2*g+14]=e.button;qa[2*g+15]=e.buttons;r[g+8]=e.movementX;r[g+9]=e.movementY;var l=Lb(a);r[g+10]=e.clientX-(l.left|0);r[g+11]=e.clientY-(l.top|0);w[f+64>>3]=e.deltaX;w[f+72>>3]=e.deltaY;w[f+80>>3]=e.deltaZ;r[f+88>>2]=e.deltaMode;z(d)(9,f,b)&&e.preventDefault()},fe:c})},Oc=["default","low-power","high-performance"],Pc={},Rc=()=>{if(!Qc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",
PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Pc)void 0===Pc[b]?delete a[b]:a[b]=Pc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Qc=c}return Qc},Qc,Sc=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Tc=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Sc(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Uc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Vc=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Wc=()=>a=>crypto.getRandomValues(a),Xc=a=>{(Xc=Wc())(a)},Yc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=
Sc(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Zc=[],$c=a=>{var b=Array(yb(a)+1);a=J(a,b,0,b.length);b.length=a;return b},ad=[];function bd(a,b){ad[a]={input:[],output:[],we:b};cd(a,dd)}
var dd={open(a){var b=ad[a.node.Qe];if(!b)throw new S(43);a.Xd=b;a.seekable=!1},close(a){a.Xd.we.Le(a.Xd)},Le(a){a.Xd.we.Le(a.Xd)},read(a,b,c,d){if(!a.Xd||!a.Xd.we.Bf)throw new S(60);for(var e=0,f=0;f<d;f++){try{var g=a.Xd.we.Bf(a.Xd)}catch(l){throw new S(29);}if(void 0===g&&0===e)throw new S(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.pe=Date.now());return e},write(a,b,c,d){if(!a.Xd||!a.Xd.we.mf)throw new S(60);try{for(var e=0;e<d;e++)a.Xd.we.mf(a.Xd,b[c+e])}catch(f){throw new S(29);
}d&&(a.node.Zd=a.node.Wd=Date.now());return e}},ed={Bf(){a:{if(!Zc.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Zc=$c(a)}a=Zc.shift()}return a},mf(a,b){null===b||10===b?(fa(F(a.output)),a.output=[]):0!=b&&a.output.push(b)},Le(a){0<a.output?.length&&(fa(F(a.output)),a.output=[])},Hg(){return{tg:25856,vg:5,sg:191,ug:35387,rg:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ig(){return 0},Jg(){return[24,
80]}},fd={mf(a,b){null===b||10===b?(k(F(a.output)),a.output=[]):0!=b&&a.output.push(b)},Le(a){0<a.output?.length&&(k(F(a.output)),a.output=[])}},U={de:null,ke(){return U.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);U.de||(U.de={dir:{node:{me:U.Ld.me,ee:U.Ld.ee,Ee:U.Ld.Ee,Pe:U.Ld.Pe,Gf:U.Ld.Gf,Te:U.Ld.Te,Re:U.Ld.Re,nf:U.Ld.nf,Se:U.Ld.Se},stream:{ce:U.Nd.ce}},file:{node:{me:U.Ld.me,ee:U.Ld.ee},stream:{ce:U.Nd.ce,read:U.Nd.read,write:U.Nd.write,
jf:U.Nd.jf,Ef:U.Nd.Ef}},link:{node:{me:U.Ld.me,ee:U.Ld.ee,Ge:U.Ld.Ge},stream:{}},yf:{node:{me:U.Ld.me,ee:U.Ld.ee},stream:gd}});c=hd(a,b,c,d);V(c.mode)?(c.Ld=U.de.dir.node,c.Nd=U.de.dir.stream,c.Od={}):32768===(c.mode&61440)?(c.Ld=U.de.file.node,c.Nd=U.de.file.stream,c.Td=0,c.Od=U.Vf??(U.Vf=new Uint8Array(0))):40960===(c.mode&61440)?(c.Ld=U.de.link.node,c.Nd=U.de.link.stream):8192===(c.mode&61440)&&(c.Ld=U.de.yf.node,c.Nd=U.de.yf.stream);c.pe=c.Zd=c.Wd=Date.now();a&&(a.Od[b]=c,a.pe=a.Zd=a.Wd=c.pe);
return c},Ld:{me(a){var b={};b.yg=8192===(a.mode&61440)?a.id:1;b.Gg=a.id;b.mode=a.mode;b.Ng=1;b.uid=0;b.Fg=0;b.Qe=a.Qe;V(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Td:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.pe=new Date(a.pe);b.Zd=new Date(a.Zd);b.Wd=new Date(a.Wd);b.Of=4096;b.qg=Math.ceil(b.size/b.Of);return b},ee(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Td!=b&&(c=a.Od,a.Od=new Uint8Array(b),a.Od.set(c.subarray(0,
Math.min(b,a.Td))),a.Td=b))},Ee(){U.Xe||(U.Xe=new S(44),U.Xe.stack="<generic error, no stack>");throw U.Xe;},Pe(a,b,c,d){return U.createNode(a,b,c,d)},Gf(a,b,c){try{var d=jd(b,c)}catch(f){}if(d){if(V(a.mode))for(var e in d.Od)throw new S(55);kd(d)}delete a.parent.Od[a.name];b.Od[c]=a;a.name=c;b.Wd=b.Zd=a.parent.Wd=a.parent.Zd=Date.now()},Te(a,b){delete a.Od[b];a.Wd=a.Zd=Date.now()},Re(a,b){var c=jd(a,b),d;for(d in c.Od)throw new S(55);delete a.Od[b];a.Wd=a.Zd=Date.now()},nf(a){return[".","..",...Object.keys(a.Od)]},
Se(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},Ge(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},Nd:{read(a,b,c,d,e){if(e>=a.node.Td)return 0;d=Math.min(a.node.Td-e,d);b.set(a.node.Od.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===m.buffer&&(f=!1);if(!d)return 0;a=a.node;a.Zd=a.Wd=Date.now();if(f)a.Od=b.subarray(c,c+d),a.Td=d;else if(0===a.Td&&0===e)a.Od=b.slice(c,c+d),a.Td=d;else{f=e+d;var g=a.Od.length;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),g&&(f=Math.max(f,
256)),g=a.Od.subarray(0,a.Td),a.Od=new Uint8Array(f),a.Od.set(g));a.Od.set(b.subarray(c,c+d),e);a.Td=Math.max(a.Td,e+d)}return d},ce(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Td);if(0>b)throw new S(28);return b},jf(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new S(43);a=a.node.Od;if(e&2||a.buffer!==m.buffer){d=!0;y();e=void 0;if(!e)throw new S(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);m.set(a,e)}}else d=
!1,e=a.byteOffset;return{Qg:e,ng:d}},Ef(a,b,c,d){U.Nd.write(a,b,0,d,c,!1);return 0}}},ld=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},md=async a=>{a=await ea(a);return new Uint8Array(a)},nd=0,od=null,pd=()=>{nd--;h.monitorRunDependencies?.(nd);if(0==nd&&od){var a=od;od=null;a()}},qd=()=>{nd++;h.monitorRunDependencies?.(nd)},rd=async(a,b)=>{"undefined"!=typeof Xb&&Tb();for(var c of Qb)if(c.canHandle(b))return c.handle(a,b);return a},sd=null,td={},za=[],ud=1,vd=null,xa=!1,wd=!0,S=class{name="ErrnoError";constructor(a){this.te=
a}},xd=class{Qd={};node=null;get flags(){return this.Qd.flags}set flags(a){this.Qd.flags=a}get position(){return this.Qd.position}set position(a){this.Qd.position=a}},yd=class{Ld={};Nd={};ue=null;constructor(a,b,c,d){a||=this;this.parent=a;this.ke=a.ke;this.id=ud++;this.name=b;this.mode=c;this.Qe=d;this.pe=this.Zd=this.Wd=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=
-147}get cg(){return V(this.mode)}get bg(){return 8192===(this.mode&61440)}};
function zd(a,b={}){if(!a)throw new S(44);b.cf??(b.cf=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(l=>!!l);for(var d=sd,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Uc(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Tc(e+"/"+a[f]);try{d=jd(d,a[f])}catch(l){if(44===l?.te&&g&&b.fg)return{path:e};throw l;}!d.ue||g&&!b.cf||(d=d.ue.root);if(40960===(d.mode&61440)&&(!g||b.bf)){if(!d.Ld.Ge)throw new S(52);
d=d.Ld.Ge(d);"/"===d.charAt(0)||(d=Uc(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new S(32);}function Ad(a){for(var b;;){if(a===a.parent)return a=a.ke.Df,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Bd(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%vd.length}
function kd(a){var b=Bd(a.parent.id,a.name);if(vd[b]===a)vd[b]=a.ve;else for(b=vd[b];b;){if(b.ve===a){b.ve=a.ve;break}b=b.ve}}function jd(a,b){var c=V(a.mode)?(c=Cd(a,"x"))?c:a.Ld.Ee?0:2:54;if(c)throw new S(c);for(c=vd[Bd(a.id,b)];c;c=c.ve){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ld.Ee(a,b)}function hd(a,b,c,d){a=new yd(a,b,c,d);b=Bd(a.parent.id,a.name);a.ve=vd[b];return vd[b]=a}function V(a){return 16384===(a&61440)}
function Cd(a,b){return wd?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function Dd(a,b){if(!V(a.mode))return 54;try{return jd(a,b),20}catch(c){}return Cd(a,"wx")}function Ed(a,b,c){try{var d=jd(a,b)}catch(e){return e.te}if(a=Cd(a,"wx"))return a;if(c){if(!V(d.mode))return 54;if(d===d.parent||"/"===Ad(d))return 10}else if(V(d.mode))return 31;return 0}function Fd(a){a=za[a];if(!a)throw new S(8);return a}
function Gd(a,b){var c=null?.Nd.ee,d=c?null:a;c??=a.Ld.ee;if(!c)throw new S(63);c(d,b)}var gd={open(a){a.Nd=td[a.node.Qe].Nd;a.Nd.open?.(a)},ce(){throw new S(70);}};function cd(a,b){td[a]={Nd:b}}function Hd(a,b){var c="/"===b;if(c&&sd)throw new S(10);if(!c&&b){var d=zd(b,{cf:!1});b=d.path;d=d.node;if(d.ue)throw new S(10);if(!V(d.mode))throw new S(54);}b={type:a,Og:{},Df:b,eg:[]};a=a.ke(b);a.ke=b;b.root=a;c?sd=a:d&&(d.ue=b,d.ke&&d.ke.eg.push(b))}
function Id(a,b,c){var d=zd(a,{parent:!0}).node;a=Vc(a);if(!a)throw new S(28);if("."===a||".."===a)throw new S(20);var e=Dd(d,a);if(e)throw new S(e);if(!d.Ld.Pe)throw new S(63);return d.Ld.Pe(d,a,b,c)}function Jd(a,b=438){return Id(a,b&4095|32768,0)}function X(a){return Id(a,16895,0)}function Ld(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Id(a,b|8192,c)}
function Md(a,b){if(!Yc(a))throw new S(44);var c=zd(b,{parent:!0}).node;if(!c)throw new S(44);b=Vc(b);var d=Dd(c,b);if(d)throw new S(d);if(!c.Ld.Se)throw new S(63);c.Ld.Se(c,b,a)}function Nd(a){var b=zd(a,{parent:!0}).node;if(!b)throw new S(44);a=Vc(a);var c=jd(b,a),d=Ed(b,a,!1);if(d)throw new S(d);if(!b.Ld.Te)throw new S(63);if(c.ue)throw new S(10);b.Ld.Te(b,a);kd(c)}function Od(a,b){a="string"==typeof a?zd(a,{bf:!0}).node:a;Gd(a,{mode:b&4095|a.mode&-4096,Wd:Date.now(),Bg:void 0})}
function Pd(a,b){if(""===a)throw new S(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");var f=zd(a,{bf:!(b&131072),fg:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new S(20);}else{if(e)throw new S(31);d=Id(a,c|511,0);f=!0}if(!d)throw new S(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!V(d.mode))throw new S(54);
if(!f&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=V(d.mode)&&("r"!==e||b&576)?31:Cd(d,e)):e=44,e))throw new S(e);if(b&512&&!f){e=d;e="string"==typeof e?zd(e,{bf:!0}).node:e;if(V(e.mode))throw new S(31);if(32768!==(e.mode&61440))throw new S(28);if(a=Cd(e,"w"))throw new S(a);Gd(e,{size:0,timestamp:Date.now()})}b={node:d,path:Ad(d),flags:b&-131713,seekable:!0,position:0,Nd:d.Nd,lg:[],error:!1};e=-1;b=Object.assign(new xd,b);if(-1==e)a:{for(e=0;4096>=e;e++)if(!za[e])break a;
throw new S(33);}b.De=e;za[e]=b;b.Nd.open&&b.Nd.open(b);f&&Od(d,c&511);return b}function Aa(a){if(null===a.De)throw new S(8);a.ef&&(a.ef=null);try{a.Nd.close&&a.Nd.close(a)}catch(b){throw b;}finally{za[a.De]=null}a.De=null}function Qd(a,b,c){if(null===a.De)throw new S(8);if(!a.seekable||!a.Nd.ce)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.Nd.ce(a,b,c);a.lg=[]}
function Rd(a,b,c,d,e,f){if(0>d||0>e)throw new S(28);if(null===a.De)throw new S(8);if(0===(a.flags&2097155))throw new S(8);if(V(a.node.mode))throw new S(31);if(!a.Nd.write)throw new S(28);a.seekable&&a.flags&1024&&Qd(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new S(70);b=a.Nd.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Sd(a,b){a="string"==typeof a?a:Ad(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Tc(a+"/"+c);try{X(d)}catch(e){if(20!=e.te)throw e;}a=d}}return d}function Td(a,b,c,d){a=Tc(("string"==typeof a?a:Ad(a))+"/"+b);return Jd(a,ld(c,d))}function Ud(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Ad(a),g=b?Tc(a+"/"+b):a);a=ld(d,e);g=Jd(g,a);c&&("string"==typeof c&&(c=$c(c)),c.subarray||(c=new Uint8Array(c)),Od(g,a|146),b=Pd(g,577),Rd(b,c,0,c.length,0,f),Aa(b),Od(g,a))}
function Y(a,b,c,d){a=Tc(("string"==typeof a?a:Ad(a))+"/"+b);b=ld(!!c,!!d);Y.Cf??(Y.Cf=64);var e=Y.Cf++<<8|0;cd(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,n){for(var p=0,v=0;v<n;v++){try{var x=c()}catch(B){throw new S(29);}if(void 0===x&&0===p)throw new S(6);if(null===x||void 0===x)break;p++;g[l+v]=x}p&&(f.node.pe=Date.now());return p},write(f,g,l,n){for(var p=0;p<n;p++)try{d(g[l+p])}catch(v){throw new S(29);}n&&(f.node.Zd=f.node.Wd=Date.now());return p}});return Ld(a,
b,e)}function Vd(a){if(!(a.bg||a.cg||a.link||a.Od))if(globalThis.XMLHttpRequest)y("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Od=(void 0)(a.url)}catch(b){throw new S(29);}}
function Wd(a,b,c,d,e){class f{he=!1;Qd=[];Sd=void 0;ye=0;se=0;get(p){if(!(p>this.length-1||0>p)){var v=p%this.Ae;return this.Sd(p/this.Ae|0)[v]}}Mf(p){this.Sd=p}ze(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);200<=p.status&&300>p.status||304===p.status||y("Couldn't load "+c+". Status: "+p.status);var v=Number(p.getResponseHeader("Content-length")),x,B=(x=p.getResponseHeader("Accept-Ranges"))&&"bytes"===x;p=(x=p.getResponseHeader("Content-Encoding"))&&"gzip"===x;var G=1048576;B||(G=
v);var D=this;D.Mf(R=>{var T=R*G,W=(R+1)*G-1;W=Math.min(W,v-1);if("undefined"==typeof D.Qd[R]){var Ab=D.Qd;T>W&&y("invalid range ("+T+", "+W+") or no bytes requested!");W>v-1&&y("only "+v+" bytes available! programmer error!");var I=new XMLHttpRequest;I.open("GET",c,!1);v!==G&&I.setRequestHeader("Range","bytes="+T+"-"+W);I.responseType="arraybuffer";I.overrideMimeType&&I.overrideMimeType("text/plain; charset=x-user-defined");I.send(null);200<=I.status&&300>I.status||304===I.status||y("Couldn't load "+
c+". Status: "+I.status);T=void 0!==I.response?new Uint8Array(I.response||[]):$c(I.responseText||"");Ab[R]=T}"undefined"==typeof D.Qd[R]&&y("doXHR failed!");return D.Qd[R]});if(p||!v)G=v=1,G=v=this.Sd(0).length,fa("LazyFiles on gzip forces download of the whole file when length is accessed");this.ye=v;this.se=G;this.he=!0}get length(){this.he||this.ze();return this.ye}get Ae(){this.he||this.ze();return this.se}}if(globalThis.XMLHttpRequest){y("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var g=new f;var l=void 0}else l=c,g=void 0;var n=Td(a,b,d,e);g?n.Od=g:l&&(n.Od=null,n.url=l);Object.defineProperties(n,{Td:{get:function(){return this.Od.length}}});a={};for(const [p,v]of Object.entries(n.Nd))a[p]=(...x)=>{Vd(n);return v(...x)};a.read=(p,v,x,B,G)=>{Vd(n);p=p.node.Od;if(G>=p.length)v=0;else{B=Math.min(p.length-G,B);if(p.slice)for(var D=0;D<B;D++)v[x+D]=p[G+D];else for(D=0;D<B;D++)v[x+D]=p.get(G+D);v=B}return v};a.jf=()=>{Vd(n);y();throw new S(48);};n.Nd=a;return n}
var Xd={},Yd=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{"suspended"===a.state&&a.resume()},{once:!0})},Zd=(a,b=[])=>{z(a)(...b)},$d=(a,b,c,d)=>{var e={string:p=>{var v=0;null!==p&&void 0!==p&&0!==p&&(v=Bb(p));return v},array:p=>{var v=zb(p.length);m.set(p,v);return v}};a=h["_"+a];var f=[],g=0;if(d)for(var l=0;l<d.length;l++){var n=e[c[l]];n?(0===g&&(g=Cb()),f[l]=n(d[l])):f[l]=d[l]}c=a(...f);return c=function(p){0!==
g&&Db(g);return"string"===b?p?F(q,p):"":"boolean"===b?!!p:p}(c)};h.requestAnimationFrame=cb;h.pauseMainLoop=ob;h.resumeMainLoop=function(){fb++;var a=Wa,b=Xa,c=Ya;Ya=null;nb(c,0,!1,gb,!0);eb(a,b);$a()};h.preMainLoop&&lb.push(h.preMainLoop);h.postMainLoop&&mb.push(h.postMainLoop);for(let a=0;32>a;++a)qc.push(Array(a));for(var ae=new Float32Array(288),Z=0;288>=Z;++Z)Cc[Z]=ae.subarray(0,Z);var be=new Int32Array(288);for(Z=0;288>=Z;++Z)Dc[Z]=be.subarray(0,Z);vd=Array(4096);Hd(U,"/");X("/tmp");X("/home");
X("/home/web_user");(function(){X("/dev");cd(259,{read:()=>0,write:(d,e,f,g)=>g,ce:()=>0});Ld("/dev/null",259);bd(1280,ed);bd(1536,fd);Ld("/dev/tty",1280);Ld("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Xc(a),b=a.byteLength);return a[--b]};Y("/dev","random",c);Y("/dev","urandom",c);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");Hd({ke(){var b=hd(a,"fd",16895,73);b.Nd={ce:U.Nd.ce};b.Ld={Ee(c,d){c=+d;var e=Fd(c);c={parent:null,ke:{Df:"fake"},Ld:{Ge:()=>e.path},id:c+1};return c.parent=c},nf(){return Array.from(za.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.noExitRuntime&&(Ja=h.noExitRuntime);h.preloadPlugins&&(Qb=h.preloadPlugins);h.print&&(fa=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(ha=h.wasmBinary);
h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.addRunDependency=qd;h.removeRunDependency=pd;h.ccall=$d;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>$d(a,b,c,f,d)};h.writeArrayToMemory=(a,b)=>{m.set(a,b)};
h.FS_preloadFile=async(a,b,c,d,e,f,g,l)=>{var n=b?Yc(Tc(a+"/"+b)):a,p=`cp ${n}`;qd(p);try{var v=c;"string"==typeof c&&(v=await md(c));v=await rd(v,n);l?.();f||Ud(a,b,v,d,e,g)}finally{pd(p)}};h.FS_unlink=(...a)=>Nd(...a);h.FS_createPath=(...a)=>Sd(...a);h.FS_createDevice=(...a)=>Y(...a);h.FS_createDataFile=(...a)=>Ud(...a);h.FS_createLazyFile=(...a)=>Wd(...a);
var Ua={51226:()=>{"undefined"===typeof h.SDL3&&(h.SDL3={});var a=h.SDL3;"undefined"===typeof a.re&&(a.re=function(b){return b});"undefined"===typeof a.Ue&&(a.Ue=function(b){return b>>>2})},51540:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,51687:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,51921:()=>{var a=h.SDL3;"undefined"===typeof a.Pd&&
(a.Pd={});"undefined"===typeof a.Md&&(a.Md={});a.Rd||("undefined"!==typeof AudioContext?a.Rd=new AudioContext:"undefined"!==typeof webkitAudioContext&&(a.Rd=new webkitAudioContext),a.Rd&&"undefined"===typeof navigator.userActivation&&Yd(a.Rd));return void 0!==a.Rd},52500:()=>h.SDL3.Rd.sampleRate,52551:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.Md.ae&&(clearInterval(g.Md.ae),g.Md.ae=void 0,g.Md.qe=void 0);g.Md.hf=g.Rd.createMediaStreamSource(l);g.Md.$d=g.Rd.createScriptProcessor(b,a,1);g.Md.$d.onaudioprocess=
function(n){void 0!==g&&void 0!==g.Md&&(n.outputBuffer.getChannelData(0).fill(0),g.Md.We=n.inputBuffer,Zd(c,[d]))};g.Md.hf.connect(g.Md.$d);g.Md.$d.connect(g.Rd.destination);g.Md.stream=l}var g=h.SDL3;g.Md.qe=g.Rd.createBuffer(a,b,g.Rd.sampleRate);g.Md.qe.getChannelData(0).fill(0);g.Md.ae=setInterval(function(){g.Md.We=g.Md.qe;Zd(c,[d])},b/g.Rd.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):
void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},54392:(a,b,c,d)=>{var e=h.SDL3;e.Pd.$d=e.Rd.createScriptProcessor(b,0,a);e.Pd.$d.onaudioprocess=function(f){void 0!==e&&void 0!==e.Pd&&(void 0!==e.Pd.ae&&(clearInterval(e.Pd.ae),e.Pd.ae=void 0,e.Pd.qe=void 0),e.Pd.Je=f.outputBuffer,Zd(c,[d]))};e.Pd.$d.connect(e.Rd.destination);"suspended"===e.Rd.state&&(e.Pd.qe=e.Rd.createBuffer(a,b,e.Rd.sampleRate),e.Pd.qe.getChannelData(0).fill(0),e.Pd.ae=setInterval(function(){"undefined"!==
typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.Rd.resume();e.Pd.Je=e.Pd.qe;Zd(c,[d]);e.Pd.Je=void 0},b/e.Rd.sampleRate*1E3))},55708:a=>{var b=h.SDL3;if(a){void 0!==b.Md.ae&&clearInterval(b.Md.ae);if(void 0!==b.Md.stream){a=b.Md.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.Md.stream.removeTrack(a[c])}void 0!==b.Md.$d&&(b.Md.$d.onaudioprocess=function(){},b.Md.$d.disconnect());void 0!==b.Md.hf&&b.Md.hf.disconnect();b.Md=void 0}else void 0!=b.Pd.$d&&b.Pd.$d.disconnect(),
void 0!==b.Pd.ae&&clearInterval(b.Pd.ae),b.Pd=void 0;void 0!==b.Rd&&void 0===b.Pd&&void 0===b.Md&&(b.Rd.close(),b.Rd=void 0)},56864:(a,b)=>{var c=h.SDL3;a=c.Ue(a);for(var d=c.Pd.Je.numberOfChannels,e=0;e<d;++e){var f=c.Pd.Je.getChannelData(e);if(f.length!=b)throw"Web Audio playback buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=u[a+(g*d+e)]}},57397:(a,b)=>{for(var c=h.SDL3,d=c.Md.We.numberOfChannels,e=0;e<d;++e){var f=c.Md.We.getChannelData(e);
if(f.length!=b)throw"Web Audio recording buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ka(a+4*g,f[g]);else for(g=0;g<b;++g)Ka(a+4*(g*d+e),f[g])}},58024:()=>window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?0:window.matchMedia("(prefers-color-scheme: dark)").matches?1:-1:-1,58233:()=>{if("undefined"!==typeof h.SDL3){var a=h.SDL3;a.rf.removeEventListener("change",a.$e);a.rf=void 0;a.$e=void 0}},58486:()=>
window.innerWidth,58516:()=>window.innerHeight,58547:a=>{h.requestFullscreen=function(){ce(a)}},58656:()=>{h.requestFullscreen=function(){}},58730:()=>window.innerWidth,58760:()=>window.innerHeight,58791:a=>{a=document.querySelector(a?F(q,a):"");a.Kf=a.style.position;a.Lf=a.style.top;a.Jf=a.style.left;var b=document.createElement("div");b.id="SDL3_fill_document_background_elements";b.Qd=a;b.ze=a.parentNode;b.ye=a.nextSibling;var c=Array.from(document.body.children),d;for(d of c)b.appendChild(d);document.body.appendChild(b);
b.style.display="none";document.body.appendChild(a);a.style.position="fixed";a.style.top="0";a.style.left="0"},59489:()=>{var a=document.getElementById("SDL3_fill_document_background_elements");if(a){for(a.ye?a.ze.insertBefore(a.Qd,a.ye):a.ze.appendChild(a.Qd);a.firstChild;)document.body.insertBefore(a.firstChild,a);a.Qd.style.position=a.Qd.Kf;a.Qd.style.top=a.Qd.Lf;a.Qd.style.left=a.Qd.Jf;a.remove()}},60048:()=>{if(window.matchMedia){var a=h.SDL3;a.$e=function(){de()};a.rf=window.matchMedia("(prefers-color-scheme: dark)");
a.rf.addEventListener("change",a.$e)}},60370:(a,b,c,d,e)=>{a=a?F(q,a):"";b=b?F(q,b):"";c=c?F(q,c):"";d=d?F(q,d):"";var f=e?F(q,e):"";e=document.createElement("dialog");e.classList.add("SDL3_messagebox");e.id=f;e.style.color=d;e.style.backgroundColor=c;document.body.append(e);d=document.createElement("h1");d.innerText=a;e.append(d);a=document.createElement("p");a.innerText=b;e.append(a);e.showModal()},60911:(a,b,c,d,e,f,g,l)=>{a=a?F(q,a):"";b=b?F(q,b):"";f=f?F(q,f):"";var n=g?F(q,g):"",p=l?F(q,l):
"",v=document.getElementById(a);if(!v)return!1;var x=document.createElement("button");x.innerText=b;x.style.borderColor=f;x.style.backgroundColor=n;v.addEventListener("keydown",function(B){d&&"Enter"===B.key?(B.preventDefault(),x.click()):e&&"Escape"===B.key&&(B.preventDefault(),x.click())});v.addEventListener("cancel",function(B){B.preventDefault()});x.onmouseenter=function(){x.style.backgroundColor=p};x.onmouseleave=function(){x.style.backgroundColor=n};x.onclick=function(){v.close(c)};v.append(x);
return!0},61920:a=>{a=a?F(q,a):"";return(a=document.getElementById(a))?a.open:!1},62058:a=>{a=a?F(q,a):"";a=document.getElementById(a);if(!a)return 0;try{return parseInt(a.returnValue)}catch(b){return 0}},62240:(a,b)=>{alert((a?F(q,a):"")+"\n\n"+(b?F(q,b):""))},62297:(a,b,c,d)=>{d=d?F(q,d):"";var e=document.querySelector(d);d=h.SDL3;if(d.Pf!==e){d.Be=Wb(e);if(!d.Be)return!1;d.Pf=e}if(d.w!==a||d.h!==b||d.$f!==d.Be)d.image=d.Be.createImageData(a,b),d.w=a,d.h=b,d.$f=d.Be;a=d.image.data;c/=4;d.Tf!==a&&
(d.Sf=new Int32Array(a.buffer),d.Tf=a);a=d.Sf;a.set(r.subarray(c,c+a.length));d.Be.putImageData(d.image,0,0);return!0},63046:()=>{var a=h.SDL3;a.mouse_x=0;a.mouse_y=0;a.mouse_buttons=[];for(var b=0;5>b;++b)a.mouse_buttons[b]=!1;document.addEventListener("mousemove",function(c){var d=h.SDL3;d.mouse_x=c.clientX;d.mouse_y=c.clientY});document.addEventListener("mousedown",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!0)});document.addEventListener("mouseup",
function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!1)})},63734:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);e/=4;b=new Int32Array(a.data.buffer);b.set(r.subarray(e,e+b.length));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=ee(c.length+1);J(c,q,d,c.length+1);return d},64392:a=>{h.canvas&&(h.canvas.style.cursor=
a?F(q,a):"")},64475:()=>{h.canvas&&(h.canvas.style.cursor="none")},64544:()=>h.SDL3.mouse_x,64582:()=>h.SDL3.mouse_y,64620:a=>h.SDL3.mouse_buttons[a],64668:a=>{document.Sd=function(b){"CapsLock"!=b.key&&"NumLock"!=b.key&&"ScrollLock"!=b.key&&fe(h.SDL3.re(a),b.getModifierState("CapsLock"),b.getModifierState("NumLock"),b.getModifierState("ScrollLock"))};document.addEventListener("keydown",document.Sd)},65095:()=>{document.removeEventListener("keydown",document.Sd)},65179:a=>{var b=document;b&&(b.Qd=
function(c){var d=h.SDL3;c=d.Fe(0,0,c);0!=c&&(ge(d.re(a),c),he(c))},b.addEventListener("pointerup",b.Qd))},65540:a=>{var b=h.SDL3;void 0===b.Fe&&(b.Fe=function(c,d,e){if("mouse"==e.pointerType)var f=1;else if("touch"==e.pointerType)f=2;else if("pen"==e.pointerType)f=3;else return 0;var g=ee(a);if(0!=g){var l=b.Ue(g);r[l++]=f;r[l++]=e.pointerId;r[l++]="undefined"!==typeof e.button?e.button:-1;r[l++]=e.buttons;r[l++]="pointerdown"==e.type?1:0;u[l++]=e.movementX;u[l++]=e.movementY;u[l++]=e.clientX-c;
u[l++]=e.clientY-d;3==f&&(u[l++]=e.pressure,u[l++]=e.Tg,u[l++]=e.tiltX,u[l++]=e.tiltY,u[l++]=e.Wg)}return g})},66532:a=>{a=a?F(q,a):"";try{var b=document.querySelector(a);if(b)return b===document.activeElement}catch(c){}return!1},66698:()=>document.hasFocus(),66730:()=>{var a=document;a&&(a.removeEventListener("pointerup",a.Qd),a.Qd=void 0)},66912:()=>document.body.clientWidth,66950:()=>document.body.clientHeight,66989:()=>window.innerWidth,67019:()=>window.innerHeight,67050:()=>window.outerWidth,
67080:()=>window.outerHeight,67111:()=>window.pageXOffset,67142:()=>window.pageYOffset,67173:(a,b)=>{var c=document.querySelector(b?F(q,b):"");if(c){var d=h.SDL3;c.se=function(e){var f=c.getBoundingClientRect();e=d.Fe(f.left,f.top,e);0!=e&&(ie(d.re(a),e),he(e))};c.he=function(e){var f=c.getBoundingClientRect();e=d.Fe(f.left,f.top,e);0!=e&&(je(d.re(a),e),he(e))};c.Sd=function(e){var f=c.getBoundingClientRect();e=d.Fe(f.left,f.top,e);0!=e&&(ke(d.re(a),e),he(e))};c.style.touchAction="none";c.addEventListener("pointerenter",
c.se);c.addEventListener("pointerleave",c.he);c.addEventListener("pointercancel",c.he);c.addEventListener("pointerdown",c.Sd);c.addEventListener("pointermove",c.Sd);c.addEventListener("pointerup",c.Sd)}},68561:(a,b,c)=>{var d=document.querySelector(b?F(q,b):"");if(d){var e=h.SDL3,f=function(g){var l=ee(c);if(0!=l){var n=l>>2,p=d.getBoundingClientRect();r[n++]=g.clientX-p.left;r[n++]=g.clientY-p.top}return l};e.Ye=function(g){g.preventDefault();g=f(g);0!=g&&(le(a,g),he(g))};d.addEventListener("dragover",
e.Ye);e.Ke=0;try{X("/tmp/filedrop")}catch(g){}e.Ze=function(g){g.preventDefault();if(g.dataTransfer.types.includes("text/plain"))g=vc(g.dataTransfer.getData("text/plain")),me(a,g),ne(g);else if(g.dataTransfer.types.includes("Files")){let l=0;const n=g.dataTransfer.files.length;for(let p=0;p<n;p++){const v=g.dataTransfer.files.item(p),x=new FileReader;x.readAsArrayBuffer(v);x.onload=function(B){const G=`/tmp/filedrop/${e.Ke}`;e.Ke+=1;const D=`${G}/${v.name}`,R=vc(D);B=new Uint8Array(B.target.result);
try{X(G);var T=Pd(D,"w");Rd(T,B,0,B.length,0);Aa(T);oe(a,R)}catch(W){}ne(R);++l;l===n&&pe(a)};x.onerror=function(){++l;l===n&&pe(a)}}}pe(a)};d.addEventListener("drop",e.Ze);e.Ce=function(g){g.preventDefault();pe(a)};d.addEventListener("dragend",e.Ce);d.addEventListener("dragleave",e.Ce)}},70928:a=>{if(a=document.querySelector(a?F(q,a):"")){var b=h.SDL3;a.removeEventListener("dragleave",b.Ce);a.removeEventListener("dragend",b.Ce);a.removeEventListener("drop",b.Ze);b.Ke=void 0;"/tmp/filedrop";var c=
zd("/tmp/filedrop",{parent:!0}).node,d=Vc("/tmp/filedrop"),e=jd(c,d),f=Ed(c,d,!0);if(f)throw new S(f);if(!c.Ld.Re)throw new S(63);if(e.ue)throw new S(10);c.Ld.Re(c,d);kd(e);a.removeEventListener("dragover",b.Ye);b.Ye=void 0;b.Ze=void 0;b.Ce=void 0}},71758:a=>{if(a=document.querySelector(a?F(q,a):""))a.removeEventListener("pointerenter",a.se),a.removeEventListener("pointerleave",a.he),a.removeEventListener("pointercancel",a.he),a.removeEventListener("pointerdown",a.Sd),a.removeEventListener("pointermove",
a.Sd),a.removeEventListener("pointerup",a.Sd),a.style.touchAction="",a.se=void 0,a.he=void 0,a.Sd=void 0}},qe,he,ee,ne,ya,P,ie,je,ke,ge,le,pe,me,oe,fe,de,ce,ua,re,Db,zb,Cb,pa,Ma,se={Pa:(a,b)=>z(a)(b),Ya:()=>y(""),Ra:()=>{Ja=!1;A=0},Sa:(a,b)=>{Na[a]&&(clearTimeout(Na[a].id),delete Na[a]);if(!b)return 0;var c=setTimeout(()=>{delete Na[a];Ra(()=>re(a,performance.now()))},b);Na[a]={id:c,Ug:b};return 0},w:Va,d:(a,b,c)=>{b=Ta(b,c);return Ua[a](...b)},a:Va,jc:(a,b,c)=>{b=Ta(b,c);return Ua[a](...b)},Zc:()=>
{ob();Ya=null},Wa:()=>Date.now(),Ka:()=>{if(!C.fullscreenEnabled())return-1;sb(Mb);var a=wb[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Qb:()=>{sb(Nb);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},bb:a=>{Ja=!1;A=0;ja=a;Ja||0<A||ta();Pa(a)},f:()=>devicePixelRatio,b:(a,b,c)=>{a=H(a);if(!a)return-4;a=Lb(a);w[b>>3]=a.width;w[c>>3]=a.height;return 0},
Ma:a=>{if(!C.fullscreenEnabled())return-1;Ob(a);return 0},V:(a,b)=>{a&&(r[a>>2]=Wa);b&&(r[b>>2]=Xa)},j:()=>performance.now(),Ec:(a,b)=>{r[a>>2]=screen.width;r[b>>2]=screen.height},qa:a=>K.activeTexture(a),pa:(a,b)=>{K.attachShader(L[a],M[b])},Ga:(a,b)=>{K.ie.beginQueryEXT(a,N[b])},oa:(a,b,c)=>{K.bindAttribLocation(L[a],b,c?F(q,c):"")},na:(a,b)=>{K.bindBuffer(a,cc[b])},ma:(a,b)=>{K.bindFramebuffer(a,dc[b])},la:(a,b)=>{K.bindRenderbuffer(a,ec[b])},ka:(a,b)=>{K.bindTexture(a,fc[b])},ya:a=>{K.bindVertexArray(gc[a])},
ja:(a,b,c,d)=>K.blendColor(a,b,c,d),ia:a=>K.blendEquation(a),ha:(a,b)=>K.blendEquationSeparate(a,b),ga:(a,b)=>K.blendFunc(a,b),fa:(a,b,c,d)=>K.blendFuncSeparate(a,b,c,d),ea:(a,b,c,d)=>{K.bufferData(a,c?q.subarray(c,c+b):b,d)},da:(a,b,c,d)=>{K.bufferSubData(a,b,q.subarray(d,d+c))},ca:a=>K.checkFramebufferStatus(a),ba:a=>K.clear(a),aa:(a,b,c,d)=>K.clearColor(a,b,c,d),$:a=>K.clearDepth(a),_:a=>K.clearStencil(a),ab:(a,b)=>{K.Xf.clipControlEXT(a,b)},Z:(a,b,c,d)=>{K.colorMask(!!a,!!b,!!c,!!d)},Y:a=>{K.compileShader(M[a])},
X:(a,b,c,d,e,f,g,l)=>{K.compressedTexImage2D(a,b,c,d,e,f,q.subarray(l,l+g))},W:(a,b,c,d,e,f,g,l,n)=>{K.compressedTexSubImage2D(a,b,c,d,e,f,g,q.subarray(n,n+l))},U:(a,b,c,d,e,f,g,l)=>K.copyTexImage2D(a,b,c,d,e,f,g,l),T:(a,b,c,d,e,f,g,l)=>K.copyTexSubImage2D(a,b,c,d,e,f,g,l),S:()=>{var a=lc(L),b=K.createProgram();b.name=a;b.Oe=b.Me=b.Ne=0;b.tf=1;L[a]=b;return a},R:a=>{var b=lc(M);M[b]=K.createShader(a);return b},Q:a=>K.cullFace(a),P:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=cc[d];e&&(K.deleteBuffer(e),
e.name=0,cc[d]=null)}},O:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+4*c>>2],e=dc[d];e&&(K.deleteFramebuffer(e),e.name=0,dc[d]=null)}},N:a=>{if(a){var b=L[a];b?(K.deleteProgram(b),b.name=0,L[a]=null):O||=1281}},Ia:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=N[d];e&&(K.ie.deleteQueryEXT(e),N[d]=null)}},M:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=ec[d];e&&(K.deleteRenderbuffer(e),e.name=0,ec[d]=null)}},L:a=>{if(a){var b=M[a];b?(K.deleteShader(b),M[a]=null):O||=1281}},J:(a,b)=>{for(var c=0;c<
a;c++){var d=r[b+4*c>>2],e=fc[d];e&&(K.deleteTexture(e),e.name=0,fc[d]=null)}},xa:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2];K.deleteVertexArray(gc[d]);gc[d]=null}},I:a=>K.depthFunc(a),H:a=>{K.depthMask(!!a)},G:(a,b)=>K.depthRange(a,b),F:(a,b)=>{K.detachShader(L[a],M[b])},E:a=>K.disable(a),D:a=>{K.disableVertexAttribArray(a)},C:(a,b,c)=>{K.drawArrays(a,b,c)},ta:(a,b,c,d)=>{K.drawArraysInstanced(a,b,c,d)},ua:(a,b)=>{for(var c=qc[a],d=0;d<a;d++)c[d]=r[b+4*d>>2];K.drawBuffers(c)},B:(a,b,c,d)=>{K.drawElements(a,
b,c,d)},sa:(a,b,c,d,e)=>{K.drawElementsInstanced(a,b,c,d,e)},A:a=>K.enable(a),Yc:a=>{K.enableVertexAttribArray(a)},Fa:a=>{K.ie.endQueryEXT(a)},Xc:()=>K.finish(),Wc:()=>K.flush(),Vc:(a,b,c,d)=>{K.framebufferRenderbuffer(a,b,c,ec[d])},Uc:(a,b,c,d,e)=>{K.framebufferTexture2D(a,b,c,fc[d],e)},Tc:a=>K.frontFace(a),Sc:(a,b)=>{mc(a,b,"createBuffer",cc)},Qc:(a,b)=>{mc(a,b,"createFramebuffer",dc)},Ja:(a,b)=>{for(var c=0;c<a;c++){var d=K.ie.createQueryEXT();if(!d){for(O||=1282;c<a;)r[b+4*c++>>2]=0;break}var e=
lc(N);d.name=e;N[e]=d;r[b+4*c>>2]=e}},Pc:(a,b)=>{mc(a,b,"createRenderbuffer",ec)},Oc:(a,b)=>{mc(a,b,"createTexture",fc)},wa:(a,b)=>{mc(a,b,"createVertexArray",gc)},Rc:a=>K.generateMipmap(a),Nc:(a,b,c,d,e,f,g)=>rc("getActiveAttrib",a,b,c,d,e,f,g),Mc:(a,b,c,d,e,f,g)=>rc("getActiveUniform",a,b,c,d,e,f,g),Lc:(a,b,c,d)=>{a=K.getAttachedShaders(L[a]);var e=a.length;e>b&&(e=b);r[c>>2]=e;for(b=0;b<e;++b)r[d+4*b>>2]=M.indexOf(a[b])},Kc:(a,b)=>K.getAttribLocation(L[a],b?F(q,b):""),Jc:(a,b)=>sc(a,b,4),Ic:(a,
b,c)=>{c?r[c>>2]=K.getBufferParameter(a,b):O||=1281},Hc:()=>{var a=K.getError()||O;O=0;return a},Gc:(a,b)=>sc(a,b,2),Fc:(a,b,c,d)=>{a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r[d>>2]=a},Dc:(a,b)=>sc(a,b,0),Bc:(a,b,c,d)=>{a=K.getProgramInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?J(a,q,d,b):0;c&&(r[c>>2]=b)},Cc:(a,b,c)=>{if(c)if(a>=bc)O||=1281;else if(a=L[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),
r[c>>2]=a.length+1;else if(35719==b){if(!a.Oe){var d=K.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Oe=Math.max(a.Oe,K.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.Oe}else if(35722==b){if(!a.Me)for(d=K.getProgramParameter(a,35721),b=0;b<d;++b)a.Me=Math.max(a.Me,K.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.Me}else if(35381==b){if(!a.Ne)for(d=K.getProgramParameter(a,35382),b=0;b<d;++b)a.Ne=Math.max(a.Ne,K.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.Ne}else r[c>>2]=K.getProgramParameter(a,
b);else O||=1281},Aa:tc,Ca:uc,za:tc,Ba:uc,Da:(a,b,c)=>{c?r[c>>2]=K.ie.getQueryEXT(a,b):O||=1281},Ac:(a,b,c)=>{c?r[c>>2]=K.getRenderbufferParameter(a,b):O||=1281},yc:(a,b,c,d)=>{a=K.getShaderInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?J(a,q,d,b):0;c&&(r[c>>2]=b)},xc:(a,b,c,d)=>{a=K.getShaderPrecisionFormat(a,b);r[c>>2]=a.rangeMin;r[c+4>>2]=a.rangeMax;r[d>>2]=a.precision},wc:(a,b,c,d)=>{if(a=K.getShaderSource(M[a]))b=0<b&&d?J(a,q,d,b):0,c&&(r[c>>2]=b)},zc:(a,b,c)=>{c?35716==b?(a=K.getShaderInfoLog(M[a]),
null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(M[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=K.getShaderParameter(M[a],b):O||=1281},vc:a=>{var b=ic[a];if(!b){switch(a){case 7939:b=vc(wc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=K.getParameter(a))||(O||=1280);b=b?vc(b):0;break;case 7938:b=vc(`OpenGL ES 2.0 (${K.getParameter(7938)})`);break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&
(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=vc(b);break;default:O||=1280}ic[a]=b}return b},uc:(a,b,c)=>{c?u[c>>2]=K.getTexParameter(a,b):O||=1281},tc:(a,b,c)=>{c?r[c>>2]=K.getTexParameter(a,b):O||=1281},qc:(a,b)=>{b=b?F(q,b):"";if(a=L[a]){yc(a);var c=a.He,d=0,e=b,f=xc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.If[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else O||=1281;return-1},sc:(a,b,c)=>{zc(a,b,c,2)},rc:(a,b,c)=>{zc(a,b,c,0)},
nc:(a,b,c)=>{c?r[c>>2]=K.getVertexAttribOffset(a,b):O||=1281},pc:(a,b,c)=>{Ac(a,b,c,2)},oc:(a,b,c)=>{Ac(a,b,c,5)},mc:(a,b)=>K.hint(a,b),lc:a=>(a=cc[a])?K.isBuffer(a):0,kc:a=>K.isEnabled(a),ic:a=>(a=dc[a])?K.isFramebuffer(a):0,hc:a=>(a=L[a])?K.isProgram(a):0,Ha:a=>(a=N[a])?K.ie.isQueryEXT(a):0,gc:a=>(a=ec[a])?K.isRenderbuffer(a):0,fc:a=>(a=M[a])?K.isShader(a):0,ec:a=>(a=fc[a])?K.isTexture(a):0,va:a=>(a=gc[a])?K.isVertexArray(a):0,dc:a=>K.lineWidth(a),cc:a=>{a=L[a];K.linkProgram(a);a.He=0;a.If={}},
bc:(a,b)=>{3317==a?jc=b:3314==a&&(kc=b);K.pixelStorei(a,b)},$a:(a,b)=>{K.mg.polygonModeWEBGL(a,b)},ac:(a,b)=>K.polygonOffset(a,b),cb:(a,b,c)=>{K.Yf.polygonOffsetClampEXT(a,b,c)},Ea:(a,b)=>{K.ie.queryCounterEXT(N[a],b)},$b:(a,b,c,d,e,f,g)=>{(g=Bc(f,e,c,d,g))?K.readPixels(a,b,c,d,e,f,g):O||=1280},_b:()=>{},Zb:(a,b,c,d)=>K.renderbufferStorage(a,b,c,d),Yb:(a,b)=>{K.sampleCoverage(a,!!b)},Xb:(a,b,c,d)=>K.scissor(a,b,c,d),Wb:()=>{O||=1280},Vb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=t[c+4*f>>2])?
F(q,g,d?t[d+4*f>>2]:void 0):"";e+=g}K.shaderSource(M[a],e)},Ub:(a,b,c)=>K.stencilFunc(a,b,c),Tb:(a,b,c,d)=>K.stencilFuncSeparate(a,b,c,d),Sb:a=>K.stencilMask(a),Rb:(a,b)=>K.stencilMaskSeparate(a,b),Pb:(a,b,c)=>K.stencilOp(a,b,c),Ob:(a,b,c,d)=>K.stencilOpSeparate(a,b,c,d),Nb:(a,b,c,d,e,f,g,l,n)=>{n=n?Bc(l,g,d,e,n):null;K.texImage2D(a,b,c,d,e,f,g,l,n)},Mb:(a,b,c)=>K.texParameterf(a,b,c),Lb:(a,b,c)=>{K.texParameterf(a,b,u[c>>2])},Kb:(a,b,c)=>K.texParameteri(a,b,c),Jb:(a,b,c)=>{K.texParameteri(a,b,r[c>>
2])},Ib:(a,b,c,d,e,f,g,l,n)=>{n=n?Bc(l,g,e,f,n):null;K.texSubImage2D(a,b,c,d,e,f,g,l,n)},Hb:(a,b)=>{K.uniform1f(Q(a),b)},Gb:(a,b,c)=>{if(288>=b)for(var d=Cc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);K.uniform1fv(Q(a),d)},Fb:(a,b)=>{K.uniform1i(Q(a),b)},Eb:(a,b,c)=>{if(288>=b)for(var d=Dc[b],e=0;e<b;++e)d[e]=r[c+4*e>>2];else d=r.subarray(c>>2,c+4*b>>2);K.uniform1iv(Q(a),d)},Db:(a,b,c)=>{K.uniform2f(Q(a),b,c)},Cb:(a,b,c)=>{if(144>=b){b*=2;for(var d=Cc[b],e=0;e<b;e+=2)d[e]=u[c+
4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);K.uniform2fv(Q(a),d)},Bb:(a,b,c)=>{K.uniform2i(Q(a),b,c)},Ab:(a,b,c)=>{if(144>=b){b*=2;for(var d=Dc[b],e=0;e<b;e+=2)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2]}else d=r.subarray(c>>2,c+8*b>>2);K.uniform2iv(Q(a),d)},zb:(a,b,c,d)=>{K.uniform3f(Q(a),b,c,d)},yb:(a,b,c)=>{if(96>=b){b*=3;for(var d=Cc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);K.uniform3fv(Q(a),d)},xb:(a,b,c,
d)=>{K.uniform3i(Q(a),b,c,d)},wb:(a,b,c)=>{if(96>=b){b*=3;for(var d=Dc[b],e=0;e<b;e+=3)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2]}else d=r.subarray(c>>2,c+12*b>>2);K.uniform3iv(Q(a),d)},vb:(a,b,c,d,e)=>{K.uniform4f(Q(a),b,c,d,e)},ub:(a,b,c)=>{if(72>=b){var d=Cc[4*b],e=u;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=u.subarray(c>>2,c+16*b>>2);K.uniform4fv(Q(a),d)},tb:(a,b,c,d,e)=>{K.uniform4i(Q(a),b,c,d,e)},sb:(a,b,c)=>{if(72>=
b){b*=4;for(var d=Dc[b],e=0;e<b;e+=4)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2],d[e+3]=r[c+(4*e+12)>>2]}else d=r.subarray(c>>2,c+16*b>>2);K.uniform4iv(Q(a),d)},rb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=Cc[b],f=0;f<b;f+=4)e[f]=u[d+4*f>>2],e[f+1]=u[d+(4*f+4)>>2],e[f+2]=u[d+(4*f+8)>>2],e[f+3]=u[d+(4*f+12)>>2]}else e=u.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(Q(a),!!c,e)},qb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=Cc[b],f=0;f<b;f+=9)e[f]=u[d+4*f>>2],e[f+1]=u[d+(4*f+4)>>2],e[f+2]=u[d+
(4*f+8)>>2],e[f+3]=u[d+(4*f+12)>>2],e[f+4]=u[d+(4*f+16)>>2],e[f+5]=u[d+(4*f+20)>>2],e[f+6]=u[d+(4*f+24)>>2],e[f+7]=u[d+(4*f+28)>>2],e[f+8]=u[d+(4*f+32)>>2]}else e=u.subarray(d>>2,d+36*b>>2);K.uniformMatrix3fv(Q(a),!!c,e)},pb:(a,b,c,d)=>{if(18>=b){var e=Cc[16*b],f=u;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=
f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=u.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(Q(a),!!c,e)},ob:a=>{a=L[a];K.useProgram(a);K.Rf=a},nb:a=>{K.validateProgram(L[a])},mb:(a,b)=>K.vertexAttrib1f(a,b),lb:(a,b)=>{K.vertexAttrib1f(a,u[b>>2])},kb:(a,b,c)=>K.vertexAttrib2f(a,b,c),jb:(a,b)=>{K.vertexAttrib2f(a,u[b>>2],u[b+4>>2])},ib:(a,b,c,d)=>K.vertexAttrib3f(a,b,c,d),hb:(a,b)=>{K.vertexAttrib3f(a,u[b>>2],u[b+4>>2],u[b+8>>2])},gb:(a,b,c,d,e)=>K.vertexAttrib4f(a,b,c,d,e),fb:(a,b)=>{K.vertexAttrib4f(a,
u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},ra:(a,b)=>{K.vertexAttribDivisor(a,b)},eb:(a,b,c,d,e,f)=>{K.vertexAttribPointer(a,b,c,!!d,e,f)},db:(a,b,c,d)=>K.viewport(a,b,c,d),i:()=>0,La:(a,b,c)=>Ec(a,{pf:r[c>>2],Ve:r[c+4>>2],Zf:r[c+8>>2],Uf:b,Ie:r[c+12>>2],xf:r[c+16>>2]}),x:(a,b)=>{a=H(a);return a?a.requestPointerLock?tb()?Nb(a):b?(rb(Nb,2,[a]),1):-2:-1:-4},Ta:a=>{var b=q.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,
65536*Math.ceil(Math.max(a,d)/65536))-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);oa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},k:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Fc(a,b),u:(a,b,c,d)=>Gc(a,b,c,d,12,"blur"),c:Fb,e:(a,b,c)=>{a=H(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},v:(a,b,c,d)=>Gc(a,b,c,d,13,"focus"),s:(a,b,c,d)=>{if(!C.fullscreenEnabled())return-1;a=H(a);if(!a)return-4;Hc(a,b,c,d,"webkitfullscreenchange");return Hc(a,
b,c,d,"fullscreenchange")},o:(a,b,c,d)=>Ic(a,b,c,d,2,"keydown"),m:(a,b,c,d)=>Ic(a,b,c,d,1,"keypress"),n:(a,b,c,d)=>Ic(a,b,c,d,3,"keyup"),Oa:(a,b,c,d)=>{nb(()=>z(a)(b),c,d,b)},g:eb,p:(a,b,c)=>window.screen&&screen.orientation?Jc(a,b,c):-1,t:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?Kc(a,b,c,d):-4:-1,r:(a,b,c,d)=>Lc(a,b,c,d),l:(a,b,c)=>Mc(a,b,c),q:(a,b,c,d)=>(a=H(a))?"undefined"!=typeof a.onwheel?Nc(a,b,c,d):-1:-4,Na:a=>document.title=a?F(q,a):"",h:()=>{y("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},
K:(a,b)=>{var c=b>>2;b={alpha:!!m[b+0],depth:!!m[b+1],stencil:!!m[b+2],antialias:!!m[b+3],premultipliedAlpha:!!m[b+4],preserveDrawingBuffer:!!m[b+5],powerPreference:Oc[r[c+2]],failIfMajorPerformanceCaveat:!!m[b+12],dg:r[c+4],Kg:r[c+5],zf:m[b+24],Wf:m[b+25],Pg:r[c+7],Sg:m[b+32]};a=H(a);return!a||b.Wf?0:oc(a,b)},y:a=>{pc==a&&(pc=0);pc===hc[a]&&(pc=null);"object"==typeof C&&C.ig(hc[a].oe.canvas);hc[a]?.oe.canvas&&(hc[a].oe.canvas.xe=void 0);hc[a]=null},z:a=>{pc=hc[a];h.ctx=K=pc?.oe;return!a||K?0:-5},
Za:(a,b)=>{var c=0,d=0,e;for(e of Rc()){var f=b+c;t[a+d>>2]=f;c+=J(e,q,f,Infinity)+1;d+=4}return 0},_a:(a,b)=>{var c=Rc();t[a>>2]=c.length;a=0;for(var d of c)a+=yb(d)+1;t[b>>2]=a;return 0},Xa:function(a){try{var b=Fd(a);Aa(b);return 0}catch(c){if("undefined"==typeof Xd||"ErrnoError"!==c.name)throw c;return c.te}},Ua:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Fd(a);Qd(e,b,c);sa[d>>3]=BigInt(e.position);e.ef&&0===b&&0===c&&(e.ef=null);return 0}catch(f){if("undefined"==
typeof Xd||"ErrnoError"!==f.name)throw f;return f.te}},Va:function(a,b,c,d){try{a:{var e=Fd(a);a=b;for(var f,g=b=0;g<c;g++){var l=t[a>>2],n=t[a+4>>2];a+=8;var p=Rd(e,m,l,n,f);if(0>p){var v=-1;break a}b+=p;if(p<n)break;"undefined"!=typeof f&&(f+=p)}v=b}t[d>>2]=v;return 0}catch(x){if("undefined"==typeof Xd||"ErrnoError"!==x.name)throw x;return x.te}},Qa:Pa};
function te(a=[]){var b=qe;a.unshift(ba);var c=a.length,d=zb(4*(c+1)),e=d,f;for(f of a)t[e>>2]=Bb(f),e+=4;t[e>>2]=0;try{var g=b(c,d);ja=g;Ja||0<A||ta();Pa(g)}catch(l){Oa(l)}}
function ue(a=aa){function b(){h.calledRun=!0;if(!ia){ma=!0;if(!h.noFSInit&&!xa){var c,d;xa=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?Y("/dev","stdin",c):Md("/dev/tty","/dev/stdin");d?Y("/dev","stdout",null,d):Md("/dev/tty","/dev/stdout");e?Y("/dev","stderr",null,e):Md("/dev/tty1","/dev/stderr");Pd("/dev/stdin",0);Pd("/dev/stdout",1);Pd("/dev/stderr",1)}ve.$c();wd=!1;ka?.(h);h.onRuntimeInitialized?.();h.noInitialRun||te(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Ga.push(e)}va(Ga)}}if(0<nd)od=ue;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ia();va(Ha);0<nd?od=ue:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var ve;
ve=await (async function(){function a(c){c=ve=c.exports;h._upload_rom=c.ad;h._set_button_state=c.bd;h._set_channel_muted=c.cd;h._is_channel_muted=c.dd;h._set_master_volume=c.ed;h._get_master_volume=c.fd;h._get_frame_count=c.gd;h._get_cart_ram_ptr=c.hd;h._get_cart_ram_size=c.id;h._import_save=c.jd;h._shutdown_emulator=c.kd;qe=h._main=c.ld;he=h._SDL_free=c.md;ee=h._SDL_malloc=c.nd;h._SDL_calloc=c.od;ne=h._Emscripten_force_free=c.pd;h._free=c.qd;h._SDL_realloc=c.rd;ya=c.sd;P=h._malloc=c.td;
ie=h._Emscripten_HandlePointerEnter=c.ud;je=h._Emscripten_HandlePointerLeave=c.vd;ke=h._Emscripten_HandlePointerGeneric=c.wd;ge=h._Emscripten_HandleMouseButtonUpGlobal=c.xd;le=h._Emscripten_SendDragEvent=c.yd;pe=h._Emscripten_SendDragCompleteEvent=c.zd;me=h._Emscripten_SendDragTextEvent=c.Ad;oe=h._Emscripten_SendDragFileEvent=c.Bd;fe=h._Emscripten_HandleLockKeysCheck=c.Cd;de=h._Emscripten_SendSystemThemeChangedEvent=c.Dd;ce=h._requestFullscreenThroughSDL=c.Ed;ua=c.Gd;re=c.Hd;Db=c.Id;zb=c.Jd;Cb=c.Kd;
pa=c._c;Ma=c.Fd;oa();return ve}var b={a:se};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});Ba??=h.locateFile?h.locateFile?h.locateFile("GBC.wasm",da):da+"GBC.wasm":(new URL("GBC.wasm",import.meta.url)).href;return a((await Ea(b)).instance)}());ue();ma?moduleRtn=h:moduleRtn=new Promise((a,b)=>{ka=a;la=b});
;return moduleRtn}export default createGBCModule;
