async function createGBCModule(moduleArg={}){var moduleRtn;var h=moduleArg,aa=[],ba="./this.program",ca=import.meta.url,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),k=console.error.bind(console),ja,ka=!1,la,na,oa,m,q,pa,qa,r,t,u,v,w,ra=!1,sa=!1;
function ta(){var a=ua.buffer;h.HEAP8=m=new Int8Array(a);pa=new Int16Array(a);h.HEAPU8=q=new Uint8Array(a);qa=new Uint16Array(a);r=new Int32Array(a);t=new Uint32Array(a);u=new Float32Array(a);v=new Float64Array(a);w=new BigInt64Array(a);new BigUint64Array(a)}function va(){wa();xa(ya);za=!1;Aa(0);for(var a of Ba)a&&Ca(a);sa=!0}function Da(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);ka=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");oa?.(a);throw a;}var Fa;
async function Ga(a){if(!ja)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==Fa&&ja)a=new Uint8Array(ja);else throw"both async and sync fetching of the wasm failed";return a}async function Ha(a,b){try{var c=await Ga(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),Da(d)}}
async function Ia(a){var b=Fa;if(!ja)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return Ha(b,a)}class Ja{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var xa=a=>{for(;0<a.length;)a.shift()(h)},Ka=[],La=[],Ma=()=>{var a=h.preRun.shift();La.push(a)},x=!1;
function Na(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":m[a]=b;break;case "i8":m[a]=b;break;case "i16":pa[a>>1]=b;break;case "i32":r[a>>2]=b;break;case "i64":w[a>>3]=BigInt(b);break;case "float":u[a>>2]=b;break;case "double":v[a>>3]=b;break;case "*":t[a>>2]=b;break;default:Da(`invalid type for setValue: ${c}`)}}
var Oa=[],A=a=>{var b=Oa[a];b||(Oa[a]=b=Pa.get(a));return b},B=()=>{var a=r[+Qa>>2];Qa+=4;return a},Ra=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Sa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ra(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ta=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ua=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Va=()=>a=>crypto.getRandomValues(a),Wa=a=>{(Wa=Va())(a)},Xa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ra(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ya=globalThis.TextDecoder&&new TextDecoder,D=(a,b=0,c)=>{var d=
b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ya)return Ya.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Za=[],$a=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?
b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},bb=[];
function cb(a,b){bb[a]={input:[],output:[],pe:b};db(a,eb)}
var eb={open(a){var b=bb[a.node.He];if(!b)throw new F(43);a.Td=b;a.seekable=!1},close(a){a.Td.pe.Ne(a.Td)},Ne(a){a.Td.pe.Ne(a.Td)},read(a,b,c,d){if(!a.Td||!a.Td.pe.Df)throw new F(60);for(var e=0,f=0;f<d;f++){try{var g=a.Td.pe.Df(a.Td)}catch(l){throw new F(29);}if(void 0===g&&0===e)throw new F(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.re=Date.now());return e},write(a,b,c,d){if(!a.Td||!a.Td.pe.lf)throw new F(60);try{for(var e=0;e<d;e++)a.Td.pe.lf(a.Td,b[c+e])}catch(f){throw new F(29);
}d&&(a.node.ae=a.node.Yd=Date.now());return e}},fb={Df(){a:{if(!Za.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array($a(a)+1);a=E(a,b,0,b.length);b.length=a;Za=b}b=Za.shift()}return b},lf(a,b){null===b||10===b?(fa(D(a.output)),a.output=[]):0!=b&&a.output.push(b)},Ne(a){0<a.output?.length&&(fa(D(a.output)),a.output=[])},fg(){return{yg:25856,Ag:5,xg:191,zg:35387,wg:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0]}},gg(){return 0},hg(){return[24,80]}},gb={lf(a,b){null===b||10===b?(k(D(a.output)),a.output=[]):0!=b&&a.output.push(b)},Ne(a){0<a.output?.length&&(k(D(a.output)),a.output=[])}},G={ie:null,oe(){return G.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);G.ie||(G.ie={dir:{node:{ge:G.Pd.ge,je:G.Pd.je,Ee:G.Pd.Ee,Re:G.Pd.Re,Jf:G.Pd.Jf,Mf:G.Pd.Mf,Se:G.Pd.Se,mf:G.Pd.mf,Te:G.Pd.Te},stream:{he:G.Qd.he}},file:{node:{ge:G.Pd.ge,je:G.Pd.je},
stream:{he:G.Qd.he,read:G.Qd.read,write:G.Qd.write,Ff:G.Qd.Ff,Hf:G.Qd.Hf}},link:{node:{ge:G.Pd.ge,je:G.Pd.je,Ie:G.Pd.Ie},stream:{}},Af:{node:{ge:G.Pd.ge,je:G.Pd.je},stream:hb}});c=ib(a,b,c,d);H(c.mode)?(c.Pd=G.ie.dir.node,c.Qd=G.ie.dir.stream,c.Sd={}):32768===(c.mode&61440)?(c.Pd=G.ie.file.node,c.Qd=G.ie.file.stream,c.Wd=0,c.Sd=null):40960===(c.mode&61440)?(c.Pd=G.ie.link.node,c.Qd=G.ie.link.stream):8192===(c.mode&61440)&&(c.Pd=G.ie.Af.node,c.Qd=G.ie.Af.stream);c.re=c.ae=c.Yd=Date.now();a&&(a.Sd[b]=
c,a.re=a.ae=a.Yd=c.re);return c},Kg(a){return a.Sd?a.Sd.subarray?a.Sd.subarray(0,a.Wd):new Uint8Array(a.Sd):new Uint8Array(0)},Pd:{ge(a){var b={};b.Wf=8192===(a.mode&61440)?a.id:1;b.dg=a.id;b.mode=a.mode;b.kg=1;b.uid=0;b.ag=0;b.He=a.He;H(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Wd:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.re=new Date(a.re);b.ae=new Date(a.ae);b.Yd=new Date(a.Yd);b.Of=4096;b.Pf=Math.ceil(b.size/b.Of);return b},je(a,b){for(var c of["mode","atime","mtime","ctime"])null!=
b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Wd!=b&&(0==b?(a.Sd=null,a.Wd=0):(c=a.Sd,a.Sd=new Uint8Array(b),c&&a.Sd.set(c.subarray(0,Math.min(b,a.Wd))),a.Wd=b)))},Ee(){G.Xe||(G.Xe=new F(44),G.Xe.stack="<generic error, no stack>");throw G.Xe;},Re(a,b,c,d){return G.createNode(a,b,c,d)},Jf(a,b,c){try{var d=jb(b,c)}catch(f){}if(d){if(H(a.mode))for(var e in d.Sd)throw new F(55);kb(d)}delete a.parent.Sd[a.name];b.Sd[c]=a;a.name=c;b.Yd=b.ae=a.parent.Yd=a.parent.ae=Date.now()},Mf(a,b){delete a.Sd[b];a.Yd=
a.ae=Date.now()},Se(a,b){var c=jb(a,b),d;for(d in c.Sd)throw new F(55);delete a.Sd[b];a.Yd=a.ae=Date.now()},mf(a){return[".","..",...Object.keys(a.Sd)]},Te(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},Ie(a){if(40960!==(a.mode&61440))throw new F(28);return a.link}},Qd:{read(a,b,c,d,e){var f=a.node.Sd;if(e>=a.node.Wd)return 0;a=Math.min(a.node.Wd-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===m.buffer&&(f=!1);if(!d)return 0;
a=a.node;a.ae=a.Yd=Date.now();if(b.subarray&&(!a.Sd||a.Sd.subarray)){if(f)return a.Sd=b.subarray(c,c+d),a.Wd=d;if(0===a.Wd&&0===e)return a.Sd=b.slice(c,c+d),a.Wd=d;if(e+d<=a.Wd)return a.Sd.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.Sd?a.Sd.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.Sd,a.Sd=new Uint8Array(f),0<a.Wd&&a.Sd.set(g.subarray(0,a.Wd),0));if(a.Sd.subarray&&b.subarray)a.Sd.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Sd[e+f]=b[c+f];a.Wd=Math.max(a.Wd,
e+d);return d},he(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Wd);if(0>b)throw new F(28);return b},Ff(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(43);a=a.node.Sd;if(e&2||!a||a.buffer!==m.buffer){d=!0;Da();e=void 0;if(!e)throw new F(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);m.set(a,e)}}else d=!1,e=a.byteOffset;return{Qg:e,tg:d}},Hf(a,b,c,d){G.Qd.write(a,b,0,d,c,!1);return 0}}},lb=(a,b)=>{var c=0;a&&(c|=
365);b&&(c|=146);return c},mb=[],nb=null,ob={},Ba=[],pb=1,I=null,za=!1,qb=!0,rb={},F=class{name="ErrnoError";constructor(a){this.ce=a}},sb=class{Xd={};node=null;get flags(){return this.Xd.flags}set flags(a){this.Xd.flags=a}get position(){return this.Xd.position}set position(a){this.Xd.position=a}},tb=class{Pd={};Qd={};Ge=null;constructor(a,b,c,d){a||=this;this.parent=a;this.oe=a.oe;this.id=pb++;this.name=b;this.mode=c;this.He=d;this.re=this.ae=this.Yd=Date.now()}get read(){return 365===(this.mode&
365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function ub(a,b={}){if(!a)throw new F(44);b.cf??(b.cf=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(l=>!!l);for(var d=nb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Ta(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Sa(e+"/"+a[f]);try{d=jb(d,a[f])}catch(l){if(44===l?.ce&&g&&b.lg)return{path:e};throw l;}!d.Ge||g&&!b.cf||(d=d.Ge.root);if(40960===(d.mode&61440)&&(!g||b.bf)){if(!d.Pd.Ie)throw new F(52);
d=d.Pd.Ie(d);"/"===d.charAt(0)||(d=Ta(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new F(32);}function vb(a){for(var b;;){if(a===a.parent)return a=a.oe.Gf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function wb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%I.length}function kb(a){var b=wb(a.parent.id,a.name);if(I[b]===a)I[b]=a.ye;else for(b=I[b];b;){if(b.ye===a){b.ye=a.ye;break}b=b.ye}}
function jb(a,b){var c=H(a.mode)?(c=xb(a,"x"))?c:a.Pd.Ee?0:2:54;if(c)throw new F(c);for(c=I[wb(a.id,b)];c;c=c.ye){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Pd.Ee(a,b)}function ib(a,b,c,d){a=new tb(a,b,c,d);b=wb(a.parent.id,a.name);a.ye=I[b];return I[b]=a}function H(a){return 16384===(a&61440)}function yb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function xb(a,b){if(qb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function zb(a,b){if(!H(a.mode))return 54;try{return jb(a,b),20}catch(c){}return xb(a,"wx")}function J(a){a=Ba[a];if(!a)throw new F(8);return a}function Ab(a,b=-1){a=Object.assign(new sb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Ba[b])break a;throw new F(33);}a.te=b;return Ba[b]=a}function Bb(a,b=-1){a=Ab(a,b);a.Qd?.Gg?.(a);return a}
function Cb(a,b){var c=null?.Qd.je,d=c?null:a;c??=a.Pd.je;if(!c)throw new F(63);c(d,b)}var hb={open(a){a.Qd=ob[a.node.He].Qd;a.Qd.open?.(a)},he(){throw new F(70);}};function db(a,b){ob[a]={Qd:b}}function Db(a,b){var c="/"===b;if(c&&nb)throw new F(10);if(!c&&b){var d=ub(b,{cf:!1});b=d.path;d=d.node;if(d.Ge)throw new F(10);if(!H(d.mode))throw new F(54);}b={type:a,Og:{},Gf:b,jg:[]};a=a.oe(b);a.oe=b;b.root=a;c?nb=a:d&&(d.Ge=b,d.oe&&d.oe.jg.push(b))}
function Eb(a,b,c){var d=ub(a,{parent:!0}).node;a=Ua(a);if(!a)throw new F(28);if("."===a||".."===a)throw new F(20);var e=zb(d,a);if(e)throw new F(e);if(!d.Pd.Re)throw new F(63);return d.Pd.Re(d,a,b,c)}function K(a){return Eb(a,16895,0)}function Fb(a,b,c){"undefined"==typeof c&&(c=b,b=438);Eb(a,b|8192,c)}function Gb(a,b){if(!Xa(a))throw new F(44);var c=ub(b,{parent:!0}).node;if(!c)throw new F(44);b=Ua(b);var d=zb(c,b);if(d)throw new F(d);if(!c.Pd.Te)throw new F(63);c.Pd.Te(c,b,a)}
function Hb(a,b,c=438){if(""===a)throw new F(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=ub(a,{bf:!(b&131072),lg:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new F(20);}else{if(e)throw new F(31);d=Eb(a,c|511,0);f=!0}if(!d)throw new F(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!H(d.mode))throw new F(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:H(d.mode)&&("r"!==yb(b)||b&576)?31:xb(d,yb(b)):44))throw new F(e);if(b&512&&!f){e=d;e="string"==typeof e?ub(e,{bf:!0}).node:e;if(H(e.mode))throw new F(31);if(32768!==(e.mode&61440))throw new F(28);var g=xb(e,"w");if(g)throw new F(g);Cb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Ab({node:d,path:vb(d),flags:b,seekable:!0,position:0,Qd:d.Qd,rg:[],error:!1});e.Qd.open&&e.Qd.open(e);f&&(c&=511,d="string"==typeof d?ub(d,{bf:!0}).node:d,Cb(d,{mode:c&4095|d.mode&-4096,
Yd:Date.now(),Fg:void 0}));!h.logReadFiles||b&1||a in rb||(rb[a]=1);return e}function Ca(a){if(null===a.te)throw new F(8);a.ef&&(a.ef=null);try{a.Qd.close&&a.Qd.close(a)}catch(b){throw b;}finally{Ba[a.te]=null}a.te=null}function Ib(a,b,c){if(null===a.te)throw new F(8);if(!a.seekable||!a.Qd.he)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.Qd.he(a,b,c);a.rg=[]}
function Jb(a,b,c,d,e){if(0>d||0>e)throw new F(28);if(null===a.te)throw new F(8);if(0===(a.flags&2097155))throw new F(8);if(H(a.node.mode))throw new F(31);if(!a.Qd.write)throw new F(28);a.seekable&&a.flags&1024&&Ib(a,0,2);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new F(70);b=a.Qd.write(a,b,c,d,e,void 0);f||(a.position+=b);return b}
function L(a,b,c){a=Sa("/dev/"+a);var d=lb(!!b,!!c);L.Ef??(L.Ef=64);var e=L.Ef++<<8|0;db(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,l,n){for(var p=0,z=0;z<n;z++){try{var y=b()}catch(C){throw new F(29);}if(void 0===y&&0===p)throw new F(6);if(null===y||void 0===y)break;p++;g[l+z]=y}p&&(f.node.re=Date.now());return p},write(f,g,l,n){for(var p=0;p<n;p++)try{c(g[l+p])}catch(z){throw new F(29);}n&&(f.node.ae=f.node.Yd=Date.now());return p}});Fb(a,d,e)}
var M={},Qa=void 0,O=0,Kb={},Lb=a=>{if(!(a instanceof Ja||"unwind"==a))throw a;},Mb=a=>{la=a;x||0<O||(h.onExit?.(a),ka=!0);throw new Ja(a);},Nb=()=>{if(!(sa||x||0<O))try{var a=la;la=a;x||0<O||va();Mb(a)}catch(b){Lb(b)}},Ob=a=>{if(!sa&&!ka)try{a(),Nb()}catch(b){Lb(b)}},Pb=[],Qb=(a,b)=>{Pb.length=0;for(var c;c=q[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Pb.push(112==c?t[b>>2]:106==c?w[b>>3]:105==c?r[b>>2]:v[b>>3]);b+=d?8:4}return Pb},Sb=(a,b,c)=>{b=Qb(b,c);return Rb[a](...b)},bc=(a,b)=>{Tb=a;Ub=b;
if(!Vb)return 1;Wb||(O+=1,Wb=!0);if(0==a)Xb=function(){setTimeout(Yb,Math.max(0,Zb+b-performance.now())|0)};else if(1==a)Xb=function(){$b(Yb)};else if(2==a){if(!ac)if(globalThis.setImmediate)ac=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);ac=d=>{c.push(d);postMessage("setimmediate","*")}}Xb=function(){ac(Yb)}}return 0},kc=(a,b,c,d,e)=>{function f(){return g<cc?(--O,Nb(),!1):!0}Vb=a;dc=d;var g=
cc;Wb=!1;Yb=function(){if(!ka)if(0<ec.length){var l=ec.shift();l.Ig(l.ug);if(fc){var n=fc,p=0==n%1?n-1:Math.floor(n);fc=l.Cg?p:(8*n+(p+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=fc??0,p=gc.Hg??0,n?n<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(Yb,0)}else if(f())if(hc=hc+1|0,1==Tb&&1<Ub&&0!=hc%Ub)Xb();else{0==Tb&&(Zb=performance.now());a:if(!ka){for(l of ic)if(!1===l())break a;Ob(a);for(n of jc)n()}f()&&Xb()}};e||(0<
b?bc(0,1E3/b):bc(1,1),Xb());if(c)throw"unwind";},Wb=!1,Xb=null,cc=0,Vb=null,dc=0,Tb=0,Ub=0,hc=0,ec=[],ic=[],jc=[];function lc(){Xb=null;cc++}var mc=0;function $b(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===mc)mc=b+1E3/60;else for(;b+2>=mc;)mc+=1E3/60;setTimeout(a,Math.max(mc-b,0))}}var gc={},Zb,Yb,ac,fc,ya=[];function nc(a){var b=P.$d[a];b.target.removeEventListener(b.Zd,b.Cf,b.ke);P.$d.splice(a,1)}
function oc(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of P.se)if(e.pf==a&&d(e.yf,c))return;P.se.push({pf:a,If:b,yf:c});P.se.sort((f,g)=>f.If<g.If)}function pc(a){P.se=P.se.filter(b=>b.pf!=a)}function qc(){return navigator.userActivation?navigator.userActivation.isActive:P.ff&&P.Rf.Nf}function rc(){if(qc()){var a=P.se;P.se=[];for(var b of a)b.pf(...b.yf)}}
function Q(a){if(!a.target)return-4;if(a.be)a.Cf=function(c){++P.ff;P.Rf=a;rc();a.ne(c);rc();--P.ff},a.target.addEventListener(a.Zd,a.Cf,a.ke),P.$d.push(a),P.pg||(ya.push(P.ng),P.pg=!0);else for(var b=0;b<P.$d.length;++b)P.$d[b].target==a.target&&P.$d[b].Zd==a.Zd&&nc(b--);return 0}function sc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={vg:0,Jg:0,gf:0,Mg:0,uf:0,rf:0,af:0,Eg:0,jf:0,Dg:0,df:0,kf:0,tf:0,Vg:0,ng(){for(;P.$d.length;)nc(P.$d.length-1);P.se=[]},ff:0,se:[],$d:[],og:(a,b)=>{for(var c=0;c<P.$d.length;++c)P.$d[c].target!=a||b&&b!=P.$d[c].Zd||nc(c--)},Rg(a){var b,c;for([b,c]of P.$d.entries())if(c.target===a.target&&c.fe===a.fe&&c.be===a.be&&c.le===a.le)return nc(b),0;return-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},tc=[0,document,window],R=a=>{a=2<a?a?D(q,a):"":a;return tc[a]||
document.querySelector(a)},vc=a=>{var b=$a(a)+1,c=uc(b);E(a,q,c,b);return c},yc=a=>{var b=wc(),c=uc(8),d=c+4;a=vc(a.id);if(a=R(a))r[c>>2]=a.width,r[d>>2]=a.height;c=[r[c>>2],r[d>>2]];xc(b);return c},zc=(a,b,c)=>{a=R(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ac=(a,b,c)=>{if(a.Bg){var d=wc();a=vc(a.id);zc(a,b,c);xc(d)}else a.width=b,a.height=c},Bc={},Dc=a=>{function b(){Cc()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Ac(a,d,e),
a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=z,a.style.paddingTop=y,a.style.paddingBottom=C,a.style.marginLeft=N,a.style.marginRight=ha,a.style.marginTop=ia,a.style.marginBottom=ma,document.body.style.margin=ab,document.documentElement.style.overflow=Ea,document.body.scroll=Kd,a.style.ue=Ld,a.ze&&a.ze.we.viewport(0,0,d,e),Bc.Ke&&A(Bc.Ke)(37,0,Bc.zf))}var c=
yc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,z=a.style.paddingRight,y=a.style.paddingTop,C=a.style.paddingBottom,N=a.style.marginLeft,ha=a.style.marginRight,ia=a.style.marginTop,ma=a.style.marginBottom,ab=document.body.style.margin,Ea=document.documentElement.style.overflow,Kd=document.body.scroll,Ld=a.style.ue;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},Ec=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Fc=a=>0>tc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Gc=(a,b)=>{if(0!=b.nf||0!=b.Ve){Dc(a);var c=b.qg?innerWidth:screen.width,d=b.qg?innerHeight:screen.height,e=Fc(a),f=e.width;e=e.height;var g=yc(a),l=g[0];g=g[1];3==b.nf?(Ec(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.nf&&(c*g<l*d?(f=g*c/l,Ec(a,(d-f)/2,0),d=f):(f=l*d/g,Ec(a,0,(c-f)/2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let p;(p=document.body.style).backgroundColor||(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.$f&&(a.style.ue="optimizeSpeed",a.style.ue="-moz-crisp-edges",a.style.ue="-o-crisp-edges",a.style.ue="-webkit-optimize-contrast",a.style.ue="optimize-contrast",a.style.ue="crisp-edges",a.style.ue="pixelated");n=2==b.Ve?devicePixelRatio:1;0!=b.Ve&&(c=c*n|0,d=d*n|0,Ac(a,c,d),a.ze&&a.ze.we.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return P.fullscreenEnabled()?-3:-1;Bc=b;b.Ke&&A(b.Ke)(37,0,b.zf);return 0},Hc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0};function Cc(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}var Ic=a=>{O+=1;setTimeout(()=>{--O;Ob(a)},1E4)},Jc=!1,Kc=[];
function Lc(){function a(){Jc=document.pointerLockElement===h.canvas}if(!Mc){Mc=!0;mb.push({canHandle:function(c){return!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:async function(c,d){var e=new Blob([c],{type:Nc(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Nc(d)}));var f=URL.createObjectURL(e);return new Promise((g,l)=>{var n=new Image;n.onload=()=>{var p=document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,
0,0);URL.revokeObjectURL(f);g(c)};n.onerror=()=>{k(`Image ${f} could not be decoded`);l()};n.src=f})}});mb.push({canHandle:function(c){return!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:async function(c,d){return new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,l=URL.createObjectURL(new Blob([c],{type:Nc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",z=0,y=0,C=0;C<c.length;C++)for(z=z<<8|c[C],y+=8;6<=y;){var N=z>>y-6&63;y-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[N]}2==y?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(z&3)<<4],p+="=="):4==y&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(z&15)<<2],p+="=");n.src="data:audio/x-"+d.slice(-3)+";base64,"+p;f(n)}};n.src=l;Ic(()=>{f(n)})})}});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,
!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Jc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Oc(a){a=a.getContext("2d");if(!a)return null;h.ctx=a;Kc.forEach(b=>b());Lc();return a}function Nc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var Mc,S,Pc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Qc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},
Rc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Sc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Tc=1,Uc=[],T=[],Vc=[],Wc=[],Xc=[],U=[],Yc=[],Zc=[],V=[],$c={},ad=4,bd=0,cd=a=>{for(var b=Tc++,c=a.length;c<b;c++)a[c]=null;return b},dd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=S[c](),g=f&&cd(d);f?(f.name=g,d[g]=f):W||=1282;r[b+4*e>>2]=g}},fd=(a,b)=>{a.xf||(a.xf=a.getContext,a.getContext=function(d,e){e=a.xf(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?ed(c,b):0},ed=(a,b)=>{var c=
cd(Zc),d={handle:c,attributes:b,version:b.ig,we:a};a.canvas&&(a.canvas.ze=d);Zc[c]=d;if("undefined"==typeof b.Bf||b.Bf)if((a=d)||(a=gd),!a.cg){a.cg=!0;a=a.we;a.Ng=a.getExtension("WEBGL_multi_draw");a.Zf=a.getExtension("EXT_polygon_offset_clamp");a.Yf=a.getExtension("EXT_clip_control");a.sg=a.getExtension("WEBGL_polygon_mode");Pc(a);Qc(a);Rc(a);a.me=a.getExtension("EXT_disjoint_timer_query");for(var e of Sc(a))e.includes("lose_context")||e.includes("debug")||a.getExtension(e)}return c},W,gd,hd=[],
jd=(a,b,c,d,e,f,g,l)=>{b=T[b];if(a=S[a](b,c))d=l&&E(a.name,q,l,d),e&&(r[e>>2]=d),f&&(r[f>>2]=a.size),g&&(r[g>>2]=a.type)},kd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(W||=1280);return;case 36345:d=0;break;case 34466:var e=S.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=S.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":W||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=
0;break;default:W||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+4*a>>2]=e[a];break;case 2:u[b+4*a>>2]=e[a];break;case 4:m[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){W||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:W||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;t[b>>2]=c;t[b+4>>2]=(c-t[b>>2])/4294967296;break;case 0:r[b>>2]=d;break;case 2:u[b>>2]=d;break;case 4:m[b]=d?1:0}}else W||=1281},ld=(a,b,c)=>{if(c){a=S.me.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d;t[c+4>>2]=(d-t[c>>2])/4294967296}else W||=1281},md=(a,b,c)=>{if(c){a=S.me.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;r[c>>2]=d}else W||=1281},nd=a=>{var b=$a(a)+1,c=X(b);c&&E(a,q,c,b);return c},od=()=>{var a=Sc(S);return a=
a.concat(a.map(b=>"GL_"+b))},pd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),qd=a=>{var b=a.Je,c=a.Lf,d;if(!b){a.Je=b={};a.Kf={};var e=S.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=S.getActiveUniform(a,d);var g=f.name;f=f.size;var l=pd(g);l=0<l?g.slice(0,l):g;var n=a.sf;a.sf+=f;c[l]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Kf[n++]=l}}},Y=a=>{var b=S.Sf;if(b){var c=b.Je[a];"number"==typeof c&&(b.Je[a]=c=S.getUniformLocation(b,b.Kf[a]+(0<c?`[${c}]`:"")));return c}W||=1282},rd=(a,b,c,d)=>{if(c)if(a=T[a],qd(a),
a=S.getUniform(a,Y(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:u[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:u[c+4*b>>2]=a[b]}else W||=1281},sd=(a,b,c,d)=>{if(c)if(a=S.getVertexAttrib(a,b),34975==b)r[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:u[c>>2]=a;break;case 5:r[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:u[c+
4*b>>2]=a[b];break;case 5:r[c+4*b>>2]=Math.fround(a[b])}else W||=1281},td=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?r:6==a?u:5==a||28922==a?t:qa;b=d*((bd||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ad-1&-ad);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},ud=[],vd=[],wd=(a,b)=>{if(!P.fullscreenEnabled())return-1;a=R(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?qc()?Gc(a,b):b.Vf?(oc(Gc,1,[a,b]),1):-2:-3:-4},xd=(a,b)=>
{var c={target:R(2),Zd:"beforeunload",fe:28,le:a,be:b,ne:(d=event)=>{var e=A(b)(28,0,a);e&&=e?D(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},ke:!0};return Q(c)},yd=(a,b,c,d,e,f)=>{P.af||(P.af=X(256));a={target:R(a),Zd:f,fe:e,le:b,be:d,ne:(g=event)=>{var l=g.target.id?g.target.id:"",n=P.af;E(sc(g.target),q,n+0,128);E(l,q,n+128,128);A(d)(e,n,b)&&g.preventDefault()},ke:c};return Q(a)},zd=(a,b,c,d,e)=>{P.df||(P.df=X(276));return Q({target:a,Zd:e,fe:19,le:b,be:d,ne:(f=event)=>{var g=P.df,l=
Cc(),n=!!l;m[g]=n;m[g+1]=P.fullscreenEnabled();var p=n?l:P.mg,z=p?.id||"";E(sc(p),q,g+2,128);E(z,q,g+130,128);r[g+260>>2]=p?p.clientWidth:0;r[g+264>>2]=p?p.clientHeight:0;r[g+268>>2]=screen.width;r[g+272>>2]=screen.height;n&&(P.mg=l);A(d)(19,g,b)&&f.preventDefault()},ke:c})},Ad=(a,b,c,d,e,f)=>{P.gf||(P.gf=X(160));a={target:R(a),Zd:f,fe:e,le:b,be:d,ne:g=>{var l=P.gf;v[l>>3]=g.timeStamp;var n=l>>2;r[n+2]=g.location;m[l+12]=g.ctrlKey;m[l+13]=g.shiftKey;m[l+14]=g.altKey;m[l+15]=g.metaKey;m[l+16]=g.repeat;
r[n+5]=g.charCode;r[n+6]=g.keyCode;r[n+7]=g.which;E(g.key||"",q,l+32,32);E(g.code||"",q,l+64,32);E(g.char||"",q,l+96,32);E(g.locale||"",q,l+128,32);A(d)(e,l,b)&&g.preventDefault()},ke:c};return Q(a)},Bd=(a,b,c)=>{var d=screen.orientation;P.jf||(P.jf=X(8));return Q({target:d,Zd:"change",fe:18,le:a,be:c,ne:(e=event)=>{var f=P.jf,g=["portrait-primary","portrait-secondary","landscape-primary","landscape-secondary"],l=["portrait","portrait","landscape","landscape"],n=0;var p=window.screen?screen.orientation||
screen.mozOrientation||screen.webkitOrientation:void 0;"object"===typeof p?(n=g.indexOf(p.type),0>n&&(n=l.indexOf(p.type)),0<=n&&(n=1<<n),g=p.angle):g=window.orientation;r[f>>2]=n;r[f+4>>2]=g;A(c)(18,f,a)&&e.preventDefault()},ke:b})},Cd=(a,b,c,d)=>{P.kf||(P.kf=X(257));return Q({target:a,Zd:"pointerlockchange",fe:20,le:b,be:d,ne:(e=event)=>{var f=P.kf,g=document.pointerLockElement;m[f]=!!g;var l=g?.id||"";E(sc(g),q,f+1,128);E(l,q,f+129,128);A(d)(20,f,b)&&e.preventDefault()},ke:c})},Dd=(a,b,c,d)=>{P.rf||
(P.rf=X(36));a=R(a);return Q({target:a,Zd:"resize",fe:10,le:b,be:d,ne:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=P.rf;r[g>>2]=0;r[g+4>>2]=f.clientWidth;r[g+8>>2]=f.clientHeight;r[g+12>>2]=innerWidth;r[g+16>>2]=innerHeight;r[g+20>>2]=outerWidth;r[g+24>>2]=outerHeight;r[g+28>>2]=pageXOffset|0;r[g+32>>2]=pageYOffset|0;A(d)(10,g,b)&&e.preventDefault()}}},ke:c})},Ed=(a,b,c)=>{var d=tc[1];P.tf||(P.tf=X(8));return Q({target:d,Zd:"visibilitychange",fe:21,le:a,be:c,ne:(e=event)=>{var f=P.tf,
g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);m[f]=document.hidden;r[f+4>>2]=g;A(c)(21,f,a)&&e.preventDefault()},ke:b})},Fd=(a,b,c,d)=>{P.uf||(P.uf=X(96));return Q({target:a,Nf:!0,Zd:"wheel",fe:9,le:b,be:d,ne:(e=event)=>{var f=P.uf;v[f>>3]=e.timeStamp;var g=f>>2;r[g+2]=e.screenX;r[g+3]=e.screenY;r[g+4]=e.clientX;r[g+5]=e.clientY;m[f+24]=e.ctrlKey;m[f+25]=e.shiftKey;m[f+26]=e.altKey;m[f+27]=e.metaKey;pa[2*g+14]=e.button;pa[2*g+15]=e.buttons;r[g+8]=e.movementX;r[g+
9]=e.movementY;var l=Fc(a);r[g+10]=e.clientX-(l.left|0);r[g+11]=e.clientY-(l.top|0);v[f+64>>3]=e.deltaX;v[f+72>>3]=e.deltaY;v[f+80>>3]=e.deltaZ;r[f+88>>2]=e.deltaMode;A(d)(9,f,b)&&e.preventDefault()},ke:c})},Gd=["default","low-power","high-performance"],Hd={},Jd=()=>{if(!Id){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Hd)void 0===Hd[b]?delete a[b]:
a[b]=Hd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Id=c}return Id},Id,Md=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{"suspended"===a.state&&a.resume()},{once:!0})},Nd=(a,b=[])=>{A(a)(...b)},Od=(a,b,c,d)=>{var e={string:p=>{var z=0;null!==p&&void 0!==p&&0!==p&&(z=vc(p));return z},array:p=>{var z=uc(p.length);m.set(p,z);return z}};a=h["_"+a];var f=[],g=0;if(d)for(var l=0;l<d.length;l++){var n=e[c[l]];n?(0===
g&&(g=wc()),f[l]=n(d[l])):f[l]=d[l]}c=a(...f);return c=function(p){0!==g&&xc(g);return"string"===b?p?D(q,p):"":"boolean"===b?!!p:p}(c)};I=Array(4096);Db(G,"/");K("/tmp");K("/home");K("/home/web_user");(function(){K("/dev");db(259,{read:()=>0,write:(d,e,f,g)=>g,he:()=>0});Fb("/dev/null",259);cb(1280,fb);cb(1536,gb);Fb("/dev/tty",1280);Fb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Wa(a),b=a.byteLength);return a[--b]};L("random",c);L("urandom",c);K("/dev/shm");K("/dev/shm/tmp")})();
(function(){K("/proc");var a=K("/proc/self");K("/proc/self/fd");Db({oe(){var b=ib(a,"fd",16895,73);b.Qd={he:G.Qd.he};b.Pd={Ee(c,d){c=+d;var e=J(c);c={parent:null,oe:{Gf:"fake"},Pd:{Ie:()=>e.path},id:c+1};return c.parent=c},mf(){return Array.from(Ba.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.requestAnimationFrame=$b;h.pauseMainLoop=lc;h.resumeMainLoop=function(){cc++;var a=Tb,b=Ub,c=Vb;Vb=null;kc(c,0,!1,dc,!0);bc(a,b);Xb()};h.preMainLoop&&ic.push(h.preMainLoop);
h.postMainLoop&&jc.push(h.postMainLoop);for(let a=0;32>a;++a)hd.push(Array(a));for(var Pd=new Float32Array(288),Z=0;288>=Z;++Z)ud[Z]=Pd.subarray(0,Z);var Qd=new Int32Array(288);for(Z=0;288>=Z;++Z)vd[Z]=Qd.subarray(0,Z);h.noExitRuntime&&(x=h.noExitRuntime);h.preloadPlugins&&(mb=h.preloadPlugins);h.print&&(fa=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(ja=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.ccall=Od;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>Od(a,b,c,f,d)};h.writeArrayToMemory=(a,b)=>{m.set(a,b)};
var Rb={74576:a=>{a=(a?D(q,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return 1===a.length?a.charCodeAt(0):-1},74791:()=>{"undefined"===typeof h.SDL3&&(h.SDL3={});h.SDL3.Ce={};h.SDL3.Ce.ve=[];h.SDL3.Ce.ve[0]=void 0;h.SDL3.Ce.ve[1]=void 0},75037:(a,b,c,d,e)=>{var f=h.SDL3.Ce;void 0!==f.ve[a]&&clearInterval(f.ve[a]);f.ve[a]=setInterval(function(){Nd(d,[e])},b/c*1E3)},75229:a=>{var b=h.SDL3.Ce;void 0!==b.ve[a]&&clearInterval(b.ve[a]);b.ve[a]=void 0},
75360:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,75507:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,75741:()=>{"undefined"===typeof h.SDL3&&(h.SDL3={});var a=h.SDL3;a.Ud={};a.Rd={};a.Vd||("undefined"!==typeof AudioContext?a.Vd=new AudioContext:"undefined"!==typeof webkitAudioContext&&(a.Vd=new webkitAudioContext),a.Vd&&"undefined"===typeof navigator.userActivation&&
Md(a.Vd));return void 0!==a.Vd},76282:()=>h.SDL3.Vd.sampleRate,76333:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.Rd.ee&&(clearInterval(g.Rd.ee),g.Rd.ee=void 0,g.Rd.xe=void 0);g.Rd.hf=g.Vd.createMediaStreamSource(l);g.Rd.de=g.Vd.createScriptProcessor(b,a,1);g.Rd.de.onaudioprocess=function(n){void 0!==g&&void 0!==g.Rd&&(n.outputBuffer.getChannelData(0).fill(0),g.Rd.We=n.inputBuffer,Nd(c,[d]))};g.Rd.hf.connect(g.Rd.de);g.Rd.de.connect(g.Vd.destination);g.Rd.stream=l}var g=h.SDL3;g.Rd.xe=g.Vd.createBuffer(a,
b,g.Vd.sampleRate);g.Rd.xe.getChannelData(0).fill(0);g.Rd.ee=setInterval(function(){g.Rd.We=g.Rd.xe;Nd(c,[d])},b/g.Vd.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},78174:(a,b,c,d)=>{var e=h.SDL3;e.Ud.de=e.Vd.createScriptProcessor(b,0,a);e.Ud.de.onaudioprocess=function(f){void 0!==e&&void 0!==
e.Ud&&(void 0!==e.Ud.ee&&(clearInterval(e.Ud.ee),e.Ud.ee=void 0,e.Ud.xe=void 0),e.Ud.Le=f.outputBuffer,Nd(c,[d]))};e.Ud.de.connect(e.Vd.destination);"suspended"===e.Vd.state&&(e.Ud.xe=e.Vd.createBuffer(a,b,e.Vd.sampleRate),e.Ud.xe.getChannelData(0).fill(0),e.Ud.ee=setInterval(function(){"undefined"!==typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.Vd.resume();e.Ud.Le=e.Ud.xe;Nd(c,[d]);e.Ud.Le=void 0},b/e.Vd.sampleRate*1E3))},79490:a=>{var b=h.SDL3;if(a){void 0!==b.Rd.ee&&
clearInterval(b.Rd.ee);if(void 0!==b.Rd.stream){a=b.Rd.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.Rd.stream.removeTrack(a[c])}void 0!==b.Rd.de&&(b.Rd.de.onaudioprocess=function(){},b.Rd.de.disconnect());void 0!==b.Rd.hf&&b.Rd.hf.disconnect();b.Rd=void 0}else void 0!=b.Ud.de&&b.Ud.de.disconnect(),void 0!==b.Ud.ee&&clearInterval(b.Ud.ee),b.Ud=void 0;void 0!==b.Vd&&void 0===b.Ud&&void 0===b.Rd&&(b.Vd.close(),b.Vd=void 0)},80646:(a,b)=>{a>>>=2;for(var c=h.SDL3,d=c.Ud.Le.numberOfChannels,e=0;e<
d;++e){var f=c.Ud.Le.getChannelData(e);if(f.length!=b)throw"Web Audio playback buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=u[a+(g*d+e)]}},81161:(a,b)=>{for(var c=h.SDL3,d=c.Rd.We.numberOfChannels,e=0;e<d;++e){var f=c.Rd.We.getChannelData(e);if(f.length!=b)throw"Web Audio recording buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Na(a+4*g,f[g]);else for(g=0;g<
b;++g)Na(a+4*(g*d+e),f[g])}},81788:()=>window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?0:window.matchMedia("(prefers-color-scheme: dark)").matches?1:-1:-1,81997:()=>{if("undefined"!==typeof h.SDL3){var a=h.SDL3;a.qf.removeEventListener("change",a.$e);a.qf=void 0;a.$e=void 0}},82250:()=>window.innerWidth,82280:()=>window.innerHeight,82311:()=>window.innerWidth,82341:()=>window.innerHeight,82372:a=>{a=document.querySelector(a?D(q,a):"");var b=document.createElement("div");
b.id="SDL3_fill_document_background_elements";b.qe=a;b.wf=a.parentNode;b.vf=a.nextSibling;var c=Array.from(document.body.children),d;for(d of c)b.appendChild(d);document.body.appendChild(b);b.style.display="none";document.body.appendChild(a);a.style.position="fixed";a.style.top="0";a.style.left="0"},82923:a=>{h.requestFullscreen=function(){Rd(a)}},83032:()=>{h.requestFullscreen=function(){};var a=document.getElementById("SDL3_fill_document_background_elements");if(a){for(a.vf?a.wf.insertBefore(a.qe,
a.vf):a.wf.appendChild(a.qe);a.firstChild;)document.body.insertBefore(a.firstChild,a);a.qe.style.position=void 0;a.qe.style.top=void 0;a.qe.style.left=void 0;a.remove()}},83583:()=>{if(window.matchMedia){"undefined"===typeof h.SDL3&&(h.SDL3={});var a=h.SDL3;a.$e=function(){Sd()};a.qf=window.matchMedia("(prefers-color-scheme: dark)");a.qf.addEventListener("change",a.$e)}},83974:(a,b,c,d,e)=>{a=a?D(q,a):"";b=b?D(q,b):"";c=c?D(q,c):"";d=d?D(q,d):"";var f=e?D(q,e):"";e=document.createElement("dialog");
e.classList.add("SDL3_messagebox");e.id=f;e.style.color=d;e.style.backgroundColor=c;document.body.append(e);d=document.createElement("h1");d.innerText=a;e.append(d);a=document.createElement("p");a.innerText=b;e.append(a);e.showModal()},84515:(a,b,c,d,e,f,g,l)=>{a=a?D(q,a):"";b=b?D(q,b):"";f=f?D(q,f):"";var n=g?D(q,g):"",p=l?D(q,l):"",z=document.getElementById(a);if(!z)return!1;var y=document.createElement("button");y.innerText=b;y.style.borderColor=f;y.style.backgroundColor=n;z.addEventListener("keydown",
function(C){d&&"Enter"===C.key?(C.preventDefault(),y.click()):e&&"Escape"===C.key&&(C.preventDefault(),y.click())});z.addEventListener("cancel",function(C){C.preventDefault()});y.onmouseenter=function(){y.style.backgroundColor=p};y.onmouseleave=function(){y.style.backgroundColor=n};y.onclick=function(){z.close(c)};z.append(y);return!0},85524:a=>{a=a?D(q,a):"";return(a=document.getElementById(a))?a.open:!1},85662:a=>{a=a?D(q,a):"";a=document.getElementById(a);if(!a)return 0;try{return parseInt(a.returnValue)}catch(b){return 0}},
85844:(a,b)=>{alert((a?D(q,a):"")+"\n\n"+(b?D(q,b):""))},85901:(a,b,c,d)=>{d=d?D(q,d):"";var e=document.querySelector(d);h.SDL3||(h.SDL3={});d=h.SDL3;if(d.Qf!==e){d.Be=Oc(e);if(!d.Be)return!1;d.Qf=e}if(d.w!==a||d.h!==b||d.bg!==d.Be)d.image=d.Be.createImageData(a,b),d.w=a,d.h=b,d.bg=d.Be;a=d.image.data;c/=4;d.Uf!==a&&(d.Tf=new Int32Array(a.buffer),d.Uf=a);a=d.Tf;a.set(r.subarray(c,c+a.length));d.Be.putImageData(d.image,0,0);return!0},86692:()=>{h.SDL3||(h.SDL3={});var a=h.SDL3;a.mouse_x=0;a.mouse_y=
0;a.mouse_buttons=[];for(var b=0;5>b;++b)a.mouse_buttons[b]=!1;document.addEventListener("mousemove",function(c){var d=h.SDL3;d.mouse_x=c.clientX;d.mouse_y=c.clientY});document.addEventListener("mousedown",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!0)});document.addEventListener("mouseup",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!1)})},87426:(a,b,c,d,e)=>{var f=document.createElement("canvas");
f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);e/=4;b=new Int32Array(a.data.buffer);b.set(r.subarray(e,e+b.length));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=Td(c.length+1);E(c,q,d,c.length+1);return d},88084:a=>{h.canvas&&(h.canvas.style.cursor=a?D(q,a):"")},88167:()=>{h.canvas&&(h.canvas.style.cursor="none")},88236:()=>h.SDL3.mouse_x,88274:()=>h.SDL3.mouse_y,88312:a=>h.SDL3.mouse_buttons[a],88360:a=>{document.qe=
function(b){"CapsLock"!=b.key&&"NumLock"!=b.key&&"ScrollLock"!=b.key&&Ud(a,b.getModifierState("CapsLock"),b.getModifierState("NumLock"),b.getModifierState("ScrollLock"))};document.addEventListener("keydown",document.qe)},88759:()=>{document.removeEventListener("keydown",document.qe)},88843:a=>{var b=document;b&&(b.Xd=function(c){c=h.SDL3.Fe(0,0,c);0!=c&&(Vd(a,c),Wd(c))},b.addEventListener("pointerup",b.Xd))},89186:a=>{"undefined"===typeof h.SDL3&&(h.SDL3={});var b=h.SDL3;void 0===b.Fe&&(b.Fe=function(c,
d,e){if("mouse"==e.pointerType)var f=1;else if("touch"==e.pointerType)f=2;else if("pen"==e.pointerType)f=3;else return 0;var g=Td(a);if(0!=g){var l=g>>2;r[l++]=f;r[l++]=e.pointerId;r[l++]="undefined"!==typeof e.button?e.button:-1;r[l++]=e.buttons;u[l++]=e.movementX;u[l++]=e.movementY;u[l++]=e.clientX-c;u[l++]=e.clientY-d;3==f&&(u[l++]=e.pressure,u[l++]=e.Tg,u[l++]=e.tiltX,u[l++]=e.tiltY,u[l++]=e.Wg)}return g})},90173:a=>{a=a?D(q,a):"";try{var b=document.querySelector(a);if(b)return b===document.activeElement}catch(c){}return!1},
90339:()=>document.hasFocus(),90371:()=>{var a=document;a&&(a.removeEventListener("pointerup",a.Xd),a.Xd=void 0)},90553:()=>document.body.clientWidth,90591:()=>document.body.clientHeight,90630:()=>window.innerWidth,90660:()=>window.innerHeight,90691:()=>window.outerWidth,90721:()=>window.outerHeight,90752:()=>window.pageXOffset,90783:()=>window.pageYOffset,90814:(a,b)=>{var c=document.querySelector(b?D(q,b):"");if(c){var d=h.SDL3;c.Ue=function(e){var f=c.getBoundingClientRect();e=d.Fe(f.left,f.top,
e);0!=e&&(Xd(a,e),Wd(e))};c.Ae=function(e){var f=c.getBoundingClientRect();e=d.Fe(f.left,f.top,e);0!=e&&(Yd(a,e),Wd(e))};c.Xd=function(e){var f=c.getBoundingClientRect();e=d.Fe(f.left,f.top,e);0!=e&&(Zd(a,e),Wd(e))};c.style.touchAction="none";c.addEventListener("pointerenter",c.Ue);c.addEventListener("pointerleave",c.Ae);c.addEventListener("pointercancel",c.Ae);c.addEventListener("pointerdown",c.Xd);c.addEventListener("pointermove",c.Xd);c.addEventListener("pointerup",c.Xd)}},92148:(a,b,c)=>{var d=
document.querySelector(b?D(q,b):"");if(d){"undefined"===typeof h.SDL3&&(h.SDL3={});var e=h.SDL3,f=function(g){var l=Td(c);if(0!=l){var n=l>>2,p=d.getBoundingClientRect();r[n++]=g.clientX-p.left;r[n++]=g.clientY-p.top}return l};e.Ye=function(g){g.preventDefault();g=f(g);0!=g&&($d(a,g),Wd(g))};d.addEventListener("dragover",e.Ye);e.Me=0;K("/tmp/filedrop");e.Ze=function(g){g.preventDefault();if(g.dataTransfer.types.includes("text/plain"))g=nd(g.dataTransfer.getData("text/plain")),ae(a,g),be(g);else if(g.dataTransfer.types.includes("Files")){let l=
0;const n=g.dataTransfer.files.length;for(let p=0;p<n;p++){const z=g.dataTransfer.files.item(p),y=new FileReader;y.readAsArrayBuffer(z);y.onload=function(C){var N=`/tmp/filedrop/${e.Me}`;e.Me+=1;const ha=`${N}/${z.name}`,ia=nd(ha);C=new Uint8Array(C.target.result);K(N);N=Hb(ha,"w");Jb(N,C,0,C.length,0);Ca(N);ce(a,ia);be(ia);++l;l===n&&de(a)};y.onerror=function(){++l;l===n&&de(a)}}}de(a)};d.addEventListener("drop",e.Ze);e.De=function(g){g.preventDefault();de(a)};d.addEventListener("dragend",e.De);
d.addEventListener("dragleave",e.De)}},94507:a=>{if(a=document.querySelector(a?D(q,a):"")){var b=h.SDL3;a.removeEventListener("dragleave",b.De);a.removeEventListener("dragend",b.De);a.removeEventListener("drop",b.Ze);b.Me=void 0;"/tmp/filedrop";var c=ub("/tmp/filedrop",{parent:!0}).node,d=Ua("/tmp/filedrop"),e=jb(c,d);a:{try{var f=jb(c,d)}catch(l){f=l.ce;break a}var g=xb(c,"wx");f=g?g:H(f.mode)?f===f.parent||"/"===vb(f)?10:0:54}if(f)throw new F(f);if(!c.Pd.Se)throw new F(63);if(e.Ge)throw new F(10);
c.Pd.Se(c,d);kb(e);a.removeEventListener("dragover",b.Ye);b.Ye=void 0;b.Ze=void 0;b.De=void 0}},95337:a=>{if(a=document.querySelector(a?D(q,a):""))a.removeEventListener("pointerenter",a.Ue),a.removeEventListener("pointerleave",a.Ae),a.removeEventListener("pointercancel",a.Ae),a.removeEventListener("pointerdown",a.Xd),a.removeEventListener("pointermove",a.Xd),a.removeEventListener("pointerup",a.Xd),a.style.touchAction="",a.Ue=void 0,a.Ae=void 0,a.Xd=void 0}},ee,Wd,Td,Aa,X,be,Xd,Yd,Zd,Vd,$d,de,ae,ce,
Ud,Sd,Rd,wa,fe,xc,uc,wc,ua,Pa,ge={Ra:(a,b)=>A(a)(b),u:function(a,b,c){Qa=c;try{var d=J(a);switch(b){case 0:var e=B();if(0>e)break;for(;Ba[e];)e++;return Bb(d,e).te;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=B(),d.flags|=e,0;case 12:return e=B(),pa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.ce}},ab:function(a){try{return J(a),0}catch(b){if("undefined"==typeof M||"ErrnoError"!==b.name)throw b;return-b.ce}},
Xa:function(a,b){try{var c=J(a),d=c.node,e=c.Qd.ge;a=e?c:d;e??=d.Pd.ge;if(!e)throw new F(63);var f=e(a);t[b>>2]=f.Wf;t[b+4>>2]=f.mode;t[b+8>>2]=f.kg;t[b+12>>2]=f.uid;t[b+16>>2]=f.ag;t[b+20>>2]=f.He;w[b+24>>3]=BigInt(f.size);r[b+32>>2]=4096;r[b+36>>2]=f.Pf;var g=f.re.getTime(),l=f.ae.getTime(),n=f.Yd.getTime();w[b+40>>3]=BigInt(Math.floor(g/1E3));t[b+48>>2]=g%1E3*1E6;w[b+56>>3]=BigInt(Math.floor(l/1E3));t[b+64>>2]=l%1E3*1E6;w[b+72>>3]=BigInt(Math.floor(n/1E3));t[b+80>>2]=n%1E3*1E6;w[b+88>>3]=BigInt(f.dg);
return 0}catch(p){if("undefined"==typeof M||"ErrnoError"!==p.name)throw p;return-p.ce}},_a:function(a,b,c){Qa=c;try{var d=J(a);switch(b){case 21509:return d.Td?0:-59;case 21505:if(!d.Td)return-59;if(d.Td.pe.fg){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=B();r[e>>2]=25856;r[e+4>>2]=5;r[e+8>>2]=191;r[e+12>>2]=35387;for(var f=0;32>f;f++)m[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Td?0:-59;case 21506:case 21507:case 21508:if(!d.Td)return-59;
if(d.Td.pe.gg)for(e=B(),a=[],f=0;32>f;f++)a.push(m[e+f+17]);return 0;case 21519:if(!d.Td)return-59;e=B();return r[e>>2]=0;case 21520:return d.Td?-28:-59;case 21537:case 21531:e=B();if(!d.Qd.eg)throw new F(59);return d.Qd.eg(d,b,e);case 21523:if(!d.Td)return-59;d.Td.pe.hg&&(f=[24,80],e=B(),pa[e>>1]=f[0],pa[e+2>>1]=f[1]);return 0;case 21524:return d.Td?0:-59;case 21515:return d.Td?0:-59;default:return-28}}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return-g.ce}},$a:function(a,b,
c,d){Qa=d;try{b=b?D(q,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":J(a).path;if(0==e.length)throw new F(44);b=f+"/"+e}var g=d?B():0;return Hb(b,c,g).te}catch(l){if("undefined"==typeof M||"ErrnoError"!==l.name)throw l;return-l.ce}},cb:()=>Da(""),Ta:()=>{x=!1;O=0},Ua:(a,b)=>{Kb[a]&&(clearTimeout(Kb[a].id),delete Kb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Kb[a];Ob(()=>fe(a,performance.now()))},b);Kb[a]={id:c,Ug:b};return 0},y:Sb,d:(a,b,c)=>{b=Qb(b,c);return Rb[a](...b)},a:Sb,
oc:(a,b,c)=>{b=Qb(b,c);return Rb[a](...b)},cd:()=>{lc();Vb=null},bb:()=>Date.now(),Na:()=>{if(!P.fullscreenEnabled())return-1;pc(Gc);var a=tc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Vb:()=>{pc(Hc);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},gb:a=>{x=!1;O=0;la=a;x||0<O||va();Mb(a)},f:()=>devicePixelRatio,b:(a,b,c)=>{a=R(a);if(!a)return-4;a=
Fc(a);v[b>>3]=a.width;v[c>>3]=a.height;return 0},X:(a,b)=>{a&&(r[a>>2]=Tb);b&&(r[b>>2]=Ub)},j:()=>performance.now(),Jc:(a,b)=>{r[a>>2]=screen.width;r[b>>2]=screen.height},ta:a=>S.activeTexture(a),sa:(a,b)=>{S.attachShader(T[a],U[b])},Ja:(a,b)=>{S.me.beginQueryEXT(a,V[b])},ra:(a,b,c)=>{S.bindAttribLocation(T[a],b,c?D(q,c):"")},qa:(a,b)=>{S.bindBuffer(a,Uc[b])},pa:(a,b)=>{S.bindFramebuffer(a,Vc[b])},oa:(a,b)=>{S.bindRenderbuffer(a,Wc[b])},na:(a,b)=>{S.bindTexture(a,Xc[b])},Ba:a=>{S.bindVertexArray(Yc[a])},
ma:(a,b,c,d)=>S.blendColor(a,b,c,d),la:a=>S.blendEquation(a),ka:(a,b)=>S.blendEquationSeparate(a,b),ja:(a,b)=>S.blendFunc(a,b),ia:(a,b,c,d)=>S.blendFuncSeparate(a,b,c,d),ha:(a,b,c,d)=>{S.bufferData(a,c?q.subarray(c,c+b):b,d)},ga:(a,b,c,d)=>{S.bufferSubData(a,b,q.subarray(d,d+c))},fa:a=>S.checkFramebufferStatus(a),ea:a=>S.clear(a),da:(a,b,c,d)=>S.clearColor(a,b,c,d),ca:a=>S.clearDepth(a),ba:a=>S.clearStencil(a),hb:(a,b)=>{S.Yf.clipControlEXT(a,b)},aa:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},$:a=>
{S.compileShader(U[a])},_:(a,b,c,d,e,f,g,l)=>{S.compressedTexImage2D(a,b,c,d,e,f,q.subarray(l,l+g))},Z:(a,b,c,d,e,f,g,l,n)=>{S.compressedTexSubImage2D(a,b,c,d,e,f,g,q.subarray(n,n+l))},Y:(a,b,c,d,e,f,g,l)=>S.copyTexImage2D(a,b,c,d,e,f,g,l),W:(a,b,c,d,e,f,g,l)=>S.copyTexSubImage2D(a,b,c,d,e,f,g,l),V:()=>{var a=cd(T),b=S.createProgram();b.name=a;b.Qe=b.Oe=b.Pe=0;b.sf=1;T[a]=b;return a},U:a=>{var b=cd(U);U[b]=S.createShader(a);return b},T:a=>S.cullFace(a),S:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>
2],e=Uc[d];e&&(S.deleteBuffer(e),e.name=0,Uc[d]=null)}},R:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+4*c>>2],e=Vc[d];e&&(S.deleteFramebuffer(e),e.name=0,Vc[d]=null)}},Q:a=>{if(a){var b=T[a];b?(S.deleteProgram(b),b.name=0,T[a]=null):W||=1281}},La:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=V[d];e&&(S.me.deleteQueryEXT(e),V[d]=null)}},P:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Wc[d];e&&(S.deleteRenderbuffer(e),e.name=0,Wc[d]=null)}},O:a=>{if(a){var b=U[a];b?(S.deleteShader(b),U[a]=null):W||=
1281}},N:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Xc[d];e&&(S.deleteTexture(e),e.name=0,Xc[d]=null)}},Aa:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2];S.deleteVertexArray(Yc[d]);Yc[d]=null}},L:a=>S.depthFunc(a),K:a=>{S.depthMask(!!a)},J:(a,b)=>S.depthRange(a,b),I:(a,b)=>{S.detachShader(T[a],U[b])},H:a=>S.disable(a),G:a=>{S.disableVertexAttribArray(a)},F:(a,b,c)=>{S.drawArrays(a,b,c)},wa:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},xa:(a,b)=>{for(var c=hd[a],d=0;d<a;d++)c[d]=r[b+4*d>>2];S.drawBuffers(c)},
E:(a,b,c,d)=>{S.drawElements(a,b,c,d)},va:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},D:a=>S.enable(a),C:a=>{S.enableVertexAttribArray(a)},Ia:a=>{S.me.endQueryEXT(a)},bd:()=>S.finish(),ad:()=>S.flush(),$c:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,Wc[d])},_c:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,Xc[d],e)},Zc:a=>S.frontFace(a),Yc:(a,b)=>{dd(a,b,"createBuffer",Uc)},Wc:(a,b)=>{dd(a,b,"createFramebuffer",Vc)},Ma:(a,b)=>{for(var c=0;c<a;c++){var d=S.me.createQueryEXT();if(!d){for(W||=1282;c<
a;)r[b+4*c++>>2]=0;break}var e=cd(V);d.name=e;V[e]=d;r[b+4*c>>2]=e}},Vc:(a,b)=>{dd(a,b,"createRenderbuffer",Wc)},Uc:(a,b)=>{dd(a,b,"createTexture",Xc)},za:(a,b)=>{dd(a,b,"createVertexArray",Yc)},Xc:a=>S.generateMipmap(a),Tc:(a,b,c,d,e,f,g)=>jd("getActiveAttrib",a,b,c,d,e,f,g),Sc:(a,b,c,d,e,f,g)=>jd("getActiveUniform",a,b,c,d,e,f,g),Rc:(a,b,c,d)=>{a=S.getAttachedShaders(T[a]);var e=a.length;e>b&&(e=b);r[c>>2]=e;for(b=0;b<e;++b)r[d+4*b>>2]=U.indexOf(a[b])},Qc:(a,b)=>S.getAttribLocation(T[a],b?D(q,b):
""),Pc:(a,b)=>kd(a,b,4),Oc:(a,b,c)=>{c?r[c>>2]=S.getBufferParameter(a,b):W||=1281},Nc:()=>{var a=S.getError()||W;W=0;return a},Mc:(a,b)=>kd(a,b,2),Lc:(a,b,c,d)=>{a=S.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r[d>>2]=a},Kc:(a,b)=>kd(a,b,0),Hc:(a,b,c,d)=>{a=S.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,q,d,b):0;c&&(r[c>>2]=b)},Ic:(a,b,c)=>{if(c)if(a>=Tc)W||=1281;else if(a=T[a],35716==b)a=S.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(35719==b){if(!a.Qe){var d=S.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Qe=Math.max(a.Qe,S.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.Qe}else if(35722==b){if(!a.Oe)for(d=S.getProgramParameter(a,35721),b=0;b<d;++b)a.Oe=Math.max(a.Oe,S.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.Oe}else if(35381==b){if(!a.Pe)for(d=S.getProgramParameter(a,35382),b=0;b<d;++b)a.Pe=Math.max(a.Pe,S.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.Pe}else r[c>>
2]=S.getProgramParameter(a,b);else W||=1281},Da:ld,Fa:md,Ca:ld,Ea:md,Ga:(a,b,c)=>{c?r[c>>2]=S.me.getQueryEXT(a,b):W||=1281},Gc:(a,b,c)=>{c?r[c>>2]=S.getRenderbufferParameter(a,b):W||=1281},Ec:(a,b,c,d)=>{a=S.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,q,d,b):0;c&&(r[c>>2]=b)},Dc:(a,b,c,d)=>{a=S.getShaderPrecisionFormat(a,b);r[c>>2]=a.rangeMin;r[c+4>>2]=a.rangeMax;r[d>>2]=a.precision},Cc:(a,b,c,d)=>{if(a=S.getShaderSource(U[a]))b=0<b&&d?E(a,q,d,b):0,c&&(r[c>>2]=b)},Fc:(a,b,
c)=>{c?35716==b?(a=S.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(U[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=S.getShaderParameter(U[a],b):W||=1281},Bc:a=>{var b=$c[a];if(!b){switch(a){case 7939:b=nd(od().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=S.getParameter(a))||(W||=1280);b=b?nd(b):0;break;case 7938:b=nd(`OpenGL ES 2.0 (${S.getParameter(7938)})`);break;case 35724:b=S.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=nd(b);break;default:W||=1280}$c[a]=b}return b},Ac:(a,b,c)=>{c?u[c>>2]=S.getTexParameter(a,b):W||=1281},zc:(a,b,c)=>{c?r[c>>2]=S.getTexParameter(a,b):W||=1281},wc:(a,b)=>{b=b?D(q,b):"";if(a=T[a]){qd(a);var c=a.Je,d=0,e=b,f=pd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Lf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else W||=1281;return-1},yc:(a,b,c)=>{rd(a,b,c,2)},xc:(a,b,c)=>{rd(a,
b,c,0)},tc:(a,b,c)=>{c?r[c>>2]=S.getVertexAttribOffset(a,b):W||=1281},vc:(a,b,c)=>{sd(a,b,c,2)},uc:(a,b,c)=>{sd(a,b,c,5)},sc:(a,b)=>S.hint(a,b),rc:a=>(a=Uc[a])?S.isBuffer(a):0,qc:a=>S.isEnabled(a),pc:a=>(a=Vc[a])?S.isFramebuffer(a):0,nc:a=>(a=T[a])?S.isProgram(a):0,Ka:a=>(a=V[a])?S.me.isQueryEXT(a):0,mc:a=>(a=Wc[a])?S.isRenderbuffer(a):0,lc:a=>(a=U[a])?S.isShader(a):0,kc:a=>(a=Xc[a])?S.isTexture(a):0,ya:a=>(a=Yc[a])?S.isVertexArray(a):0,jc:a=>S.lineWidth(a),ic:a=>{a=T[a];S.linkProgram(a);a.Je=0;a.Lf=
{}},hc:(a,b)=>{3317==a?ad=b:3314==a&&(bd=b);S.pixelStorei(a,b)},fb:(a,b)=>{S.sg.polygonModeWEBGL(a,b)},gc:(a,b)=>S.polygonOffset(a,b),ib:(a,b,c)=>{S.Zf.polygonOffsetClampEXT(a,b,c)},Ha:(a,b)=>{S.me.queryCounterEXT(V[a],b)},fc:(a,b,c,d,e,f,g)=>{(g=td(f,e,c,d,g))?S.readPixels(a,b,c,d,e,f,g):W||=1280},ec:()=>{},dc:(a,b,c,d)=>S.renderbufferStorage(a,b,c,d),cc:(a,b)=>{S.sampleCoverage(a,!!b)},bc:(a,b,c,d)=>S.scissor(a,b,c,d),ac:()=>{W||=1280},$b:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=t[c+4*f>>
2])?D(q,g,d?t[d+4*f>>2]:void 0):"";e+=g}S.shaderSource(U[a],e)},_b:(a,b,c)=>S.stencilFunc(a,b,c),Zb:(a,b,c,d)=>S.stencilFuncSeparate(a,b,c,d),Yb:a=>S.stencilMask(a),Xb:(a,b)=>S.stencilMaskSeparate(a,b),Wb:(a,b,c)=>S.stencilOp(a,b,c),Ub:(a,b,c,d)=>S.stencilOpSeparate(a,b,c,d),Tb:(a,b,c,d,e,f,g,l,n)=>{n=n?td(l,g,d,e,n):null;S.texImage2D(a,b,c,d,e,f,g,l,n)},Sb:(a,b,c)=>S.texParameterf(a,b,c),Rb:(a,b,c)=>{S.texParameterf(a,b,u[c>>2])},Qb:(a,b,c)=>S.texParameteri(a,b,c),Pb:(a,b,c)=>{S.texParameteri(a,
b,r[c>>2])},Ob:(a,b,c,d,e,f,g,l,n)=>{n=n?td(l,g,e,f,n):null;S.texSubImage2D(a,b,c,d,e,f,g,l,n)},Nb:(a,b)=>{S.uniform1f(Y(a),b)},Mb:(a,b,c)=>{if(288>=b)for(var d=ud[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);S.uniform1fv(Y(a),d)},Lb:(a,b)=>{S.uniform1i(Y(a),b)},Kb:(a,b,c)=>{if(288>=b)for(var d=vd[b],e=0;e<b;++e)d[e]=r[c+4*e>>2];else d=r.subarray(c>>2,c+4*b>>2);S.uniform1iv(Y(a),d)},Jb:(a,b,c)=>{S.uniform2f(Y(a),b,c)},Ib:(a,b,c)=>{if(144>=b){b*=2;for(var d=ud[b],e=0;e<b;e+=2)d[e]=
u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);S.uniform2fv(Y(a),d)},Hb:(a,b,c)=>{S.uniform2i(Y(a),b,c)},Gb:(a,b,c)=>{if(144>=b){b*=2;for(var d=vd[b],e=0;e<b;e+=2)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2]}else d=r.subarray(c>>2,c+8*b>>2);S.uniform2iv(Y(a),d)},Fb:(a,b,c,d)=>{S.uniform3f(Y(a),b,c,d)},Eb:(a,b,c)=>{if(96>=b){b*=3;for(var d=ud[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);S.uniform3fv(Y(a),d)},Db:(a,
b,c,d)=>{S.uniform3i(Y(a),b,c,d)},Cb:(a,b,c)=>{if(96>=b){b*=3;for(var d=vd[b],e=0;e<b;e+=3)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2]}else d=r.subarray(c>>2,c+12*b>>2);S.uniform3iv(Y(a),d)},Bb:(a,b,c,d,e)=>{S.uniform4f(Y(a),b,c,d,e)},Ab:(a,b,c)=>{if(72>=b){var d=ud[4*b],e=u;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=u.subarray(c>>2,c+16*b>>2);S.uniform4fv(Y(a),d)},zb:(a,b,c,d,e)=>{S.uniform4i(Y(a),b,c,d,e)},yb:(a,b,c)=>
{if(72>=b){b*=4;for(var d=vd[b],e=0;e<b;e+=4)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2],d[e+3]=r[c+(4*e+12)>>2]}else d=r.subarray(c>>2,c+16*b>>2);S.uniform4iv(Y(a),d)},xb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=ud[b],f=0;f<b;f+=4)e[f]=u[d+4*f>>2],e[f+1]=u[d+(4*f+4)>>2],e[f+2]=u[d+(4*f+8)>>2],e[f+3]=u[d+(4*f+12)>>2]}else e=u.subarray(d>>2,d+16*b>>2);S.uniformMatrix2fv(Y(a),!!c,e)},wb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=ud[b],f=0;f<b;f+=9)e[f]=u[d+4*f>>2],e[f+1]=u[d+(4*f+4)>>2],e[f+
2]=u[d+(4*f+8)>>2],e[f+3]=u[d+(4*f+12)>>2],e[f+4]=u[d+(4*f+16)>>2],e[f+5]=u[d+(4*f+20)>>2],e[f+6]=u[d+(4*f+24)>>2],e[f+7]=u[d+(4*f+28)>>2],e[f+8]=u[d+(4*f+32)>>2]}else e=u.subarray(d>>2,d+36*b>>2);S.uniformMatrix3fv(Y(a),!!c,e)},vb:(a,b,c,d)=>{if(18>=b){var e=ud[16*b],f=u;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];
e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=u.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(Y(a),!!c,e)},ub:a=>{a=T[a];S.useProgram(a);S.Sf=a},tb:a=>{S.validateProgram(T[a])},sb:(a,b)=>S.vertexAttrib1f(a,b),rb:(a,b)=>{S.vertexAttrib1f(a,u[b>>2])},qb:(a,b,c)=>S.vertexAttrib2f(a,b,c),pb:(a,b)=>{S.vertexAttrib2f(a,u[b>>2],u[b+4>>2])},ob:(a,b,c,d)=>S.vertexAttrib3f(a,b,c,d),nb:(a,b)=>{S.vertexAttrib3f(a,u[b>>2],u[b+4>>2],u[b+8>>2])},mb:(a,b,c,d,e)=>S.vertexAttrib4f(a,b,c,d,e),lb:(a,b)=>{S.vertexAttrib4f(a,
u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},ua:(a,b)=>{S.vertexAttribDivisor(a,b)},kb:(a,b,c,d,e,f)=>{S.vertexAttribPointer(a,b,c,!!d,e,f)},jb:(a,b,c,d)=>S.viewport(a,b,c,d),i:()=>0,Oa:(a,b,c)=>wd(a,{nf:r[c>>2],Ve:r[c+4>>2],$f:r[c+8>>2],Vf:b,Ke:r[c+12>>2],zf:r[c+16>>2]}),z:(a,b)=>{a=R(a);return a?a.requestPointerLock?qc()?Hc(a):b?(oc(Hc,2,[a]),1):-2:-1:-4},Va:a=>{var b=q.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,
65536*Math.ceil(Math.max(a,d)/65536))-ua.buffer.byteLength+65535)/65536|0;try{ua.grow(d);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},k:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:xd(a,b),w:(a,b,c,d)=>yd(a,b,c,d,12,"blur"),c:zc,e:(a,b,c)=>{a=R(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},x:(a,b,c,d)=>yd(a,b,c,d,13,"focus"),s:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=R(a);if(!a)return-4;zd(a,b,c,d,"webkitfullscreenchange");return zd(a,
b,c,d,"fullscreenchange")},o:(a,b,c,d)=>Ad(a,b,c,d,2,"keydown"),m:(a,b,c,d)=>Ad(a,b,c,d,1,"keypress"),n:(a,b,c,d)=>Ad(a,b,c,d,3,"keyup"),Qa:(a,b,c,d)=>{kc(()=>A(a)(b),c,d,b)},g:bc,p:(a,b,c)=>window.screen&&screen.orientation?Bd(a,b,c):-1,t:(a,b,c,d)=>document.body?.requestPointerLock?(a=R(a))?Cd(a,b,c,d):-4:-1,r:(a,b,c,d)=>Dd(a,b,c,d),l:(a,b,c)=>Ed(a,b,c),q:(a,b,c,d)=>(a=R(a))?"undefined"!=typeof a.onwheel?Fd(a,b,c,d):-1:-4,Pa:a=>document.title=a?D(q,a):"",h:()=>{Da("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},
M:(a,b)=>{var c=b>>2;b={alpha:!!m[b+0],depth:!!m[b+1],stencil:!!m[b+2],antialias:!!m[b+3],premultipliedAlpha:!!m[b+4],preserveDrawingBuffer:!!m[b+5],powerPreference:Gd[r[c+2]],failIfMajorPerformanceCaveat:!!m[b+12],ig:r[c+4],Lg:r[c+5],Bf:m[b+24],Xf:m[b+25],Pg:r[c+7],Sg:m[b+32]};a=R(a);return!a||b.Xf?0:fd(a,b)},A:a=>{gd==a&&(gd=0);gd===Zc[a]&&(gd=null);"object"==typeof P&&P.og(Zc[a].we.canvas);Zc[a]?.we.canvas&&(Zc[a].we.canvas.ze=void 0);Zc[a]=null},B:a=>{gd=Zc[a];h.ctx=S=gd?.we;return!a||S?0:-5},
db:(a,b)=>{var c=0,d=0,e;for(e of Jd()){var f=b+c;t[a+d>>2]=f;c+=E(e,q,f,Infinity)+1;d+=4}return 0},eb:(a,b)=>{var c=Jd();t[a>>2]=c.length;a=0;for(var d of c)a+=$a(d)+1;t[b>>2]=a;return 0},v:function(a){try{var b=J(a);Ca(b);return 0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return c.ce}},Za:function(a,b,c,d){try{a:{var e=J(a);a=b;for(var f,g=b=0;g<c;g++){var l=t[a>>2],n=t[a+4>>2];a+=8;var p=e,z=l,y=n,C=f,N=m;if(0>y||0>C)throw new F(28);if(null===p.te)throw new F(8);if(1===(p.flags&
2097155))throw new F(8);if(H(p.node.mode))throw new F(31);if(!p.Qd.read)throw new F(28);var ha="undefined"!=typeof C;if(!ha)C=p.position;else if(!p.seekable)throw new F(70);var ia=p.Qd.read(p,N,z,y,C);ha||(p.position+=ia);var ma=ia;if(0>ma){var ab=-1;break a}b+=ma;if(ma<n)break;"undefined"!=typeof f&&(f+=ma)}ab=b}t[d>>2]=ab;return 0}catch(Ea){if("undefined"==typeof M||"ErrnoError"!==Ea.name)throw Ea;return Ea.ce}},Wa:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;
var e=J(a);Ib(e,b,c);w[d>>3]=BigInt(e.position);e.ef&&0===b&&0===c&&(e.ef=null);return 0}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return f.ce}},Ya:function(a,b,c,d){try{a:{var e=J(a);a=b;for(var f,g=b=0;g<c;g++){var l=t[a>>2],n=t[a+4>>2];a+=8;var p=Jb(e,m,l,n,f);if(0>p){var z=-1;break a}b+=p;if(p<n)break;"undefined"!=typeof f&&(f+=p)}z=b}t[d>>2]=z;return 0}catch(y){if("undefined"==typeof M||"ErrnoError"!==y.name)throw y;return y.ce}},Sa:Mb};
function he(a=[]){var b=ee;a.unshift(ba);var c=a.length,d=uc(4*(c+1)),e=d,f;for(f of a)t[e>>2]=vc(f),e+=4;t[e>>2]=0;try{var g=b(c,d);la=g;x||0<O||va();Mb(g)}catch(l){Lb(l)}}var ie;
ie=await (async function(){function a(c){c=ie=c.exports;h._upload_rom=c.fd;h._set_button_state=c.gd;h._set_channel_muted=c.hd;h._is_channel_muted=c.id;h._set_master_volume=c.jd;h._get_master_volume=c.kd;h._get_frame_count=c.ld;h._get_cart_ram_ptr=c.md;h._get_cart_ram_size=c.nd;h._import_save=c.od;h._shutdown_emulator=c.pd;ee=h._main=c.qd;Wd=h._SDL_free=c.rd;Td=h._SDL_malloc=c.sd;h._SDL_calloc=c.td;h._SDL_realloc=c.ud;Aa=c.vd;X=h._malloc=c.wd;be=h._free=c.xd;Xd=h._Emscripten_HandlePointerEnter=
c.yd;Yd=h._Emscripten_HandlePointerLeave=c.zd;Zd=h._Emscripten_HandlePointerGeneric=c.Ad;Vd=h._Emscripten_HandleMouseButtonUpGlobal=c.Bd;$d=h._Emscripten_SendDragEvent=c.Cd;de=h._Emscripten_SendDragCompleteEvent=c.Dd;ae=h._Emscripten_SendDragTextEvent=c.Ed;ce=h._Emscripten_SendDragFileEvent=c.Fd;Ud=h._Emscripten_HandleLockKeysCheck=c.Gd;Sd=h._Emscripten_SendSystemThemeChangedEvent=c.Hd;Rd=h._requestFullscreenThroughSDL=c.Id;wa=c.Kd;fe=c.Ld;xc=c.Md;uc=c.Nd;wc=c.Od;ua=c.dd;Pa=c.Jd;ta();return ie}var b=
{a:ge};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});Fa??=h.locateFile?h.locateFile?h.locateFile("GBC.wasm",da):da+"GBC.wasm":(new URL("GBC.wasm",import.meta.url)).href;return a((await Ia(b)).instance)}());
(function(a=aa){function b(){h.calledRun=!0;if(!ka){ra=!0;if(!h.noFSInit&&!za){var c,d;za=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?L("stdin",c):Gb("/dev/tty","/dev/stdin");d?L("stdout",null,d):Gb("/dev/tty","/dev/stdout");e?L("stderr",null,e):Gb("/dev/tty1","/dev/stderr");Hb("/dev/stdin",0);Hb("/dev/stdout",1);Hb("/dev/stderr",1)}ie.ed();qb=!1;na?.(h);h.onRuntimeInitialized?.();h.noInitialRun||he(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Ka.push(e)}xa(Ka)}}if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ma();xa(La);h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()})();ra?moduleRtn=h:moduleRtn=new Promise((a,b)=>{na=a;oa=b});
;return moduleRtn}export default createGBCModule;
